local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-FactionHomeLayer_group_faction_Game",
			UUID = "2062fd3e_763f_43ca_b0f2_50ad231ef5dc",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_List_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "2b6ed2f7_6533_4d4b_a742_bb048ed53f06",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_List",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Bg_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "7c1332b7_229a_4d4b_bf3b_9adb7b831495",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "bg_jpg/bp_beijing_bg.jpg",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -88,
								TopPosition = 66,
								relativeToName = "Panel",
								nGravity = 2,
								nAlign = 2
							},
							width = "2114",
							ZOrder = "1",
						},
						{
							controlID = "btn_zyt_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "68d52920_c39a_4872_af8e_46356b3d9640",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "153",
							HitType = 
							{
								nHitType = 1,
								nXpos = 0,
								nYpos = 0,
								nHitWidth = 270,
								nHitHeight = 182
							},
							ignoreSize = "True",
							name = "btn_zyt",
							normal = "ui_new/faction/n1a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 128,
								PositionY = 400,
							},
							UItype = "Button",
							width = "261",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_biaoti_btn_zyt_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "5aaf0aff_4017_4d12_8a3e_1831adc0606c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "148",
									ignoreSize = "True",
									name = "img_biaoti",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -90,
										PositionY = 30,
									},
									width = "49",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_jyt_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "6b18d754_250c_4dcb_8219_eabca3a229a8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "272",
							HitType = 
							{
								nHitType = 1,
								nXpos = 0,
								nYpos = 0,
								nHitWidth = 313,
								nHitHeight = 273
							},
							ignoreSize = "True",
							name = "btn_jyt",
							normal = "ui_new/faction/n2a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 542,
								PositionY = 343,
							},
							UItype = "Button",
							width = "330",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_biaoti_btn_jyt_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "a5bb639b_3884_41d5_9220_4e6154fc3c21",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "148",
									ignoreSize = "True",
									name = "img_biaoti",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -129,
										PositionY = 61,
									},
									width = "49",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_zbg_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "cf3cd8a4_1485_4acd_86e8_ee8d939dc2d6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "147",
							HitType = 
							{
								nHitType = 1,
								nXpos = -28,
								nYpos = -23,
								nHitWidth = 206,
								nHitHeight = 187
							},
							ignoreSize = "True",
							name = "btn_zbg",
							normal = "ui_new/faction/n3a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 228,
								PositionY = 220,
							},
							UItype = "Button",
							width = "168",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_biaoti_btn_zbg_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "8a172088_359e_4d62_98f3_830599631f4a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "148",
									ignoreSize = "True",
									name = "img_biaoti",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -86,
										PositionY = 19,
									},
									width = "50",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_hs_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "5689b408_1163_4fc5_ab8b_838301021f52",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "163",
							HitType = 
							{
								nHitType = 1,
								nXpos = -38,
								nYpos = 9,
								nHitWidth = 260,
								nHitHeight = 190
							},
							ignoreSize = "True",
							name = "btn_hs",
							normal = "ui_new/faction/n5a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 837,
								PositionY = 393,
							},
							UItype = "Button",
							width = "162",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_biaoti_btn_hs_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "8a2a5bec_c32d_4689_bff9_2dfa477533ab",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "111",
									ignoreSize = "True",
									name = "img_biaoti",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n5.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -90,
										PositionY = 43,
									},
									width = "49",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_bangpaizhan_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "f451788c_3038_4e80_8a87_527ff95cbe1b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "318",
							ignoreSize = "True",
							name = "btn_bangpaizhan",
							normal = "ui_new/faction/n6a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 1547,
								PositionY = 327,
							},
							UItype = "Button",
							width = "430",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_biaoti_btn_bangpaizhan_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "3494acc7_b74e_4a57_91b8_a349caf69f74",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "142",
									ignoreSize = "True",
									name = "img_biaoti",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n6.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -145,
										PositionY = 101,
									},
									width = "38",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "img_pd_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "dad5cec6_ec67_4175_a482_0ee9e99c4447",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "img_pd",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "bg_jpg/bg_beijing_pd.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -88,
							},
							visible = "False",
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "btn_xlc_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "989b9791_29dd_4a5d_9ada_b51ee54b2ae4",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "284",
							HitType = 
							{
								nHitType = 1,
								nXpos = 76,
								nYpos = 70,
								nHitWidth = 300,
								nHitHeight = 215
							},
							ignoreSize = "True",
							name = "btn_xlc",
							normal = "ui_new/faction/n4a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 830,
								PositionY = 174,
							},
							UItype = "Button",
							width = "436",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_biaoti_btn_xlc_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "b1ed9915_e9f3_477e_8b4a_a67aa5d900c5",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "148",
									ignoreSize = "True",
									name = "img_biaoti",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n4.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -116,
										PositionY = 39,
									},
									width = "51",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_ywc_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "41c32541_911e_4f78_b81b_eebf60b2defa",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "240",
							HitType = 
							{
								nHitType = 1,
								nXpos = -14,
								nYpos = 47,
								nHitWidth = 300,
								nHitHeight = 192
							},
							ignoreSize = "True",
							name = "btn_ywc",
							normal = "ui_new/faction/n7a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 1195,
								PositionY = 347,
							},
							UItype = "Button",
							width = "323",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_ywcrk_btn_ywc_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "7b0e3d67_f7e6_4e2d_a58d_b85d94e76fde",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "147",
									ignoreSize = "True",
									name = "img_ywcrk",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n7.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -157,
										PositionY = 43,
									},
									width = "53",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_jst_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "60e5b8b3_7617_4c62_ad05_3f067471bcfa",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "154",
							HitType = 
							{
								nHitType = 1,
								nXpos = -23,
								nYpos = -9,
								nHitWidth = 186,
								nHitHeight = 170
							},
							ignoreSize = "True",
							name = "btn_jst",
							normal = "ui_new/faction/n8a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 425,
								PositionY = 121,
							},
							UItype = "Button",
							width = "152",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_biaoti_btn_jst_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "229f93e2_dcc4_4784_b6b1_d837753508cc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "147",
									ignoreSize = "True",
									name = "img_biaoti",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n8.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -82,
										PositionY = 34,
									},
									width = "53",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_df_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "82df2abb_f285_4e91_b416_1729931cb058",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "225",
							HitType = 
							{
								nHitType = 1,
								nXpos = 27,
								nYpos = 19,
								nHitWidth = 287,
								nHitHeight = 206
							},
							ignoreSize = "True",
							name = "btn_df",
							normal = "ui_new/faction/n9a.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 1203,
								PositionY = 113,
							},
							UItype = "Button",
							width = "337",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_biaoti_btn_df_Panel_List_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "0378d075_1b80_4e70_aae8_de1339e61e77",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "114",
									ignoreSize = "True",
									name = "img_biaoti",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/n9.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -126,
										PositionY = 63,
									},
									width = "51",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "panel_head_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "33acde06_8781_4d46_be20_39ca7875e850",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "66",
					ignoreSize = "False",
					name = "panel_head",
					sizepercentx = "100",
					sizepercenty = "10",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = 576,
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
				},
				{
					controlID = "Btn_jhp_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "83c9a858_8794_4aba_bb5a_29460d54aab0",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "56",
					ignoreSize = "True",
					name = "Btn_jhp",
					normal = "ui_new/faction/btn_jianghupu.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 1014,
						PositionY = 36,
						RightPosition = 9,
						BottomPosition = 8,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 9
					},
					UItype = "Button",
					width = "194",
					ZOrder = "1",
				},
				{
					controlID = "panel_msg_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "6240e31a_a74b_4ec8_b87c_68111296cd37",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "True",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "38",
					ignoreSize = "False",
					name = "panel_msg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 372,
						PositionY = 36,
						LeftPositon = 22,
						BottomPosition = 17,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "700",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_gonggao_panel_msg_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "aea7b944_7d0b_42cd_b11a_96b396a041fe",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "38",
							ignoreSize = "False",
							name = "bg_gonggao",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/common/bg_heijianbian.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								LeftPositon = 22,
								BottomPosition = 17,
								relativeToName = "Panel",
								nGravity = 4,
								nAlign = 7
							},
							width = "700",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_FactionHomeLayer_1_bg_gonggao_panel_msg_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "49d137cc_e285_407c_a1ee_1a2084dc0bd2",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "36",
									ignoreSize = "False",
									name = "Label_FactionHomeLayer_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "Nội dung thông báo, không hiển thị đủ sẽ dùng hình thức cuộn",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -275,
									},
									width = "600",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Btn_gonggao_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "1f69b201_b241_435e_b883_ae1afd043807",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "56",
					HitType = 
					{
						nHitType = 1,
						nXpos = -6,
						nYpos = -7,
						nHitWidth = 100,
						nHitHeight = 80
					},
					ignoreSize = "True",
					name = "Btn_gonggao",
					normal = "ui_new/faction/btn_gonggao.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 56,
						PositionY = 36,
						LeftPositon = 9,
						BottomPosition = 8,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					UItype = "Button",
					width = "94",
					ZOrder = "1",
				},
				{
					controlID = "Panel_title_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "65cbee7e_fa6d_496b_8b74_4efcdf45f85e",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_title",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_name_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "860cbcd2_c2cd_4aad_ad75_ed168fec5717",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "36",
							ignoreSize = "True",
							name = "bg_name",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/faction/bg_bpming.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 245,
								PositionY = 554,
							},
							width = "472",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_name_bg_name_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "7b2f4583_e48e_4600_9166_6eb904f9f96b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "txt_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Tên bang 6 chữ",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -140,
									},
									width = "147",
									ZOrder = "1",
								},
								{
									controlID = "bg_jindu_bg_name_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "8066d1ce_cc24_430c_ae7b_c84303bcf738",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "18",
									ignoreSize = "True",
									name = "bg_jindu",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/bg_bpjingyan.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 100,
									},
									width = "231",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "bar_exp_bg_jindu_bg_name_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
											UUID = "6fc9121b_905c_4b00_be01_92e73b532d6e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MELoadingBar",
											direction = "0",
											dstBlendFunc = "771",
											height = "18",
											ignoreSize = "False",
											name = "bar_exp",
											percent = "100",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texture = "ui_new/team/team_bar2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "231",
											ZOrder = "1",
										},
										{
											controlID = "txt_exp_bg_jindu_bg_name_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
											UUID = "c4c25a23_5273_425f_9536_050d5b296461",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabelBMFont",
											dstBlendFunc = "771",
											fileNameData = "font/num_217.fnt",
											height = "27",
											ignoreSize = "True",
											name = "txt_exp",
											scaleX = "0.7",
											scaleY = "0.7",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "1111117222222",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -1,
											},
											width = "192",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "txt_level_bg_name_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "30885fef_2335_43b4_ab54_eea95fb31f9d",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "773",
									fileNameData = "font/num_208.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_level",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "38d",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -16,
										PositionY = -4,
									},
									width = "42",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "bg_fangrong_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "8d91ca41_3c9d_48ae_842c_98ebfbcf1ed6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "22",
							ignoreSize = "True",
							name = "bg_fangrong",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/faction/bg_bpfanrong.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 610,
								PositionY = 554,
							},
							width = "231",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_fangrong_bg_fangrong_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "839cd79c_ac84_4aa1_b2f4_d6ec0a3e7bbf",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_215.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_fangrong",
									scaleX = "0.8",
									scaleY = "0.8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "88888888",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "131",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "bg_gongxian_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "74fe88d6_5ab2_4261_a69e_9adc41d2ee06",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "22",
							ignoreSize = "True",
							name = "bg_gongxian",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/faction/bg_bpgongxian.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 843,
								PositionY = 554,
							},
							width = "221",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_gongxian_bg_gongxian_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "9c54c919_0eaf_4d93_9fc9_2fe3000d6785",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_215.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_gongxian",
									scaleX = "0.8",
									scaleY = "0.8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "8888888",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 6,
									},
									width = "115",
									ZOrder = "1",
								},
								{
									controlID = "Image_FactionHomeLayer_1_bg_gongxian_Panel_title_Panel-FactionHomeLayer_group_faction_Game",
									UUID = "f787b20e_e6e1_44e0_952a_86d28c0f239f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "45",
									ignoreSize = "True",
									name = "Image_FactionHomeLayer_1",
									scaleX = "0.6",
									scaleY = "0.6",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/faction/icon_gongxian.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -4,
										PositionY = -1,
									},
									width = "40",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "img_jiantou_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "035abd66_82cc_46ac_839d_1c06a7d9321b",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "83",
					ignoreSize = "True",
					name = "img_jiantou",
					scaleX = "0.8",
					scaleY = "0.8",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/common/right.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 1094,
						PositionY = 354,
						RightPosition = 13,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 6
					},
					width = "33",
					ZOrder = "1",
				},
				{
					controlID = "btn_hongbao_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "f10c6572_5638_465a_9494_baa81fd32129",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "False",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "95",
					ignoreSize = "False",
					name = "btn_hongbao",
					normal = "ui_new/faction/hongbao/btn_bphb_old.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 1054,
						PositionY = 134,
						RightPosition = 18,
						BottomPosition = 86,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 9
					},
					UItype = "Button",
					width = "95",
					ZOrder = "1",
				},
				{
					controlID = "btn_linghongbao_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "da77940a_e524_427f_99ec_ccb597b8d5d9",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "False",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "92",
					ignoreSize = "False",
					name = "btn_linghongbao",
					normal = "ui_new/faction/hongbao/btn_kelingqu_old.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 1054,
						PositionY = 235,
						RightPosition = 18,
						BottomPosition = 189,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 9
					},
					UItype = "Button",
					width = "95",
					ZOrder = "1",
				},
				{
					controlID = "btn_buff3_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "db5964f4_6f37_41a2_b2ef_865be3aa0407",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "70",
					HitType = 
					{
						nHitType = 1,
						nXpos = -20,
						nYpos = -11,
						nHitWidth = 116,
						nHitHeight = 96
					},
					ignoreSize = "True",
					name = "btn_buff3",
					normal = "ui_new/lunjian/icon_bpbuff.png",
					scaleX = "0.8",
					scaleY = "0.8",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 1077,
						PositionY = 580,
						RightPosition = 15,
						TopPosition = 101,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					UItype = "Button",
					width = "70",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "txt_num_btn_buff3_Panel-FactionHomeLayer_group_faction_Game",
							UUID = "a60e3734_148e_4a73_a1ff_983ae054993f",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0.5",
							classname = "MELabelBMFont",
							dstBlendFunc = "771",
							fileNameData = "font/num_55.fnt",
							height = "27",
							ignoreSize = "True",
							name = "txt_num",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							text = "15%",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 25,
								PositionY = 14,
							},
							width = "35",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "btn_hyhb_Panel-FactionHomeLayer_group_faction_Game",
					UUID = "91f01f0a_3d3a_48db_9675_fb24b936c403",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "99",
					ignoreSize = "True",
					name = "btn_hyhb",
					normal = "ui_new/faction/hongbao/btn_hyhb.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 66,
						PositionY = 134,
						LeftPositon = 18,
						BottomPosition = 84,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					UItype = "Button",
					width = "95",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		Action0 = 
		{
			name = "Action0",
			FPS = 24,
			duration = 2.08,
			looptimes = 1,
			autoplay = false,
			{
				id = "img_jiantou_Panel-FactionHomeLayer_group_faction_Game",
				name = "Panel.img_jiantou",
				frames = 
				{
					
					{
						alpha = 255,
						color = 
						{
							r=255,
							g=255,
							b=255,
							 a=255,
						},
						dstBlendFunc = 771,
						frame = 0,
						MixColor = 
						{
							r=0,
							g=0,
							b=0,
							 a=0,
						},
						percentenable = false,
						perposition = 
						{
							x=97.19,
							y=50,
						},
						position = 
						{
							x=933,
							y=320,
						},
						rotate = 0,
						scale = 
						{
							x=1,
							y=1,
						},
						srcBlendFunc = 1,
						tweenToNext = true,
						visible = true,
					},
					{
						alpha = 255,
						color = 
						{
							r=255,
							g=255,
							b=255,
							 a=255,
						},
						dstBlendFunc = 771,
						frame = 25,
						MixColor = 
						{
							r=0,
							g=0,
							b=0,
							 a=0,
						},
						percentenable = false,
						perposition = 
						{
							x=98.75,
							y=50,
						},
						position = 
						{
							x=948,
							y=320,
						},
						rotate = 0,
						scale = 
						{
							x=1,
							y=1,
						},
						srcBlendFunc = 1,
						tweenToNext = true,
						visible = true,
					},
					{
						alpha = 255,
						color = 
						{
							r=255,
							g=255,
							b=255,
							 a=255,
						},
						dstBlendFunc = 771,
						frame = 50,
						MixColor = 
						{
							r=0,
							g=0,
							b=0,
							 a=0,
						},
						percentenable = false,
						perposition = 
						{
							x=97.19,
							y=50,
						},
						position = 
						{
							x=933,
							y=320,
						},
						rotate = 0,
						scale = 
						{
							x=1,
							y=1,
						},
						srcBlendFunc = 1,
						tweenToNext = true,
						visible = true,
					},
				},
			},
		},
	},
	respaths = 
	{
		textures = 
		{
			"bg_jpg/bp_beijing_bg.jpg",
			"ui_new/faction/n1a.png",
			"ui_new/faction/n1.png",
			"ui_new/faction/n2a.png",
			"ui_new/faction/n2.png",
			"ui_new/faction/n3a.png",
			"ui_new/faction/n3.png",
			"ui_new/faction/n5a.png",
			"ui_new/faction/n5.png",
			"ui_new/faction/n6a.png",
			"ui_new/faction/n6.png",
			"bg_jpg/bg_beijing_pd.png",
			"ui_new/faction/n4a.png",
			"ui_new/faction/n4.png",
			"ui_new/faction/n7a.png",
			"ui_new/faction/n7.png",
			"ui_new/faction/n8a.png",
			"ui_new/faction/n8.png",
			"ui_new/faction/n9a.png",
			"ui_new/faction/n9.png",
			"ui_new/faction/btn_jianghupu.png",
			"ui_new/common/bg_heijianbian.png",
			"ui_new/faction/btn_gonggao.png",
			"ui_new/faction/bg_bpming.png",
			"ui_new/faction/bg_bpjingyan.png",
			"ui_new/team/team_bar2.png",
			"ui_new/faction/bg_bpfanrong.png",
			"ui_new/faction/bg_bpgongxian.png",
			"ui_new/faction/icon_gongxian.png",
			"ui_new/common/right.png",
			"ui_new/faction/hongbao/btn_bphb_old.png",
			"ui_new/faction/hongbao/btn_kelingqu_old.png",
			"ui_new/lunjian/icon_bpbuff.png",
			"ui_new/faction/hongbao/btn_hyhb.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

