local t = 
{
	version = 1,
	components = 
	{
		
		{
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "710",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1120",
			ZOrder = "1",
			components = 
			{
				
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "770",
					texturePath = "bg_jpg/cjjs_bj_bg.jpg",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					width = "1136",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "64",
					ignoreSize = "True",
					name = "img_house_bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						RightPosition = 448,
						TopPosition = 288,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "64",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "513",
					ignoreSize = "True",
					name = "img_wuyan",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/bg_wuyan.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 450,
						PositionY = 256,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					width = "901",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "55",
					ignoreSize = "True",
					name = "biaoti",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/cjjs_cjjs_title.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 116,
						PositionY = 599,
						TopPosition = 13,
						relativeToName = "Panel",
						nType = 3,
					},
					width = "233",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "anim_panel",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 204,
						PositionY = 163,
						LeftPositon = 204,
						TopPosition = 77,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "panel_flower",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = -69,
						TopPosition = 309,
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "450",
					ignoreSize = "True",
					name = "role_big",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/role_1.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 220,
						PositionY = 342,
						LeftPositon = -40,
						TopPosition = 73,
						relativeToName = "Panel",
						nType = 3,
					},
					width = "520",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "bg_zhiye",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/cjjs_smd_icon.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 776,
						PositionY = 320,
						RightPosition = 117,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "134",
					ZOrder = "1",
					components = 
					{
						
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "144",
							HitType = 
							{
								nHitType = 1,
								nXpos = 0,
								nYpos = 9,
								nHitWidth = 212,
								nHitHeight = 126
							},
							ignoreSize = "True",
							name = "Button_CreatePlayerNew_1",
							normal = "ui_new/createplayer/g1b.png",
							pressed = "ui_new/createplayer/g1.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = 156,
							},
							UItype = "Button",
							width = "166",
							ZOrder = "1",
						},
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "142",
							ignoreSize = "True",
							name = "Button_CreatePlayerNew_2",
							normal = "ui_new/createplayer/g3b.png",
							pressed = "ui_new/createplayer/g3.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -79,
								PositionY = 31,
							},
							UItype = "Button",
							width = "171",
							ZOrder = "1",
						},
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "147",
							ignoreSize = "True",
							name = "Button_CreatePlayerNew_3",
							normal = "ui_new/createplayer/g4b.png",
							pressed = "ui_new/createplayer/g4.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -12,
								PositionY = -102,
							},
							UItype = "Button",
							width = "150",
							ZOrder = "1",
						},
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "142",
							ignoreSize = "True",
							name = "Button_CreatePlayerNew_4",
							normal = "ui_new/createplayer/g2b.png",
							pressed = "ui_new/createplayer/g2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 89,
								PositionY = 25,
							},
							UItype = "Button",
							width = "173",
							ZOrder = "1",
						},
					},
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "102",
					ignoreSize = "True",
					name = "bg_shuoming",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/bg_txt.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 253,
						PositionY = 141,
						LeftPositon = 131,
						TopPosition = 448,
						relativeToName = "Panel",
						nType = 3,
					},
					width = "245",
					ZOrder = "1",
					components = 
					{
						
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "113",
							ignoreSize = "True",
							name = "Img_zhiye",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/common/img_role_type1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -143,
								PositionY = 8,
							},
							width = "44",
							ZOrder = "1",
						},
						{
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "METextArea",
							dstBlendFunc = "771",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							hAlignment = "0",
							height = "25",
							ignoreSize = "False",
							name = "TextDesc1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							text = "剑魔传人",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -113,
								PositionY = 21,
							},
							vAlignment = "0",
							width = "220",
							ZOrder = "1",
						},
						{
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "METextArea",
							dstBlendFunc = "771",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							hAlignment = "0",
							height = "25",
							ignoreSize = "False",
							name = "TextDesc2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							text = "玄铁重剑无坚不摧",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -113,
								PositionY = -11,
							},
							vAlignment = "0",
							width = "220",
							ZOrder = "1",
						},
					},
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "70",
					ignoreSize = "True",
					name = "Btn_star",
					normal = "ui_new/createplayer/cjjs_qd_btn.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 776,
						PositionY = 60,
						RightPosition = 106,
						TopPosition = 545,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					UItype = "Button",
					width = "156",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "41",
					ignoreSize = "True",
					name = "bg_name",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/cjjs_jsmc_icon.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 59,
						TopPosition = 560,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					width = "429",
					ZOrder = "1",
					components = 
					{
						
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "41",
							HitType = 
							{
								nHitType = 1,
								nXpos = -10,
								nYpos = -17,
								nHitWidth = 80,
								nHitHeight = 80
							},
							ignoreSize = "True",
							name = "Btn_rename",
							normal = "ui_new/createplayer/cjjs_sj_icon.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 141,
							},
							UItype = "Button",
							width = "40",
							ZOrder = "1",
						},
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "METextField",
							CursorEnabled = "True",
							dstBlendFunc = "771",
							fontName = "simhei",
							fontSize = "26",
							hAlignment = "0",
							height = "26",
							HitType = 
							{
								nHitType = 1,
								nXpos = -70,
								nYpos = -50,
								nHitWidth = 230,
								nHitHeight = 150
							},
							ignoreSize = "True",
							KeyBoradType = "0",
							maxLengthEnable = "True;maxLength:16",
							name = "playernameInput",
							passwordEnable = "False",
							placeHolder = "请输入名称",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 4,
								PositionY = 1,
							},
							vAlignment = "0",
							width = "130",
							ZOrder = "9",
						},
					},
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "50",
					ignoreSize = "True",
					name = "btn_tianxie",
					normal = "ui_new/qiyu/family/btn_tianxie.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 137,
						PositionY = 58,
						LeftPositon = 57,
						TopPosition = 557,
						relativeToName = "Panel",
						nType = 3,
					},
					UItype = "Button",
					width = "161",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"bg_jpg/cjjs_bj_bg.jpg",
			"ui_new/createplayer/bg_wuyan.png",
			"ui_new/createplayer/cjjs_cjjs_title.png",
			"ui_new/createplayer/role_1.png",
			"ui_new/createplayer/cjjs_smd_icon.png",
			"ui_new/createplayer/g1.png",
			"ui_new/createplayer/g1b.png",
			"ui_new/createplayer/g3.png",
			"ui_new/createplayer/g3b.png",
			"ui_new/createplayer/g4.png",
			"ui_new/createplayer/g4b.png",
			"ui_new/createplayer/g2.png",
			"ui_new/createplayer/g2b.png",
			"ui_new/createplayer/bg_txt.png",
			"ui_new/common/img_role_type1.png",
			"ui_new/createplayer/cjjs_qd_btn.png",
			"ui_new/createplayer/cjjs_jsmc_icon.png",
			"ui_new/createplayer/cjjs_sj_icon.png",
			"ui_new/qiyu/family/btn_tianxie.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

