local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-LoginLayer_group_login_Game",
			UUID = "e5ebdcfb_ca22_4024_9a15_d5844207143c",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "Panel_1_Panel-LoginLayer_group_login_Game",
					UUID = "6ccb194e_b835_4b5f_bd6d_4dd0ce458029",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "18cf94d0_a3b9_4793_a5cc_d1ad750d2887",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui_new/login/img_bg.jpg",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							visible = "False",
							width = "1136",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_LoginLayer_2_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "8d109ce8_4d35_45f1_9dae_3af1858f2258",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_LoginLayer_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -130,
										PositionY = -97,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "Image_LoginLayer_1_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "c92988ff_767d_473c_b24d_0591b634a89d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_LoginLayer_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -163,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "panel_ef1_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "aeac5d53_0e0b_46e1_b9e2_31d160a78b27",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_ef1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "960",
							ZOrder = "1",
						},
						{
							controlID = "panel_ef2_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "661912ad_fa31_4ad4_9a98_13b7b7c1b2d3",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_ef2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "960",
							ZOrder = "1",
						},
						{
							controlID = "panel_ef3_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "95c85d2a_e608_4b49_bd0c_d26137e8b378",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_ef3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "960",
							ZOrder = "1",
						},
						{
							controlID = "panel_touch_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "7fc1506d_4e5f_461a_b725_7d902a51efe6",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_touch",
							sizepercentx = "100",
							sizepercenty = "100",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -88,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1136",
							ZOrder = "1",
						},
						{
							controlID = "img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "835c4d8a_6cea_4173_9b40_50ba40df86b1",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "46",
							ignoreSize = "True",
							name = "img_input_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/bg_shuru.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 490,
								PositionY = 123,
							},
							width = "476",
							ZOrder = "3",
							components = 
							{
								
								{
									controlID = "input_name_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "21a4bb89_6c1c_4389_9d5e_d39eeecfd282",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "METextField",
									ColorMixing = "#FF000000",
									CursorEnabled = "True",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontSize = "30",
									hAlignment = "0",
									height = "30",
									HitType = 
									{
										nHitType = 1,
										nXpos = -50,
										nYpos = -10,
										nHitWidth = 340,
										nHitHeight = 50
									},
									ignoreSize = "True",
									KeyBoradType = "0",
									maxLengthEnable = "True;maxLength:20",
									name = "input_name",
									passwordEnable = "False",
									placeHolder = "请输入账号！",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -130,
									},
									vAlignment = "0",
									visible = "False",
									width = "180",
									ZOrder = "9",
								},
								{
									controlID = "btn_selectAcount_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "d0f35afb_ba10_457a_aee7_c5a5adf185fb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									HitType = 
									{
										nHitType = 1,
										nXpos = -450,
										nYpos = -10,
										nHitWidth = 630,
										nHitHeight = 80
									},
									ignoreSize = "True",
									name = "btn_selectAcount",
									normal = "ui_new/login/zh_qh.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 251,
									},
									UItype = "Button",
									visible = "False",
									width = "124",
									ZOrder = "7",
								},
								{
									controlID = "lb_name_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "5e5d4e66_1bba_49d7_b697_9b72dae7bf55",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "30",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "False",
									name = "lb_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "请登录账号",
									touchAble = "True",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -130,
										PositionY = -1,
										LeftPositon = 275,
										TopPosition = 491,
										relativeToName = "Panel",
									},
									visible = "False",
									width = "300",
									ZOrder = "8",
								},
								{
									controlID = "Img_zh_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "5ca70b77_bd5f_41bc_bc59_a77397106def",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "36",
									ignoreSize = "True",
									name = "Img_zh",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/img_zh.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -175,
									},
									width = "70",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "img_account_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "ac7039b1_cf0e_4dd9_8c3b_ff2e4e4879ef",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "46",
							ignoreSize = "True",
							name = "img_account",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/bg_shuru.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 490,
								PositionY = 123,
								LeftPositon = 270,
								TopPosition = 113,
								relativeToName = "Panel",
							},
							visible = "False",
							width = "476",
							ZOrder = "3",
							components = 
							{
								
								{
									controlID = "txt_area_img_account_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "c502cd10_3ecc_454d_90d2_c763373cd28a",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "30",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "False",
									name = "txt_area",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "109区  天龙八部",
									touchAble = "True",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -128,
										LeftPositon = 275,
										TopPosition = 491,
										relativeToName = "Panel",
									},
									width = "300",
									ZOrder = "8",
								},
								{
									controlID = "btn_selectServer_img_account_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "b16c015e_2281_4c04_9b4f_5a2d3340440a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "18",
									HitType = 
									{
										nHitType = 1,
										nXpos = -477,
										nYpos = -10,
										nHitWidth = 630,
										nHitHeight = 80
									},
									ignoreSize = "True",
									name = "btn_selectServer",
									normal = "ui_new/login/zh_hq.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 250,
										PositionY = -2,
										LeftPositon = 579,
										TopPosition = 483,
										relativeToName = "Panel",
									},
									UItype = "Button",
									width = "83",
									ZOrder = "7",
								},
								{
									controlID = "Img_xq_img_account_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "f6f2875f_3d82_4e42_ad4e_74bcb66be0db",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "36",
									ignoreSize = "True",
									name = "Img_xq",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/img_xq.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -175,
									},
									width = "70",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_register_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "f1f03deb_041c_4cb8_bad4_bba2c7bce567",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "25",
							ignoreSize = "True",
							name = "btn_register",
							normal = "ui_new/login/zh_zc.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 278,
								PositionY = 62,
							},
							UItype = "Button",
							visible = "False",
							width = "60",
							ZOrder = "5",
						},
						{
							controlID = "img_dengru_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "32e0512e_b4ac_4309_9c65_77c48c7ae7c6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "32",
							ignoreSize = "True",
							name = "img_dengru",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/xf_dianji.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 54,
								LeftPositon = 254,
								TopPosition = 553,
								relativeToName = "Panel",
							},
							width = "445",
							ZOrder = "1",
						},
						{
							controlID = "img_gonggaodi_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "113528a0_8715_4e6c_85f7_bd06340442fe",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "574",
							ignoreSize = "False",
							name = "img_gonggaodi",
							scaleX = "0.9",
							scaleY = "0.9",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/xf_gonggao.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
							},
							visible = "False",
							width = "798",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_gonggao_img_gonggaodi_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "50ca33a3_f255_4b74_9d33_b74d03a6b9fb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "True",
									name = "img_gonggao",
									scaleX = "0.9",
									scaleY = "0.9",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/xf_gonggao2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 245,
									},
									visible = "False",
									width = "60",
									ZOrder = "1",
								},
								{
									controlID = "Button_Gonggao_1_img_gonggaodi_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "2775ead5_17fc_4e12_9e2a_63573696696b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "70",
									ignoreSize = "True",
									name = "Button_Gonggao_1",
									normal = "ui_new/login/xf_closeicon.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = -233,
									},
									UItype = "Button",
									width = "156",
									ZOrder = "1",
								},
								{
									controlID = "bg_title_img_gonggaodi_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "50e545b4_87a1_4a2a_8698_3aaadd05a9f1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "160",
									ignoreSize = "True",
									name = "bg_title",
									scaleX = "1.02",
									scaleY = "1.02",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_gonggao.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = 231,
									},
									width = "826",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "btn_login_Panel-LoginLayer_group_login_Game",
					UUID = "6941c1e5_d468_4a0b_a038_dc59ff7be6a0",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "54",
					ignoreSize = "True",
					name = "btn_login",
					normal = "ui_new/login/zh_jr.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 898,
						PositionY = 27,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 9
					},
					UItype = "Button",
					visible = "False",
					width = "445",
					ZOrder = "4",
				},
				{
					controlID = "panel_close_Panel-LoginLayer_group_login_Game",
					UUID = "27af0391_233e_4c94_8831_071b9c893e83",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "100",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_close",
					PanelRelativeSizeModel = 
					{
						PanelRelativeEnable = true,
					},
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					visible = "False",
					width = "960",
					ZOrder = "5",
				},
				{
					controlID = "img_title_Panel-LoginLayer_group_login_Game",
					UUID = "b7216393_2872_448a_87dc_8d409e867a95",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "145",
					ignoreSize = "True",
					name = "img_title",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/logo.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 932,
						PositionY = 634,
						RightPosition = 15,
						TopPosition = 3,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "347",
					ZOrder = "1",
				},
				{
					controlID = "img_notice_Panel-LoginLayer_group_login_Game",
					UUID = "0a910790_0cd0_4ffc_a4cb_265d81f27fbd",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "23",
					ignoreSize = "True",
					name = "img_notice",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/img_zg.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 12,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 8
					},
					width = "848",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/login/img_bg.jpg",
			"ui_new/login/bg_2.png",
			"ui_new/login/bg_1.png",
			"ui_new/login/bg_shuru.png",
			"ui_new/login/zh_qh.png",
			"ui_new/login/img_zh.png",
			"ui_new/login/zh_hq.png",
			"ui_new/login/img_xq.png",
			"ui_new/login/zh_zc.png",
			"ui_new/login/xf_dianji.png",
			"ui_new/login/xf_gonggao.png",
			"ui_new/login/xf_gonggao2.png",
			"ui_new/login/xf_closeicon.png",
			"ui_new/login/bg_gonggao.png",
			"ui_new/login/zh_jr.png",
			"ui_new/login/logo.png",
			"ui_new/login/img_zg.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

