local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-LoginNoticePage_group_login_Game",
			UUID = "6d3f74a9_774e_4d8f_b06f_b5c455199359",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "panel_ef2_Panel-LoginNoticePage_group_login_Game",
					UUID = "1b5da334_500e_4b04_bf96_9dd9b08df5d0",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_ef2",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
				},
				{
					controlID = "panel_ef3_Panel-LoginNoticePage_group_login_Game",
					UUID = "aca9dfab_edd3_45a1_9676_207e5903b4b3",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_ef3",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
				},
				{
					controlID = "Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
					UUID = "f2222625_c910_44dd_b051_ae836ae6646b",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_LoginNoticePage_1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
							UUID = "859cec6e_ebaa_4372_b23e_a46c07b1c318",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							width = "64",
							ZOrder = "3",
							components = 
							{
								
								{
									controlID = "panel_ef1_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "c7dde85c_507b_47bb_a49c_8cc514786b93",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "640",
									ignoreSize = "False",
									name = "panel_ef1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -480,
										PositionY = -320,
										relativeToName = "Panel",
										nGravity = 6,
										nAlign = 5
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "960",
									ZOrder = "1",
								},
								{
									controlID = "Image_LoginLayer_1_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "475fefb6_4540_4bf8_8c08_9fcb0e6ccdc1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_LoginLayer_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = -164,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "Image_LoginLayer_2_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "0d8c98e5_4470_4085_ae11_0db5739c5c01",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_LoginLayer_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -130,
										PositionY = -97,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "img_account_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "ec0c883d_b2c5_4f8d_8c8c_5b91e6f9b216",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "57",
									ignoreSize = "True",
									name = "img_account",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/zh_xuanqu.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -175,
										LeftPositon = 270,
										TopPosition = 113,
										relativeToName = "Panel",
									},
									width = "374",
									ZOrder = "3",
									components = 
									{
										
										{
											controlID = "txt_area_img_account_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "6c066579_7ecb_45db_8596_6430fbbfc6c7",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "False",
											name = "txt_area",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "109区  天龙八部",
											touchAble = "True",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -139,
												PositionY = 3,
												LeftPositon = 275,
												TopPosition = 491,
												relativeToName = "Panel",
											},
											width = "300",
											ZOrder = "8",
										},
										{
											controlID = "btn_selectServer_img_account_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "78c82a2d_2b4c_4c6d_836b_903b66cdb380",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "18",
											HitType = 
											{
												nHitType = 1,
												nXpos = -306,
												nYpos = -16,
												nHitWidth = 496,
												nHitHeight = 80
											},
											ignoreSize = "True",
											name = "btn_selectServer",
											normal = "ui_new/login/zh_hq.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 91,
												PositionY = 4,
												LeftPositon = 579,
												TopPosition = 483,
												relativeToName = "Panel",
											},
											UItype = "Button",
											width = "83",
											ZOrder = "7",
										},
									},
								},
								{
									controlID = "btn_register_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "38660dcd_e1dd_4d38_b6f7_6e105a5558bb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "25",
									ignoreSize = "True",
									name = "btn_register",
									normal = "ui_new/login/zh_zc.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 2,
										PositionY = -312,
									},
									UItype = "Button",
									visible = "False",
									width = "60",
									ZOrder = "5",
								},
								{
									controlID = "img_input_bg_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "1326cefe_72b0_4a32_8be2_a45b7e294883",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "66",
									ignoreSize = "True",
									name = "img_input_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/zh_zhanghao.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 1,
										PositionY = -222,
									},
									visible = "False",
									width = "880",
									ZOrder = "3",
									components = 
									{
										
										{
											controlID = "input_name_img_input_bg_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "d8589428_a8e6_4a7c_9b4f_eb4010143502",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "METextField",
											ColorMixing = "#FF000000",
											CursorEnabled = "True",
											dstBlendFunc = "771",
											fontName = "simhei",
											fontSize = "30",
											hAlignment = "0",
											height = "30",
											HitType = 
											{
												nHitType = 1,
												nXpos = -50,
												nYpos = -10,
												nHitWidth = 340,
												nHitHeight = 50
											},
											ignoreSize = "True",
											KeyBoradType = "0",
											maxLengthEnable = "True;maxLength:20",
											name = "input_name",
											passwordEnable = "False",
											placeHolder = "请输入账号！",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -196,
											},
											vAlignment = "0",
											width = "180",
											ZOrder = "9",
										},
										{
											controlID = "btn_selectAcount_img_input_bg_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "8df2c9e3_5734_41a7_81d6_09f0901dd0a7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "56",
											HitType = 
											{
												nHitType = 1,
												nXpos = -450,
												nYpos = -10,
												nHitWidth = 630,
												nHitHeight = 80
											},
											ignoreSize = "True",
											name = "btn_selectAcount",
											normal = "ui_new/login/zh_qh.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 156,
												PositionY = 3,
											},
											UItype = "Button",
											width = "124",
											ZOrder = "7",
										},
										{
											controlID = "lb_name_img_input_bg_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "a10b8d2d_5dbb_46c0_abd1_486ec29e450b",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											ColorMixing = "#FF000000",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "30",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "False",
											name = "lb_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "请登录账号",
											touchAble = "True",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -219,
												PositionY = 2,
												LeftPositon = 275,
												TopPosition = 491,
												relativeToName = "Panel",
											},
											width = "300",
											ZOrder = "8",
										},
									},
								},
								{
									controlID = "btn_login_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "f3fbaeee_c95b_4bfc_a46b_09a54d26af8c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "54",
									HitType = 
									{
										nHitType = 1,
										nXpos = -27,
										nYpos = -36,
										nHitWidth = 503,
										nHitHeight = 109
									},
									ignoreSize = "True",
									name = "btn_login",
									normal = "ui_new/login/zh_jr.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = -260,
										RightPosition = 102,
										BottomPosition = 35,
										relativeToName = "Panel",
										nGravity = 3,
										nAlign = 9
									},
									UItype = "Button",
									width = "445",
									ZOrder = "4",
								},
							},
						},
					},
				},
				{
					controlID = "btn_fanhui_Panel-LoginNoticePage_group_login_Game",
					UUID = "8a83a09d_678c_4fce_aded_45c83989d842",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "56",
					HitType = 
					{
						nHitType = 2,
						nRadius = 50,
					},
					ignoreSize = "True",
					name = "btn_fanhui",
					normal = "ui_new/common/xx_fanhui_btn.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 42,
						PositionY = 682,
						relativeToName = "Panel",
						nType = 3,
					},
					UItype = "Button",
					width = "83",
					ZOrder = "5",
				},
				{
					controlID = "panel_close_Panel-LoginNoticePage_group_login_Game",
					UUID = "c7544e92_d998_431c_ae4a_ade42b45d485",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "100",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_close",
					PanelRelativeSizeModel = 
					{
						PanelRelativeEnable = true,
					},
					sizepercentx = "85",
					sizepercenty = "100",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					visible = "False",
					width = "960",
					ZOrder = "5",
				},
				{
					controlID = "img_title_Panel-LoginNoticePage_group_login_Game",
					UUID = "b139420b_4ca2_4d8f_a5cd_42753fbe7e30",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "145",
					ignoreSize = "True",
					name = "img_title",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/logo.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 932,
						PositionY = 634,
						RightPosition = 15,
						TopPosition = 3,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "347",
					ZOrder = "4",
				},
				{
					controlID = "img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
					UUID = "3849093a_478a_4a1d_8f56_fbe25e75647d",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "442",
					ignoreSize = "True",
					name = "img_gonggaodi",
					scaleX = "0.9",
					scaleY = "0.9",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/xf_gonggao.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 465,
						TopPosition = 46,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					width = "644",
					ZOrder = "88",
					components = 
					{
						
						{
							controlID = "img_gonggao_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
							UUID = "731b567d_cef5_4672_b64b_736986ae7b5d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "30",
							ignoreSize = "True",
							name = "img_gonggao",
							scaleX = "0.9",
							scaleY = "0.9",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/xf_gonggao2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 172,
							},
							visible = "False",
							width = "60",
							ZOrder = "1",
						},
						{
							controlID = "bg_helpList_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
							UUID = "e89a8f4b_0fb8_429f_99b9_0245e56a0a8a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "390",
							ignoreSize = "False",
							name = "bg_helpList",
							opacity = "0",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 1,
							},
							width = "550",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "list_help_bg_helpList_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
									UUID = "d1c089eb_b5dc_4da1_8855_4e25fd3e004f",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "300",
									ignoreSize = "False",
									innerHeight = "300",
									innerWidth = "530",
									name = "list_help",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -265,
										PositionY = -178,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "530",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "txt_content_list_help_bg_helpList_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
											UUID = "a37627c3_d962_4870_a32f_f03d14029810",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "1",
											classname = "METextArea",
											ColorMixing = "#FF000000",
											dstBlendFunc = "771",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFFFFFFF",
												StrokeSize = 1,
											},
											hAlignment = "0",
											height = "0",
											ignoreSize = "False",
											name = "txt_content",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Hey Man~~ adadasd",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												PositionY = 380,
											},
											vAlignment = "0",
											width = "530",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "bg_title_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
							UUID = "18fc4dba_db0c_4031_b360_6fdd58d168fd",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "160",
							ignoreSize = "True",
							name = "bg_title",
							scaleX = "0.824",
							scaleY = "0.82",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/bg_gonggao.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -1,
								PositionY = 174,
							},
							width = "826",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Image_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
					UUID = "b0f23fcc_0fd3_4f1c_a1e6_46e9b237d40d",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "23",
					ignoreSize = "True",
					name = "Image_LoginNoticePage_1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/img_zg.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 12,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 8
					},
					width = "848",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/login/bg_1.png",
			"ui_new/login/bg_2.png",
			"ui_new/login/zh_xuanqu.png",
			"ui_new/login/zh_hq.png",
			"ui_new/login/zh_zc.png",
			"ui_new/login/zh_zhanghao.png",
			"ui_new/login/zh_qh.png",
			"ui_new/login/zh_jr.png",
			"ui_new/common/xx_fanhui_btn.png",
			"ui_new/login/logo.png",
			"ui_new/login/xf_gonggao.png",
			"ui_new/login/xf_gonggao2.png",
			"ui_new/login/bg_gonggao.png",
			"ui_new/login/img_zg.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

