local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-ServerChoice_group_login_Game",
			UUID = "9955b8bd_063a_4f32_b8eb_88a2b165c607",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "bg_Panel-ServerChoice_group_login_Game",
					UUID = "c9f516f5_dae9_433e_9ab8_da6a5af8ea16",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "582",
					ignoreSize = "True",
					name = "bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/xf_di.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 475,
						PositionY = 310,
					},
					width = "885",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "img_bg_bg_Panel-ServerChoice_group_login_Game",
							UUID = "7f2434a9_54c9_40cb_91e3_c9edce820c0c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "img_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/xf_fuwuqi.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -2,
								PositionY = 11,
							},
							visible = "False",
							width = "64",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "panel_zone_Panel-ServerChoice_group_login_Game",
					UUID = "459fca26_afb0_4f8b_923e_20398af2ee64",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "550",
					ignoreSize = "False",
					name = "panel_zone",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 50,
						PositionY = 43,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					visible = "False",
					width = "160",
					ZOrder = "1",
				},
				{
					controlID = "laye_Scroll_Panel-ServerChoice_group_login_Game",
					UUID = "8d9c6d10_6724_4ea1_a71f_b1598191f64c",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "150",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "338",
					ignoreSize = "False",
					name = "laye_Scroll",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 115,
						PositionY = 92,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "722",
					ZOrder = "3",
					components = 
					{
						
						{
							controlID = "panel_1_laye_Scroll_Panel-ServerChoice_group_login_Game",
							UUID = "216e0a5a_2637_4df3_8c47_217ffa5f37ed",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "82",
							ignoreSize = "False",
							name = "panel_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "350",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "btn_Choice_panel_1_laye_Scroll_Panel-ServerChoice_group_login_Game",
									UUID = "150d7892_0a97_4234_b49f_5a0da0e92c23",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									disabled = "ui_new/login/xf_fuwuqidi2.png",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "70",
									ignoreSize = "True",
									name = "btn_Choice",
									normal = "ui_new/login/xf_fuwuqidi.png",
									pressed = "ui_new/login/xf_fuwuqidi2.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										
									},
									UItype = "Button",
									width = "332",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "txt_2_btn_Choice_panel_1_laye_Scroll_Panel-ServerChoice_group_login_Game",
											UUID = "dd44c1b6_1dc8_4bb4_88f5_baa07eb690ac",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											ColorMixing = "#FF3A3A3A",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "26",
											ignoreSize = "True",
											name = "txt_2",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "S122真江湖122区",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 19,
												PositionY = 35,
											},
											width = "166",
											ZOrder = "1",
										},
										{
											controlID = "txt_3_btn_Choice_panel_1_laye_Scroll_Panel-ServerChoice_group_login_Game",
											UUID = "ba4f756f_a888_4422_aa9d_5bddd8d53260",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											ColorMixing = "#FFFF5400",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "26",
											ignoreSize = "True",
											name = "txt_3",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "（Lv123）",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 264,
												PositionY = 35,
											},
											width = "91",
											ZOrder = "1",
										},
										{
											controlID = "img_baov_btn_Choice_panel_1_laye_Scroll_Panel-ServerChoice_group_login_Game",
											UUID = "645ce971_2ce3_4c39_bb2f_78852017ee93",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "True",
											name = "img_baov",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/login/xf_bao.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 309,
												PositionY = 55,
											},
											width = "48",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "img_di1_panel_1_laye_Scroll_Panel-ServerChoice_group_login_Game",
									UUID = "e55923df_f007_4394_b19f_75fd5020cb1c",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "70",
									ignoreSize = "True",
									name = "img_di1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/xf_fuwuqidi.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "332",
									ZOrder = "1",
								},
								{
									controlID = "img_di2_panel_1_laye_Scroll_Panel-ServerChoice_group_login_Game",
									UUID = "ac45005f_e800_4940_9224_ae49e6781612",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "70",
									ignoreSize = "True",
									name = "img_di2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/xf_fuwuqidi2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "332",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "laye_zuijin_Panel-ServerChoice_group_login_Game",
					UUID = "dc8124c0_b07a_4394_8b29_ee1751a01e57",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "150",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "60",
					ignoreSize = "False",
					name = "laye_zuijin",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 122,
						PositionY = 461,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "706",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "btn_tab_laye_zuijin_Panel-ServerChoice_group_login_Game",
							UUID = "59c88b1d_d331_4b46_856e_eb7402e8ded0",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "50",
							ignoreSize = "True",
							name = "btn_tab",
							normal = "ui_new/login/tab_1.png",
							pressed = "ui_new/login/tab_2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = 24,
							},
							UItype = "Button",
							width = "163",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_1_btn_tab_laye_zuijin_Panel-ServerChoice_group_login_Game",
									UUID = "a25fc135_61be_43f6_ae46_d2c32165b6a3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF3A3A3A",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "29",
									ignoreSize = "True",
									name = "txt_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "最近登陆",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 81,
										PositionY = -4,
									},
									width = "91",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "img_di_Panel-ServerChoice_group_login_Game",
					UUID = "2be2bbb8_c571_479d_a194_a9e3928a0d87",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "157",
					ignoreSize = "True",
					name = "img_di",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/img_zs.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 929,
						PositionY = 575,
					},
					width = "27",
					ZOrder = "1",
				},
				{
					controlID = "btn_close_Panel-ServerChoice_group_login_Game",
					UUID = "011c4823_dd6e_4384_b3c7_a03e1ba354b1",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "65",
					HitType = 
					{
						nHitType = 2,
						nRadius = 50,
					},
					ignoreSize = "True",
					name = "btn_close",
					normal = "ui_new/common/common_close_icon.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 930,
						PositionY = 598,
					},
					UItype = "Button",
					width = "65",
					ZOrder = "3",
				},
				{
					controlID = "btn_zone_Panel-ServerChoice_group_login_Game",
					UUID = "c4c1b092_de1e_446c_b847_fe7923171011",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "25",
					ignoreSize = "True",
					name = "btn_zone",
					normal = "ui_new/login/xf_tab1.png",
					pressed = "ui_new/login/xf_tab2.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 134,
						PositionY = 541,
					},
					UItype = "Button",
					visible = "False",
					width = "60",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "lbl_name_btn_zone_Panel-ServerChoice_group_login_Game",
							UUID = "00ef9c59_4e5a_44ea_86aa_6d2581037878",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							ColorMixing = "#00FFFFFF",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF3D3D3D",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "26",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "34",
							ignoreSize = "True",
							name = "lbl_name",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "五区",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 2,
								PositionY = 3,
							},
							width = "54",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "img_jianbain1_Panel-ServerChoice_group_login_Game",
					UUID = "8388db1a_aaba_428a_bdf2_9c5befb7b184",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "60",
					ignoreSize = "True",
					name = "img_jianbain1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/img_jianbian.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 135,
						PositionY = 490,
					},
					width = "38",
					ZOrder = "1",
				},
				{
					controlID = "img_jianbain2_Panel-ServerChoice_group_login_Game",
					UUID = "70e8e590_4e3d_45f8_ae1e_1850aead6fc7",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					flipX = "True",
					height = "60",
					ignoreSize = "True",
					name = "img_jianbain2",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/img_jianbian.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 815,
						PositionY = 490,
					},
					width = "38",
					ZOrder = "1",
				},
				{
					controlID = "img_xian_Panel-ServerChoice_group_login_Game",
					UUID = "080b2bde_d00c_4385_91b5_3c8cd14b1df0",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "3",
					ignoreSize = "True",
					name = "img_xian",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/img_xian.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 474,
						PositionY = 459,
					},
					width = "759",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/login/xf_di.png",
			"ui_new/login/xf_fuwuqi.png",
			"ui_new/login/xf_fuwuqidi2.png",
			"ui_new/login/xf_fuwuqidi.png",
			"ui_new/login/xf_bao.png",
			"ui_new/login/tab_2.png",
			"ui_new/login/tab_1.png",
			"ui_new/login/img_zs.png",
			"ui_new/common/common_close_icon.png",
			"ui_new/login/xf_tab2.png",
			"ui_new/login/xf_tab1.png",
			"ui_new/login/img_jianbian.png",
			"ui_new/login/img_xian.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

