local mapArray = MEMapArray:new()
mapArray:push({ id = 101, level = 15, name = "Mở ra:Trang bị cường hóa", pic = "0", des = "Trang bị cường hóa", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 102, level = 29, name = "Mở ra:Trang bị thăng tinh", pic = "0", des = "Trang bị thăng tinh", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 103, level = 40, name = "Mở ra:Trang bị tinh luyện", pic = "0", des = "Trang bị tinh luyện", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 104, level = 24, name = "Mở ra:Bảo thạch khảm nạm", pic = "0", des = "Bảo thạch khảm nạm", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 105, level = 24, name = "Mở ra:Bảo thạch hợp thành", pic = "0", des = "Bảo thạch hợp thành", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 106, level = 8, name = "Mở ra:Thương thành", pic = "0", des = "Thương thành", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 107, level = 45, name = "Mở ra:Trang bị tẩy luyện", pic = "0", des = "Trang bị tẩy luyện", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 108, level = 55, name = "Mở ra:Trang bị đúc lại", pic = "0", des = "Trang bị đúc lại", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 201, level = 1, name = "Mở ra:Kỹ năng thăng cấp", pic = "0", des = "Kỹ năng thăng cấp", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 202, level = 20, name = "Mở ra:Nhân vật kinh mạch", pic = "0", des = "Nhân vật kinh mạch", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 203, level = 1, name = "Mở ra:Nhân vật tu luyện", pic = "0", des = "Nhân vật tu luyện", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 204, level = 1, name = "Mở ra:Nhân vật truyền công", pic = "0", des = "Nhân vật truyền công", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 205, level = 1, name = "Mở ra:Võ học thăng giai", pic = "0", des = "Võ học thăng giai", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 301, level = 12, name = "Mở ra:Quần hào phổ", pic = "0", des = "Quần hào phổ", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 401, level = 20, name = "Mở ra:Vô Lượng Sơn", pic = "0", des = "Vô Lượng Sơn", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 501, level = 25, name = "Mở ra:Nhạn Môn Quan", pic = "0", des = "Nhạn Môn Quan", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 601, level = 28, name = "Mở ra:Ma ha nhai", pic = "0", des = "Ma ha nhai", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 701, level = 1, name = "Mở ra:Trận vị 1", pic = "0", des = "Trận vị 1", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 702, level = 1, name = "Mở ra:Trận vị 2", pic = "0", des = "Trận vị 2", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 703, level = 1, name = "Mở ra:Trận vị 3", pic = "0", des = "Trận vị 3", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 704, level = 5, name = "Mở ra:Trận vị 4", pic = "0", des = "Trận vị 4", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 705, level = 10, name = "Mở ra:Trận vị 5", pic = "0", des = "Trận vị 5", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 800, level = 15, name = "Thanh trang bị ẩn tàng", pic = "0", des = "Thanh trang bị", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 801, level = 15, name = "Mở ra:Trang bị vị 1", pic = "0", des = "Trang bị vị 1", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 802, level = 16, name = "Mở ra:Trang bị vị 2", pic = "0", des = "Trang bị vị 2", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 803, level = 18, name = "Mở ra:Trang bị vị 3", pic = "0", des = "Trang bị vị 3", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 804, level = 17, name = "Mở ra:Trang bị vị 4", pic = "0", des = "Trang bị vị 4", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 805, level = 19, name = "Mở ra:Trang bị vị 5", pic = "0", des = "Trang bị vị 5", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 901, level = 7, name = "Mở ra:Ngự Thiện Phòng", pic = "0", des = "Ngự Thiện Phòng", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 902, level = 52, name = "Mở ra:Mời mã", pic = "0", des = "Mời mã", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 903, level = 13, name = "Mở ra:Long Môn Tiêu Cục", pic = "0", des = "Long Môn Tiêu Cục", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 904, level = 11, name = "Mở ra:Hộ giá", pic = "0", des = "Hộ giá", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 905, level = 7, name = "Mở ra:Đánh dấu", pic = "0", des = "Đánh dấu", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 906, level = 1, name = "Mở ra:Thiên Miêu Carnival", pic = "0", des = "Thiên Miêu Carnival", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 907, level = 999, name = "Mở ra:Đổ thạch", pic = "0", des = "Đổ thạch", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 1001, level = 6, name = "Mở ra:Nhiệm vụ hàng ngày", pic = "0", des = "Nhiệm vụ hàng ngày", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 1101, level = 30, name = "Mở ra:Phục ma lục", pic = "0", des = "Phục ma lục", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 1102, level = 9, name = "Mở ra:Hảo hữu", pic = "0", des = "Hảo hữu", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 1201, level = 25, name = "Mở ra:Bang phái", pic = "0", des = "Bang phái", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 1202, level = 35, name = "Mở ra:Võ Lâm Đại Hội", pic = "0", des = "Võ Lâm Đại Hội", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 1203, level = 27, name = "Mở ra:Trợ chiến", pic = "0", des = "Trợ chiến", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 1204, level = 43, name = "Mở ra : Phù hợp", pic = "0", des = "Phù hợp", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 1205, level = 28, name = "Mở ra : Sáng tạo Bang phái", pic = "0", des = "Sáng Tạo Bang phái", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2001, level = 15, name = "Mở ra:Tông sư quan", pic = "0", des = "Tông sư quan", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2101, level = 53, name = "Mở ra:Đào khoáng", pic = "0", des = "Đào khoáng", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2102, level = 34, name = "Mở ra:Lính đánh thuê", pic = "0", des = "Lính đánh thuê", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2201, level = 22, name = "Mở ra:Quy ẩn", pic = "0", des = "Quy ẩn", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2202, level = 36, name = "Mở ra:Cầu nguyện", pic = "0", des = "Cầu nguyện", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2203, level = 65, name = "Mở ra:Du lịch", pic = "0", des = "Du lịch", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2204, level = 35, name = "Mở ra:Thay tranng phục nhanh", pic = "0", des = "Thay tranng phục nhanh", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2205, level = 80, name = "Mở ra:Luyện thể", pic = "0", des = "Luyện thể", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2206, level = 48, name = "Mở ra:Tiềm tu", pic = "0", des = "Tiềm tu", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2207, level = 23, name = "Mở ra:Chiến lực khảo giáo", pic = "0", des = "Chiến lực khảo giáo", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2208, level = 25, name = "Mở ra:Long Môn phá", pic = "0", des = "Long Môn phá", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2209, level = 26, name = "Mở ra:Kỹ năng sách lược", pic = "0", des = "Kỹ năng sách lược", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2210, level = 70, name = "Mở ra:Luận kiếm trèo núi", pic = "0", des = "Luận kiếm trèo núi", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2211, level = 85, name = "Mở ra:Trang bị thăng giai", pic = "0", des = "Trang bị thăng giai", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2212, level = 47, name = "Mở ra:Vô lượng ác mộng", pic = "0", des = "Vô lượng ác mộng", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2213, level = 70, name = "Mở ra:Trận pháp", pic = "0", des = "Trận pháp", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2214, level = 70, name = "Mở ra:Xông trận", pic = "0", des = "Xông trận", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2215, level = 25, name = "Mở ra:Tầm bảo", pic = "0", des = "Tầm bảo", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2216, level = 25, name = "Mở ra:Thiên cơ vòng", pic = "0", des = "Thiên cơ vòng", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2217, level = 25, name = "Mở ra:Nện trứng", pic = "0", des = "Nện trứng", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2218, level = 35, name = "Mở ra:Lãng Nhân võ sĩ", pic = "0", des = "Lãng Nhân võ sĩ", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2219, level = 46, name = "Mở ra:Đông Doanh đảo", pic = "0", des = "Đông Doanh đảo", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2220, level = 36, name = "Mở ra:Danh nhân đường", pic = "0", des = "Danh nhân đường", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2221, level = 0, name = "Mở ra:Khinh công đoạt bảo", pic = "0", des = "Khinh công đoạt bảo", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2222, level = 75, name = "Mở ra:Thiên Thư nghiên tu", pic = "0", des = "Thiên Thư nghiên tu", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2223, level = 82, name = "Mở ra:Thiên Thư lĩnh hội", pic = "0", des = "Thiên Thư lĩnh hội", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2224, level = 65, name = "Mở ra:Thiên Thư đổi thành", pic = "0", des = "Thiên Thư đổi thành", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2225, level = 40, name = "Mở ra:Vương giả lôi đài", pic = "0", des = "Vương giả lôi đài", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2226, level = 62, name = "Mở ra:pet", pic = "0", des = "pet", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2227, level = 49, name = "Mở ra:Thiên Giai tranh bá", pic = "0", des = "Thiên Giai tranh bá", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2228, level = 44, name = "Mở ra:Bảo Tiêu thiên hạ", pic = "0", des = "Bảo Tiêu thiên hạ", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2229, level = 48, name = "Mở ra:Võ lâm công địch", pic = "0", des = "Võ lâm công địch", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2230, level = 78, name = "Mở ra:Thiên Thư chú giải", pic = "0", des = "Thiên Thư chú giải", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2231, level = 68, name = "Mở ra:Tâm pháp", pic = "0", des = "Tâm pháp", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2232, level = 60, name = "Mở ra:Anh hùng đại hội", pic = "0", des = "Anh hùng đại hội", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2233, level = 82, name = "Mở ra:Thiên mệnh", pic = "0", des = "Thiên mệnh", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 909, level = 82, name = "Mở ra:Tế Tự", pic = "0", des = "Tế Tự", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 908, level = 1, name = "Mở ra:Nhân vật xem xét", pic = "0", des = "Nhân vật xem xét", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2234, level = 60, name = "Mở ra:Anh Hùng Chí", pic = "0", des = "Anh Hùng Chí", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2235, level = 62, name = "Mở ra:pet Thuần ngự", pic = "0", des = "pet Thuần ngự", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2236, level = 50, name = "Mở ra:Phong Vân ghi chép", pic = "0", des = "Phong Vân ghi chép", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 910, level = 51, name = "Mở ra:Giang hồ nhã tập", pic = "0", des = "Giang hồ nhã tập", unlockBtn = 0, process = "0", notice = "0"})
mapArray:push({ id = 2237, level = 88, name = "Mở ra:Thiên mệnh Thăng tinh", pic = "0", des = "Thiên mệnh Thăng tinh", unlockBtn = 0, process = "0", notice = "0"})
return mapArray
