local mapArray = MEMapArray:new()
mapArray:push({ id = 1, attribute = "3_7700|5_7700", immune_rate = "", effect_active = "", effect_passive = "", name = "2 trợ chiến+1", power = 0, des = "thân pháp+7700 Phòng ngự+7700"})
mapArray:push({ id = 2, attribute = "2_7700|4_7700", immune_rate = "", effect_active = "", effect_passive = "", name = "3 trợ chiến+2", power = 0, des = "võ lực+7700 Nội lực+7700"})
mapArray:push({ id = 3, attribute = "1_11600", immune_rate = "", effect_active = "", effect_passive = "", name = "4 trợ chiến+3", power = 0, des = "khí huyết+11600"})
mapArray:push({ id = 4, attribute = "18_6000", immune_rate = "", effect_active = "", effect_passive = "", name = "5 trợ chiến+4", power = 0, des = "khí huyết+60%"})
mapArray:push({ id = 5, attribute = "19_4000|21_4000", immune_rate = "", effect_active = "", effect_passive = "", name = "6 trợ chiến+5", power = 0, des = "võ lực+40% Nội lực+40%"})
mapArray:push({ id = 6, attribute = "", immune_rate = "", effect_active = "", effect_passive = "45_500", name = "6 trợ chiến+6", power = 5000, des = "nhận trị liệu lượng+5%"})
mapArray:push({ id = 7, attribute = "", immune_rate = "", effect_active = "", effect_passive = "44_-800", name = "6 trợ chiến+7", power = 8000, des = "nhận tổn thương-8%"})
mapArray:push({ id = 8, attribute = "", immune_rate = "", effect_active = "44_1000", effect_passive = "", name = "6 trợ chiến+8", power = 10000, des = "tổn thương+10%"})
mapArray:push({ id = 9, attribute = "15_9000", immune_rate = "", effect_active = "", effect_passive = "", name = "6 trợ chiến+9", power = 0, des = "né tránh+9000"})
mapArray:push({ id = 10, attribute = "18_2000|20_2000", immune_rate = "", effect_active = "", effect_passive = "", name = "6 trợ chiến+10", power = 0, des = "khí huyết+20% Phòng ngự+20%"})
mapArray:push({ id = 11, attribute = "16_1000", immune_rate = "", effect_active = "", effect_passive = "", name = "6 trợ chiến+11", power = 0, des = "bạo kích+10%"})
mapArray:push({ id = 12, attribute = "", immune_rate = "", effect_active = "44_1200", effect_passive = "", name = "6 trợ chiến+12", power = 20000, des = "tổn thương+12%"})
return mapArray
