local mapArray = MEMapArray:new()
mapArray:push({ id = 1, rank = 1, attribute = 1000})
mapArray:push({ id = 2, rank = 2, attribute = 900})
mapArray:push({ id = 3, rank = 3, attribute = 800})
mapArray:push({ id = 4, rank = 4, attribute = 700})
mapArray:push({ id = 5, rank = 5, attribute = 600})
mapArray:push({ id = 6, rank = 6, attribute = 500})
mapArray:push({ id = 7, rank = 7, attribute = 400})
mapArray:push({ id = 8, rank = 8, attribute = 300})
mapArray:push({ id = 9, rank = 9, attribute = 200})
mapArray:push({ id = 10, rank = 10, attribute = 100})
return mapArray
