local mapArray = MEMapArray:new()
mapArray:push({ id = 1, answer = "A", des = "Lệnh Hồ Xung"})
mapArray:push({ id = 2, answer = "B", des = "Quách Tĩnh"})
mapArray:push({ id = 3, answer = "C", des = "Kiều Phong"})
mapArray:push({ id = 4, answer = "A", des = "Phong Lăng Sư Thái"})
mapArray:push({ id = 5, answer = "B", des = "Diệt Tuyệt Sư Thái"})
mapArray:push({ id = 6, answer = "C", des = "Chu Chỉ Nhược"})
mapArray:push({ id = 7, answer = "A", des = "Triệu Chí Kính"})
mapArray:push({ id = 8, answer = "B", des = "Doãn Chí Bình"})
mapArray:push({ id = 9, answer = "C", des = "Lý Chí Thường"})
mapArray:push({ id = 10, answer = "A", des = "Bảy tên"})
mapArray:push({ id = 11, answer = "B", des = "Sáu tên"})
mapArray:push({ id = 12, answer = "C", des = "Bốn tên"})
mapArray:push({ id = 13, answer = "A", des = "Trường Xuân Tử"})
mapArray:push({ id = 14, answer = "B", des = "Ngọc Dương Tử"})
mapArray:push({ id = 15, answer = "C", des = "Quảng Ninh Tử"})
mapArray:push({ id = 16, answer = "A", des = "Thứ năm"})
mapArray:push({ id = 17, answer = "B", des = "Thứ tư"})
mapArray:push({ id = 18, answer = "C", des = "Thứ ba"})
mapArray:push({ id = 19, answer = "A", des = "Thất Tâm hải đường"})
mapArray:push({ id = 20, answer = "B", des = "Hạc Đỉnh Hồng"})
mapArray:push({ id = 21, answer = "C", des = "Kim Tằm Cổ"})
mapArray:push({ id = 22, answer = "A", des = "Viên Chân"})
mapArray:push({ id = 23, answer = "B", des = "Huyền Từ"})
mapArray:push({ id = 24, answer = "C", des = "Hối Thông"})
mapArray:push({ id = 25, answer = "A", des = "Cà sa"})
mapArray:push({ id = 26, answer = "B", des = "Họa quyển"})
mapArray:push({ id = 27, answer = "C", des = "Một quyển sách"})
mapArray:push({ id = 28, answer = "A", des = "Phùng Hành"})
mapArray:push({ id = 29, answer = "B", des = "Trình Dao Già"})
mapArray:push({ id = 30, answer = "C", des = "Hoa Tranh"})
mapArray:push({ id = 31, answer = "B", des = "Sa Thông Thiên"})
mapArray:push({ id = 32, answer = "C", des = "Bành Liên Hổ"})
mapArray:push({ id = 33, answer = "A", des = "Lương Tử Ông"})
mapArray:push({ id = 34, answer = "B", des = "La Nhân Kiệt"})
mapArray:push({ id = 35, answer = "C", des = "Dư Nhân Ngạn"})
mapArray:push({ id = 36, answer = "A", des = "Hạ Nhân Long"})
mapArray:push({ id = 37, answer = "B", des = "Ảm Nhiên Tiêu Hồn Chưởng"})
mapArray:push({ id = 38, answer = "C", des = "Không Minh Quyền"})
mapArray:push({ id = 39, answer = "A", des = "Hàn Băng chưởng"})
mapArray:push({ id = 40, answer = "B", des = "Mai Nhược hoa"})
mapArray:push({ id = 41, answer = "C", des = "Mai giáng tuyết"})
mapArray:push({ id = 42, answer = "A", des = "Mai Phương Cô"})
mapArray:push({ id = 43, answer = "B", des = "Đoàn Duyên Khánh"})
mapArray:push({ id = 44, answer = "C", des = "Đoàn Chính Thuần"})
mapArray:push({ id = 45, answer = "A", des = "Đoạn Chính Minh"})
mapArray:push({ id = 46, answer = "B", des = "Tuyệt Tình Cốc"})
mapArray:push({ id = 47, answer = "C", des = "Cổ mộ"})
mapArray:push({ id = 48, answer = "A", des = "Hoàng cung"})
mapArray:push({ id = 49, answer = "B", des = "Thiên Hạ Vô Cẩu"})
mapArray:push({ id = 50, answer = "C", des = "Ngao khẩu đoạt trượng"})
mapArray:push({ id = 51, answer = "A", des = "Bổng đả song khuyển"})
mapArray:push({ id = 52, answer = "B", des = "Lớn lao"})
mapArray:push({ id = 53, answer = "C", des = "Định Nhàn Sư Thái"})
mapArray:push({ id = 54, answer = "A", des = "Thiên môn đạo nhân"})
mapArray:push({ id = 55, answer = "B", des = "Vương Trùng Dương"})
mapArray:push({ id = 56, answer = "C", des = "Âu Dương Phong"})
mapArray:push({ id = 57, answer = "A", des = "Hồng Thất Công"})
mapArray:push({ id = 58, answer = "B", des = "Tây Cuồng"})
mapArray:push({ id = 59, answer = "C", des = "Bắc Hiệp"})
mapArray:push({ id = 60, answer = "A", des = "Nam tăng"})
mapArray:push({ id = 61, answer = "C", des = "Hàn Băng Chân Khí"})
mapArray:push({ id = 62, answer = "B", des = "Tử Hà Thần Công"})
mapArray:push({ id = 63, answer = "A", des = "Tiêu Tương Dạ Vũ"})
mapArray:push({ id = 64, answer = "C", des = "Vũ Mục Di Thư"})
mapArray:push({ id = 65, answer = "B", des = "Cửu Âm Chân Kinh"})
mapArray:push({ id = 66, answer = "A", des = "Hàng Long Thập Bát Chưởng"})
mapArray:push({ id = 67, answer = "C", des = "Cửu Âm Chân Kinh"})
mapArray:push({ id = 68, answer = "B", des = "Cửu Dương Thần Công"})
mapArray:push({ id = 69, answer = "A", des = "Độc Cô Cửu Kiếm"})
mapArray:push({ id = 70, answer = "C", des = "Vương Trùng Dương"})
mapArray:push({ id = 71, answer = "B", des = "Hoàng Dung"})
mapArray:push({ id = 72, answer = "A", des = "Hồng Thất Công"})
mapArray:push({ id = 73, answer = "C", des = "Càn Khôn Đại Na Di"})
mapArray:push({ id = 74, answer = "B", des = "Cửu Dương Thần Công"})
mapArray:push({ id = 75, answer = "A", des = "Thánh Hỏa Lệnh võ công"})
mapArray:push({ id = 76, answer = "C", des = "Hồ Thanh Ngưu"})
mapArray:push({ id = 77, answer = "B", des = "Vương Nan Cô"})
mapArray:push({ id = 78, answer = "A", des = "Kỷ Hiểu Phù"})
mapArray:push({ id = 79, answer = "C", des = "Tổ Thiên Thu"})
mapArray:push({ id = 80, answer = "B", des = "Lam Phượng Hoàng"})
mapArray:push({ id = 81, answer = "A", des = "Kế Vô Thi"})
mapArray:push({ id = 82, answer = "C", des = "Cuồng Phong Khoái Kiếm"})
mapArray:push({ id = 83, answer = "B", des = "Thương Dương Kiếm"})
mapArray:push({ id = 84, answer = "A", des = "Thiếu Thương Kiếm"})
mapArray:push({ id = 85, answer = "C", des = "Tịch dương tây hạ"})
mapArray:push({ id = 86, answer = "B", des = "Dương Ca Thiên Quân"})
mapArray:push({ id = 87, answer = "A", des = "Dương Xuân Bạch Tuyết"})
mapArray:push({ id = 88, answer = "C", des = "Long phi phượng vũ"})
mapArray:push({ id = 89, answer = "B", des = "Song Long Thủ Thủy"})
mapArray:push({ id = 90, answer = "A", des = "Lý Sương Băng Chí"})
mapArray:push({ id = 91, answer = "A", des = "Chu Cửu Chân"})
mapArray:push({ id = 92, answer = "B", des = "Chu Chỉ Nhược"})
mapArray:push({ id = 93, answer = "C", des = "Triệu Mẫn"})
mapArray:push({ id = 94, answer = "A", des = "Trường không xạ nhạn"})
mapArray:push({ id = 95, answer = "B", des = "Thiên Địa Đồng Thọ"})
mapArray:push({ id = 96, answer = "C", des = "Ngọc toái côn cương"})
mapArray:push({ id = 97, answer = "A", des = "Hoa Thiết Kiền"})
mapArray:push({ id = 98, answer = "B", des = "Hoa Vô Khuyết"})
mapArray:push({ id = 99, answer = "C", des = "Hoa tàng hoa"})
mapArray:push({ id = 100, answer = "A", des = "Khúc Linh Phong"})
mapArray:push({ id = 101, answer = "B", des = "Lão ngoan đồng"})
mapArray:push({ id = 102, answer = "C", des = "Hoàng Dược Sư"})
mapArray:push({ id = 103, answer = "A", des = "Lăng Sương Hoa"})
mapArray:push({ id = 104, answer = "B", des = "Thủy Sanh"})
mapArray:push({ id = 105, answer = "C", des = "Thích Phương"})
mapArray:push({ id = 106, answer = "A", des = "Phi Thiên Biên Bức"})
mapArray:push({ id = 107, answer = "B", des = "Phi Thiên thần long"})
mapArray:push({ id = 108, answer = "C", des = "Phi Thiên tiểu nữ"})
mapArray:push({ id = 109, answer = "A", des = "Mộ Dung Long Thành"})
mapArray:push({ id = 110, answer = "B", des = "Mộ Dung Bác"})
mapArray:push({ id = 111, answer = "C", des = "Mộ Dung Phục"})
mapArray:push({ id = 112, answer = "A", des = "Đông Phương Bất Bại"})
mapArray:push({ id = 113, answer = "B", des = "Phong Thanh Dương"})
mapArray:push({ id = 114, answer = "C", des = "Phương Chứng đại sư"})
mapArray:push({ id = 115, answer = "A", des = "Khúc Phi Yên"})
mapArray:push({ id = 116, answer = "B", des = "Nghi Lâm"})
mapArray:push({ id = 117, answer = "C", des = "Nhạc Linh San"})
mapArray:push({ id = 118, answer = "A", des = "Thiên Vương lão tử"})
mapArray:push({ id = 119, answer = "B", des = "Lục Chỉ Cầm Ma"})
mapArray:push({ id = 120, answer = "C", des = "Nhất kiếm vô huyết"})
mapArray:push({ id = 121, answer = "B", des = "Hóa Công Đại Pháp"})
mapArray:push({ id = 122, answer = "C", des = "Bắc Minh Thần Công"})
mapArray:push({ id = 123, answer = "A", des = "Tiểu Vô Tướng Công"})
mapArray:push({ id = 124, answer = "B", des = "Khách ti lệ"})
mapArray:push({ id = 125, answer = "C", des = "Hoắc Thanh Đồng"})
mapArray:push({ id = 126, answer = "A", des = "Quan minh mai"})
mapArray:push({ id = 127, answer = "B", des = "Ân Tố Tố"})
mapArray:push({ id = 128, answer = "C", des = "Thành Côn"})
mapArray:push({ id = 129, answer = "A", des = "Kim Hoa Bà Bà"})
mapArray:push({ id = 130, answer = "B", des = "Hoa sơn trà"})
mapArray:push({ id = 131, answer = "C", des = "Tình Hoa"})
mapArray:push({ id = 132, answer = "A", des = "Long Nữ hoa"})
mapArray:push({ id = 133, answer = "B", des = "Mộc Kiếm Bình"})
mapArray:push({ id = 134, answer = "C", des = "Mộc Anh"})
mapArray:push({ id = 135, answer = "A", des = "Mộc kiếm sinh"})
mapArray:push({ id = 136, answer = "B", des = "Vạn Lý Độc Hành"})
mapArray:push({ id = 137, answer = "C", des = "Mã Vương Thần"})
mapArray:push({ id = 138, answer = "A", des = "Diệu thủ thư sinh"})
mapArray:push({ id = 139, answer = "B", des = "Bi Tô Thanh Phong"})
mapArray:push({ id = 140, answer = "C", des = "Mông hãn dược"})
mapArray:push({ id = 141, answer = "A", des = "Hóa thi phấn"})
mapArray:push({ id = 142, answer = "B", des = "Nhất Dương Chỉ"})
mapArray:push({ id = 143, answer = "C", des = "Lục Mạch Thần Kiếm"})
mapArray:push({ id = 144, answer = "A", des = "Thiên Sơn Chiết Mai Thủ"})
mapArray:push({ id = 145, answer = "B", des = "Kim Diện Phật"})
mapArray:push({ id = 146, answer = "C", des = "Thiên thủ nhân đồ"})
mapArray:push({ id = 147, answer = "A", des = "Tham tiên lão quái"})
mapArray:push({ id = 148, answer = "B", des = "Không tâm thái"})
mapArray:push({ id = 149, answer = "C", des = "Quyển tâm thái"})
mapArray:push({ id = 150, answer = "A", des = "Sinh thái"})
mapArray:push({ id = 151, answer = "C", des = "Thiết tác hoành giang"})
mapArray:push({ id = 152, answer = "B", des = "Ngũ Vân Thủ"})
mapArray:push({ id = 153, answer = "A", des = "Lục địa thần long"})
mapArray:push({ id = 154, answer = "C", des = "Thôi bách tuyền"})
mapArray:push({ id = 155, answer = "B", des = "Bao Bất Đồng"})
mapArray:push({ id = 156, answer = "A", des = "Công Dã Kiền"})
mapArray:push({ id = 157, answer = "C", des = "Ô Lão Đại"})
mapArray:push({ id = 158, answer = "B", des = "Bất Bình đạo nhân"})
mapArray:push({ id = 159, answer = "A", des = "Tang thổ công"})
mapArray:push({ id = 160, answer = "C", des = "Thái Tổ Trường Quyền"})
mapArray:push({ id = 161, answer = "B", des = "Cầm Long Công"})
mapArray:push({ id = 162, answer = "A", des = "Hàng Long Thập Bát Chưởng"})
mapArray:push({ id = 163, answer = "C", des = "Đại Luân Minh Vương"})
mapArray:push({ id = 164, answer = "B", des = "Mộ Dung Phục"})
mapArray:push({ id = 165, answer = "A", des = "Đinh Xuân Thu"})
mapArray:push({ id = 166, answer = "C", des = "Hoa Tranh"})
mapArray:push({ id = 167, answer = "B", des = "Mục Niệm Từ"})
mapArray:push({ id = 168, answer = "A", des = "Trình Dao Già"})
mapArray:push({ id = 169, answer = "C", des = "Kim Đao Phò Mã"})
mapArray:push({ id = 170, answer = "B", des = "Quách đại hiệp"})
mapArray:push({ id = 171, answer = "A", des = "Bắc Hiệp"})
mapArray:push({ id = 172, answer = "C", des = "Quách Tĩnh"})
mapArray:push({ id = 173, answer = "B", des = "Tiểu Long Nữ"})
mapArray:push({ id = 174, answer = "A", des = "Dương Khang"})
mapArray:push({ id = 175, answer = "C", des = "Bạch Long môn"})
mapArray:push({ id = 176, answer = "B", des = "Xích Long môn"})
mapArray:push({ id = 177, answer = "A", des = "Thanh Long môn"})
mapArray:push({ id = 178, answer = "C", des = "Thủy Sanh"})
mapArray:push({ id = 179, answer = "B", des = "Thích Phương"})
mapArray:push({ id = 180, answer = "A", des = "Màu hồng"})
mapArray:push({ id = 181, answer = "A", des = "Ác Quán Mãn Doanh"})
mapArray:push({ id = 182, answer = "B", des = "Việc ác bất tận"})
mapArray:push({ id = 183, answer = "C", des = "Hung thần ác sát"})
mapArray:push({ id = 184, answer = "A", des = "Nguyễn Tinh Trúc"})
mapArray:push({ id = 185, answer = "B", des = "Cam Bảo Bảo"})
mapArray:push({ id = 186, answer = "C", des = "Tần Hồng Miên"})
mapArray:push({ id = 187, answer = "A", des = "Hỏa Diễm Đao"})
mapArray:push({ id = 188, answer = "B", des = "Vô Tương Kiếp Chỉ"})
mapArray:push({ id = 189, answer = "C", des = "Dịch Cân Kinh"})
mapArray:push({ id = 190, answer = "A", des = "Khâu Xử Cơ"})
mapArray:push({ id = 191, answer = "B", des = "Chu Tử Liễu"})
mapArray:push({ id = 192, answer = "C", des = "Võ Tam Thông"})
mapArray:push({ id = 193, answer = "A", des = "Lý Văn Tú"})
mapArray:push({ id = 194, answer = "B", des = "Tiêu Trung Tuệ"})
mapArray:push({ id = 195, answer = "C", des = "Miêu Nhược Lan"})
mapArray:push({ id = 196, answer = "A", des = "Thanh Mộc đường"})
mapArray:push({ id = 197, answer = "B", des = "Thần Đao Đường"})
mapArray:push({ id = 198, answer = "C", des = "Vạn mã đường"})
mapArray:push({ id = 199, answer = "A", des = "Bình Nhất Chỉ"})
mapArray:push({ id = 200, answer = "B", des = "Hắc bạch tử"})
mapArray:push({ id = 201, answer = "C", des = "Hoàng Chung Công"})
mapArray:push({ id = 202, answer = "A", des = "Du Đại Nham"})
mapArray:push({ id = 203, answer = "B", des = "Du Liên Chu"})
mapArray:push({ id = 204, answer = "C", des = "Trương Tùng Khê"})
mapArray:push({ id = 205, answer = "A", des = "Cổ mộ U cư"})
mapArray:push({ id = 206, answer = "B", des = "Tây tử nâng tâm"})
mapArray:push({ id = 207, answer = "C", des = "Điêu Thuyền Bái Nguyệt"})
mapArray:push({ id = 208, answer = "A", des = "Ni cô"})
mapArray:push({ id = 209, answer = "B", des = "Đạo Cô"})
mapArray:push({ id = 210, answer = "C", des = "Hiệp Nữ"})
mapArray:push({ id = 211, answer = "B", des = "Đường Thi kiếm pháp"})
mapArray:push({ id = 212, answer = "C", des = "Liên Thành kiếm pháp"})
mapArray:push({ id = 213, answer = "A", des = "Thảng Thi Kiếm Pháp"})
mapArray:push({ id = 214, answer = "B", des = "Đinh Điển"})
mapArray:push({ id = 215, answer = "C", des = "Mai Niệm Sanh"})
mapArray:push({ id = 216, answer = "A", des = "Thích Trường Phát"})
mapArray:push({ id = 217, answer = "B", des = "Linh kiếm song hiệp"})
mapArray:push({ id = 218, answer = "C", des = "Thần Điêu Hiệp Lữ"})
mapArray:push({ id = 219, answer = "A", des = "Tắc Bắc song anh"})
mapArray:push({ id = 220, answer = "B", des = "Kiều Tam Hòe"})
mapArray:push({ id = 221, answer = "C", des = "Kiều Viễn Sơn"})
mapArray:push({ id = 222, answer = "A", des = "Huyền Khổ"})
mapArray:push({ id = 223, answer = "B", des = "Đại Luân Minh Vương"})
mapArray:push({ id = 224, answer = "C", des = "Hướng Vọng Hải"})
mapArray:push({ id = 225, answer = "A", des = "Ngô Trường Phong"})
mapArray:push({ id = 226, answer = "B", des = "Tẫn lực tương trợ, dĩ tử tương báo."})
mapArray:push({ id = 227, answer = "C", des = "Khoanh tay đứng nhìn"})
mapArray:push({ id = 228, answer = "A", des = "Tẩu vi thượng kế"})
mapArray:push({ id = 229, answer = "B", des = "Sinh Tử Phù"})
mapArray:push({ id = 230, answer = "C", des = "Thiên Sơn Lục Dương Chưởng"})
mapArray:push({ id = 231, answer = "A", des = "Thiên Sơn Chiết Mai Thủ"})
mapArray:push({ id = 232, answer = "B", des = "Lý Thu Thủy muội muội"})
mapArray:push({ id = 233, answer = "C", des = "Lý Thu Thủy"})
mapArray:push({ id = 234, answer = "A", des = "Thiên Sơn Đồng Lão"})
mapArray:push({ id = 235, answer = "B", des = "Cúc Kiếm"})
mapArray:push({ id = 236, answer = "C", des = "Cúc bạn"})
mapArray:push({ id = 237, answer = "A", des = "Dư bà bà"})
mapArray:push({ id = 238, answer = "B", des = "Mộ Dung Phục"})
mapArray:push({ id = 239, answer = "C", des = "Đoàn Duyên Khánh"})
mapArray:push({ id = 240, answer = "A", des = "Đoàn Dự"})
mapArray:push({ id = 241, answer = "C", des = "Hãn Huyết Bảo Mã"})
mapArray:push({ id = 242, answer = "B", des = "Đại Uyển lương câu"})
mapArray:push({ id = 243, answer = "A", des = "Tây vực danh kỵ"})
mapArray:push({ id = 244, answer = "C", des = "Trương Gia Khẩu"})
mapArray:push({ id = 245, answer = "B", des = "Yến Kinh"})
mapArray:push({ id = 246, answer = "A", des = "Đào hoa đảo"})
mapArray:push({ id = 247, answer = "C", des = "Mai Siêu Phong"})
mapArray:push({ id = 248, answer = "B", des = "Trần Huyền Phong"})
mapArray:push({ id = 249, answer = "A", des = "Khúc Linh Phong"})
mapArray:push({ id = 250, answer = "C", des = "Hài tử"})
mapArray:push({ id = 251, answer = "B", des = "Cái trâm cài đầu"})
mapArray:push({ id = 252, answer = "A", des = "Túi tiền"})
mapArray:push({ id = 253, answer = "C", des = "Thứ bảy"})
mapArray:push({ id = 254, answer = "B", des = "Thứ năm"})
mapArray:push({ id = 255, answer = "A", des = "Thứ ba"})
mapArray:push({ id = 256, answer = "C", des = "Khâu Xử Cơ"})
mapArray:push({ id = 257, answer = "B", des = "Mã Ngọc"})
mapArray:push({ id = 258, answer = "A", des = "Vương Xử Nhất"})
mapArray:push({ id = 259, answer = "C", des = "Phong lăng độ khẩu"})
mapArray:push({ id = 260, answer = "B", des = "Tương Dương thành"})
mapArray:push({ id = 261, answer = "A", des = "Tuyệt Tình Cốc"})
mapArray:push({ id = 262, answer = "C", des = "Phái Hằng Sơn"})
mapArray:push({ id = 263, answer = "B", des = "Phái Hoa Sơn"})
mapArray:push({ id = 264, answer = "A", des = "Tung Sơn Phái"})
mapArray:push({ id = 265, answer = "C", des = "Tam Thi Não Thần Đan"})
mapArray:push({ id = 266, answer = "B", des = "Báo Thai Dịch Cân hoàn"})
mapArray:push({ id = 267, answer = "A", des = "Thất Trùng Thất Hoa Cao"})
mapArray:push({ id = 268, answer = "C", des = "Huyền Thiết Trọng Kiếm"})
mapArray:push({ id = 269, answer = "B", des = "Tử Vi Nhuyễn Kiếm"})
mapArray:push({ id = 270, answer = "A", des = "Kiếm gỗ"})
mapArray:push({ id = 271, answer = "A", des = "Ký kiến quân tử, vân hồ bất hỉ"})
mapArray:push({ id = 272, answer = "B", des = "Yểu điệu thục nữ, quân tử hảo cầu"})
mapArray:push({ id = 273, answer = "C", des = "Đào chi Yêu yêu, sáng rực nó hoa"})
mapArray:push({ id = 274, answer = "A", des = "Long Tượng Bàn Nhược Công"})
mapArray:push({ id = 275, answer = "B", des = "Di Hồn Đại Pháp"})
mapArray:push({ id = 276, answer = "C", des = "Ngũ luân đại chuyển"})
mapArray:push({ id = 277, answer = "A", des = "Sử ức đao"})
mapArray:push({ id = 278, answer = "B", des = "Cẩu tạp chủng"})
mapArray:push({ id = 279, answer = "C", des = "Thạch Trung Ngọc"})
mapArray:push({ id = 280, answer = "A", des = "Tạ Tốn tóc"})
mapArray:push({ id = 281, answer = "B", des = "Đồ Long Đao"})
mapArray:push({ id = 282, answer = "C", des = "Một rương hoàng kim"})
mapArray:push({ id = 283, answer = "A", des = "Hán thủy ngư chu trung"})
mapArray:push({ id = 284, answer = "B", des = "Nga Mi Sơn"})
mapArray:push({ id = 285, answer = "C", des = "Núi Võ Đang"})
mapArray:push({ id = 286, answer = "A", des = "A Cửu"})
mapArray:push({ id = 287, answer = "B", des = "Ôn Thanh Thanh"})
mapArray:push({ id = 288, answer = "C", des = "Hà Thiết Thủ"})
mapArray:push({ id = 289, answer = "A", des = "Dương"})
mapArray:push({ id = 290, answer = "B", des = "Lý"})
mapArray:push({ id = 291, answer = "C", des = "Triệu"})
mapArray:push({ id = 292, answer = "A", des = "Vô Nhai Tử"})
mapArray:push({ id = 293, answer = "B", des = "Tô Tinh Hà"})
mapArray:push({ id = 294, answer = "C", des = "Đinh Xuân Thu"})
mapArray:push({ id = 295, answer = "A", des = "Ngũ Hổ Đoạn Môn Đao"})
mapArray:push({ id = 296, answer = "B", des = "Lạc Anh Thần Kiếm Chưởng"})
mapArray:push({ id = 297, answer = "C", des = "Cuồng phong tuyệt kỹ"})
mapArray:push({ id = 298, answer = "A", des = "Triệu Mẫn quận chúa"})
mapArray:push({ id = 299, answer = "B", des = "Trường Bình Công Chúa"})
mapArray:push({ id = 300, answer = "C", des = "Kiến Ninh công chúa"})
mapArray:push({ id = 301, answer = "B", des = "Vọng đế xuân tâm thác đỗ quyên"})
mapArray:push({ id = 302, answer = "C", des = "Lam điền nhật noãn ngọc sinh yên"})
mapArray:push({ id = 303, answer = "A", des = "Nhất huyền nhất trụ tư hoa niên"})
mapArray:push({ id = 304, answer = "B", des = "Nguyệt dũng đại giang lưu"})
mapArray:push({ id = 305, answer = "C", des = "Minh nguyệt chiếu Đại Giang"})
mapArray:push({ id = 306, answer = "A", des = "Thanh phong phất sơn cương"})
mapArray:push({ id = 307, answer = "B", des = "Tự tại kiều oanh kháp kháp đề"})
mapArray:push({ id = 308, answer = "C", des = "Xuân phong hựu lục giang nam ngạn"})
mapArray:push({ id = 309, answer = "A", des = "Thiên thụ vạn thụ lê hoa khai"})
mapArray:push({ id = 310, answer = "B", des = "Hồng Lâu Mộng"})
mapArray:push({ id = 311, answer = "C", des = "Tây Sương Ký"})
mapArray:push({ id = 312, answer = "A", des = "Nghiệt Hải hoa"})
mapArray:push({ id = 313, answer = "B", des = "Mẫu Đơn đình"})
mapArray:push({ id = 314, answer = "C", des = "Trường Sinh Điện"})
mapArray:push({ id = 315, answer = "A", des = "Đậu Nga oan"})
mapArray:push({ id = 316, answer = "B", des = "Tư Mã Quang"})
mapArray:push({ id = 317, answer = "C", des = "Tư Mã Thiên"})
mapArray:push({ id = 318, answer = "A", des = "Tư Mã Chiêu"})
mapArray:push({ id = 319, answer = "B", des = "Hương Sơn cư sĩ"})
mapArray:push({ id = 320, answer = "C", des = "Nhạc thiên cư sĩ"})
mapArray:push({ id = 321, answer = "A", des = "Lục nhất cư sĩ"})
mapArray:push({ id = 322, answer = "B", des = "Âu Dương Tu"})
mapArray:push({ id = 323, answer = "C", des = "Tô Thức"})
mapArray:push({ id = 324, answer = "A", des = "Hàn Dũ"})
mapArray:push({ id = 325, answer = "B", des = "Vương Xương Linh"})
mapArray:push({ id = 326, answer = "C", des = "Vương Bột"})
mapArray:push({ id = 327, answer = "A", des = "Lục Du"})
mapArray:push({ id = 328, answer = "B", des = "Lý Bạch cùng Đỗ Phủ"})
mapArray:push({ id = 329, answer = "C", des = "Lý Thương Ẩn cùng Đỗ Mục"})
mapArray:push({ id = 330, answer = "A", des = "Lý Hạ cùng Đỗ Vi"})
mapArray:push({ id = 331, answer = "C", des = "Lý Bạch"})
mapArray:push({ id = 332, answer = "B", des = "Âu Dương Tu"})
mapArray:push({ id = 333, answer = "A", des = "Liễu Tông Nguyên"})
mapArray:push({ id = 334, answer = "C", des = "Đại học"})
mapArray:push({ id = 335, answer = "B", des = "Mạnh Tử"})
mapArray:push({ id = 336, answer = "A", des = "Luận Ngữ"})
mapArray:push({ id = 337, answer = "C", des = "Kinh Thi"})
mapArray:push({ id = 338, answer = "B", des = "Trung dung"})
mapArray:push({ id = 339, answer = "A", des = "Mạnh Tử"})
mapArray:push({ id = 340, answer = "C", des = "Tĩnh Dạ Tư"})
mapArray:push({ id = 341, answer = "B", des = "Nguyệt dạ trữ hoài"})
mapArray:push({ id = 342, answer = "A", des = "Thu tứ"})
mapArray:push({ id = 343, answer = "C", des = "Vương thực phủ"})
mapArray:push({ id = 344, answer = "B", des = "Mã Trí Viễn"})
mapArray:push({ id = 345, answer = "A", des = "Quan Hán Khanh"})
mapArray:push({ id = 346, answer = "C", des = "Lý Hạ"})
mapArray:push({ id = 347, answer = "B", des = "Cổ đảo"})
mapArray:push({ id = 348, answer = "A", des = "Mạnh Giao"})
mapArray:push({ id = 349, answer = "C", des = "Thâm hạng minh triêu mại hạnh hoa"})
mapArray:push({ id = 350, answer = "B", des = "Tình song tế nhũ hí phân trà"})
mapArray:push({ id = 351, answer = "A", des = "Do cập thanh minh khả đáo gia"})
mapArray:push({ id = 352, answer = "C", des = "Sấu Ngọc Từ"})
mapArray:push({ id = 353, answer = "B", des = "Hoa gian tập"})
mapArray:push({ id = 354, answer = "A", des = "Chương nhạc tập"})
mapArray:push({ id = 355, answer = "C", des = "Hồng Lâu Mộng"})
mapArray:push({ id = 356, answer = "B", des = "Liêu Trai Chí Dị"})
mapArray:push({ id = 357, answer = "A", des = "Lương Chúc"})
mapArray:push({ id = 358, answer = "C", des = "Ly Tao"})
mapArray:push({ id = 359, answer = "B", des = "Thiên Vấn"})
mapArray:push({ id = 360, answer = "A", des = "Cửu Ca"})
mapArray:push({ id = 361, answer = "A", des = "Tào Thực"})
mapArray:push({ id = 362, answer = "B", des = "Tào Tháo"})
mapArray:push({ id = 363, answer = "C", des = "Tào Phi"})
mapArray:push({ id = 364, answer = "A", des = "Tân Khí Tật"})
mapArray:push({ id = 365, answer = "B", des = "Nhạc Phi"})
mapArray:push({ id = 366, answer = "C", des = "Hoắc Khứ Bệnh"})
mapArray:push({ id = 367, answer = "A", des = "Niếp chính thứ hàn vương"})
mapArray:push({ id = 368, answer = "B", des = "Yếu ly thứ khánh kỵ"})
mapArray:push({ id = 369, answer = "C", des = "Kinh kha thứ tần vương"})
mapArray:push({ id = 370, answer = "A", des = "Phùng Mộng Long"})
mapArray:push({ id = 371, answer = "B", des = "Lăng mông sơ"})
mapArray:push({ id = 372, answer = "C", des = "Lý bá nguyên"})
mapArray:push({ id = 373, answer = "A", des = "Đào Uyên Minh"})
mapArray:push({ id = 374, answer = "B", des = "Vương Duy"})
mapArray:push({ id = 375, answer = "C", des = "Mạnh Hạo Nhiên"})
mapArray:push({ id = 376, answer = "A", des = "Run"})
mapArray:push({ id = 377, answer = "B", des = "Cung"})
mapArray:push({ id = 378, answer = "C", des = "Thương"})
mapArray:push({ id = 379, answer = "A", des = "Ba mươi"})
mapArray:push({ id = 380, answer = "B", des = "Bốn mươi"})
mapArray:push({ id = 381, answer = "C", des = "Hai mươi"})
mapArray:push({ id = 382, answer = "A", des = "Thám Hoa"})
mapArray:push({ id = 383, answer = "B", des = "Bảng Nhãn"})
mapArray:push({ id = 384, answer = "C", des = "Trạng Nguyên"})
mapArray:push({ id = 385, answer = "A", des = "Dịch Kinh"})
mapArray:push({ id = 386, answer = "B", des = "Lễ Ký"})
mapArray:push({ id = 387, answer = "C", des = "Xuân thu"})
mapArray:push({ id = 388, answer = "A", des = "Huynh vi đệ cương"})
mapArray:push({ id = 389, answer = "B", des = "Phụ vi tử cương"})
mapArray:push({ id = 390, answer = "C", des = "Quân Vi Thần cương"})
mapArray:push({ id = 391, answer = "B", des = "Minh"})
mapArray:push({ id = 392, answer = "C", des = "Nhân"})
mapArray:push({ id = 393, answer = "A", des = "Trí"})
mapArray:push({ id = 394, answer = "B", des = "Phạm Trọng Yêm"})
mapArray:push({ id = 395, answer = "C", des = "Phạm Tiến"})
mapArray:push({ id = 396, answer = "A", des = "Phạm Dao"})
mapArray:push({ id = 397, answer = "B", des = "Gia Cát Lượng"})
mapArray:push({ id = 398, answer = "C", des = "Bạch Khởi"})
mapArray:push({ id = 399, answer = "A", des = "Hàn Tín"})
mapArray:push({ id = 400, answer = "B", des = "Tần Lương Ngọc"})
mapArray:push({ id = 401, answer = "C", des = "Hoa Mộc Lan"})
mapArray:push({ id = 402, answer = "A", des = "Mộc Quế Anh"})
mapArray:push({ id = 403, answer = "B", des = "Trác Văn Quân"})
mapArray:push({ id = 404, answer = "C", des = "Tây Thi"})
mapArray:push({ id = 405, answer = "A", des = "Vương tường"})
mapArray:push({ id = 406, answer = "B", des = "Tần Vũ Dương"})
mapArray:push({ id = 407, answer = "C", des = "Chuyên Chư"})
mapArray:push({ id = 408, answer = "A", des = "Dự Nhượng"})
mapArray:push({ id = 409, answer = "B", des = "Hoa Sơn"})
mapArray:push({ id = 410, answer = "C", des = "Hằng Sơn"})
mapArray:push({ id = 411, answer = "A", des = "Thái Sơn"})
mapArray:push({ id = 412, answer = "B", des = "Lý bạch 《 trường kiền hành 》"})
mapArray:push({ id = 413, answer = "C", des = "Bạch Cư Dịch 《 Trường Hận ca 》"})
mapArray:push({ id = 414, answer = "A", des = "Lý Dục 《 Ngu Mỹ Nhân 》"})
mapArray:push({ id = 415, answer = "B", des = "Sử ký"})
mapArray:push({ id = 416, answer = "C", des = "Hán Thư"})
mapArray:push({ id = 417, answer = "A", des = "Xuân thu"})
mapArray:push({ id = 418, answer = "B", des = "Tinh vệ điền hải"})
mapArray:push({ id = 419, answer = "C", des = "Bạch Xà truyện"})
mapArray:push({ id = 420, answer = "A", des = "Lương Chúc"})
mapArray:push({ id = 421, answer = "C", des = "Tây Thi"})
mapArray:push({ id = 422, answer = "B", des = "Điêu Thuyền"})
mapArray:push({ id = 423, answer = "A", des = "Vương tường"})
mapArray:push({ id = 424, answer = "C", des = "Tết Nguyên Tiêu"})
mapArray:push({ id = 425, answer = "B", des = "Tết Trung Nguyên"})
mapArray:push({ id = 426, answer = "A", des = "Hạ nguyên tiết"})
mapArray:push({ id = 427, answer = "C", des = "Ngô"})
mapArray:push({ id = 428, answer = "B", des = "Tề"})
mapArray:push({ id = 429, answer = "A", des = "Sở"})
mapArray:push({ id = 430, answer = "C", des = "Tề Hoàn Công"})
mapArray:push({ id = 431, answer = "B", des = "Sở Trang Vương"})
mapArray:push({ id = 432, answer = "A", des = "Tống Tương Công"})
mapArray:push({ id = 433, answer = "C", des = "Triệu Phi Yến"})
mapArray:push({ id = 434, answer = "B", des = "Triệu Hợp Đức"})
mapArray:push({ id = 435, answer = "A", des = "Âm Lệ Hoa"})
mapArray:push({ id = 436, answer = "C", des = "Sáu mươi năm"})
mapArray:push({ id = 437, answer = "B", des = "Ba mươi năm"})
mapArray:push({ id = 438, answer = "A", des = "Năm mươi năm"})
mapArray:push({ id = 439, answer = "C", des = "Ba mươi dặm"})
mapArray:push({ id = 440, answer = "B", des = "Hai mươi dặm"})
mapArray:push({ id = 441, answer = "A", des = "Năm mươi dặm"})
mapArray:push({ id = 442, answer = "C", des = "Mười sáu tuổi"})
mapArray:push({ id = 443, answer = "B", des = "Hai mươi tám tuổi"})
mapArray:push({ id = 444, answer = "A", des = "Mười tám tuổi"})
mapArray:push({ id = 445, answer = "C", des = "Hạ Tri Chương"})
mapArray:push({ id = 446, answer = "B", des = "Lý Hạ"})
mapArray:push({ id = 447, answer = "A", des = "Lưu qua"})
mapArray:push({ id = 448, answer = "C", des = "Trương Nhược Hư"})
mapArray:push({ id = 449, answer = "B", des = "Liễu Tông Nguyên"})
mapArray:push({ id = 450, answer = "A", des = "Chu Đôn Di"})
mapArray:push({ id = 451, answer = "A", des = "Nga Mi tổ sư"})
mapArray:push({ id = 452, answer = "B", des = "Trương Tam Phong"})
mapArray:push({ id = 453, answer = "C", des = "Cửu Sát cư sĩ"})
mapArray:push({ id = 454, answer = "A", des = "Nữ tử áo vàng"})
mapArray:push({ id = 455, answer = "B", des = "Mộ Dung Tông chủ"})
mapArray:push({ id = 456, answer = "C", des = "Tiền triều thái giám"})
mapArray:push({ id = 457, answer = "A", des = "Thái Huyền công tử"})
mapArray:push({ id = 458, answer = "B", des = "Tiêu dao chân nhân"})
mapArray:push({ id = 459, answer = "C", des = "Ngũ nhạc minh chủ"})
mapArray:push({ id = 460, answer = "A", des = "120"})
mapArray:push({ id = 461, answer = "B", des = "110"})
mapArray:push({ id = 462, answer = "C", des = "100"})
mapArray:push({ id = 463, answer = "A", des = "Kiếm Tông ẩn sĩ"})
mapArray:push({ id = 464, answer = "B", des = "Ngũ nhạc chưởng môn"})
mapArray:push({ id = 465, answer = "C", des = "Ngoan bì lão nhân"})
mapArray:push({ id = 466, answer = "A", des = "Tích nộ"})
mapArray:push({ id = 467, answer = "B", des = "Tổn tâm"})
mapArray:push({ id = 468, answer = "C", des = "Minh hồn"})
mapArray:push({ id = 469, answer = "A", des = "Phi Hồ công tử"})
mapArray:push({ id = 470, answer = "B", des = "Nữ tử áo vàng"})
mapArray:push({ id = 471, answer = "C", des = "Nga Mi tổ sư"})
mapArray:push({ id = 472, answer = "A", des = "Linh Xà phu nhân"})
mapArray:push({ id = 473, answer = "B", des = "Vô tình Sư Thái"})
mapArray:push({ id = 474, answer = "C", des = "Quang minh Tả Sứ"})
mapArray:push({ id = 475, answer = "A", des = "Thứ hai"})
mapArray:push({ id = 476, answer = "B", des = "Thứ tư"})
mapArray:push({ id = 477, answer = "C", des = "Thứ sáu"})
mapArray:push({ id = 478, answer = "A", des = "Chủ nhật"})
mapArray:push({ id = 479, answer = "B", des = "Thứ bảy"})
mapArray:push({ id = 480, answer = "C", des = "Thứ hai"})
mapArray:push({ id = 481, answer = "B", des = "Đột phá đan"})
mapArray:push({ id = 482, answer = "C", des = "Hiệp hồn"})
mapArray:push({ id = 483, answer = "A", des = "Bí Yếu mảnh vỡ"})
mapArray:push({ id = 484, answer = "B", des = "5 Lần"})
mapArray:push({ id = 485, answer = "C", des = "4 Lần"})
mapArray:push({ id = 486, answer = "A", des = "6 Lần"})
mapArray:push({ id = 487, answer = "B", des = "1000"})
mapArray:push({ id = 488, answer = "C", des = "1500"})
mapArray:push({ id = 489, answer = "A", des = "800"})
mapArray:push({ id = 490, answer = "B", des = "21 Điểm"})
mapArray:push({ id = 491, answer = "C", des = "18 Điểm"})
mapArray:push({ id = 492, answer = "A", des = "12 Điểm"})
mapArray:push({ id = 493, answer = "B", des = "50 Cái"})
mapArray:push({ id = 494, answer = "C", des = "30 Cái"})
mapArray:push({ id = 495, answer = "A", des = "40 Cái"})
mapArray:push({ id = 496, answer = "B", des = "3 Tinh"})
mapArray:push({ id = 497, answer = "C", des = "10 Tinh"})
mapArray:push({ id = 498, answer = "A", des = "5 Tinh"})
mapArray:push({ id = 499, answer = "B", des = "20 Điểm"})
mapArray:push({ id = 500, answer = "C", des = "10 Điểm"})
mapArray:push({ id = 501, answer = "A", des = "30 Điểm"})
mapArray:push({ id = 502, answer = "B", des = "Giới chỉ"})
mapArray:push({ id = 503, answer = "C", des = "Hài tử"})
mapArray:push({ id = 504, answer = "A", des = "Áo"})
mapArray:push({ id = 505, answer = "B", des = "Thiên Thư"})
mapArray:push({ id = 506, answer = "C", des = "Tâm pháp"})
mapArray:push({ id = 507, answer = "A", des = "Vũ khí"})
mapArray:push({ id = 508, answer = "B", des = "Vượt phục Võ Lâm Đại Hội quán quân"})
mapArray:push({ id = 509, answer = "C", des = "Thiên Giai tranh bá thứ 1 tên"})
mapArray:push({ id = 510, answer = "A", des = "Luận kiếm phong thứ 1 tên"})
mapArray:push({ id = 511, answer = "C", des = "600 Cùng 60"})
mapArray:push({ id = 512, answer = "B", des = "400 Cùng 30"})
mapArray:push({ id = 513, answer = "A", des = "500 Cùng 40"})
mapArray:push({ id = 514, answer = "C", des = "Danh nhân đường hạng nhất"})
mapArray:push({ id = 515, answer = "B", des = "Vượt phục Võ Lâm Đại Hội hạng nhất"})
mapArray:push({ id = 516, answer = "A", des = "Quần hào phổ hạng nhất"})
mapArray:push({ id = 517, answer = "C", des = "10 Lần"})
mapArray:push({ id = 518, answer = "B", des = "8 Lần"})
mapArray:push({ id = 519, answer = "A", des = "12 Lần"})
mapArray:push({ id = 520, answer = "C", des = "Truyền thuyết"})
mapArray:push({ id = 521, answer = "B", des = "Quý hiếm"})
mapArray:push({ id = 522, answer = "A", des = "Hi hữu"})
mapArray:push({ id = 523, answer = "C", des = "Bên ta hiệp khách bị khống chế"})
mapArray:push({ id = 524, answer = "B", des = "Kỹ năng không phải làm lạnh bên trong"})
mapArray:push({ id = 525, answer = "A", des = "Bên ta hiệp khách HP thấp hơn nhất định tỉ lệ phần trăm"})
mapArray:push({ id = 526, answer = "C", des = "3 Cái"})
mapArray:push({ id = 527, answer = "B", des = "2 Cái"})
mapArray:push({ id = 528, answer = "A", des = "5 Cái"})
mapArray:push({ id = 529, answer = "C", des = "4 Cái"})
mapArray:push({ id = 530, answer = "B", des = "3 Cái"})
mapArray:push({ id = 531, answer = "A", des = "5 Cái"})
mapArray:push({ id = 532, answer = "C", des = "30 Cái"})
mapArray:push({ id = 533, answer = "B", des = "20 Cái"})
mapArray:push({ id = 534, answer = "A", des = "25 Cái"})
mapArray:push({ id = 535, answer = "C", des = "Phổ thông đồ màu cam chuẩn bị"})
mapArray:push({ id = 536, answer = "B", des = "VIP trang bị"})
mapArray:push({ id = 537, answer = "A", des = "Trang Bị Kỷ Niệm"})
mapArray:push({ id = 538, answer = "C", des = "Anh hiệp Thiên Thư"})
mapArray:push({ id = 539, answer = "B", des = "Thiên Thư Kỷ Niệm"})
mapArray:push({ id = 540, answer = "A", des = "Cửu kiếm trân bản"})
mapArray:push({ id = 541, answer = "A", des = "Thánh đạo phách cường"})
mapArray:push({ id = 542, answer = "B", des = "8 bộ thần uy"})
mapArray:push({ id = 543, answer = "C", des = "Chân Viêm bất diệt"})
mapArray:push({ id = 544, answer = "A", des = "Kiều bang chủ"})
mapArray:push({ id = 545, answer = "B", des = "Trùng Dương chân nhân"})
mapArray:push({ id = 546, answer = "C", des = "Quang minh Tả Sứ"})
mapArray:push({ id = 547, answer = "A", des = "Chu chưởng môn"})
mapArray:push({ id = 548, answer = "B", des = "Đại sư huynh"})
mapArray:push({ id = 549, answer = "C", des = "Nữ tử áo vàng"})
mapArray:push({ id = 550, answer = "A", des = "4 Lần"})
mapArray:push({ id = 551, answer = "B", des = "3 Lần"})
mapArray:push({ id = 552, answer = "C", des = "5 Lần"})
mapArray:push({ id = 553, answer = "A", des = "Nữ Nhi Hồng"})
mapArray:push({ id = 554, answer = "B", des = "Trúc Diệp Thanh"})
mapArray:push({ id = 555, answer = "C", des = "Bích Loa Xuân"})
mapArray:push({ id = 556, answer = "A", des = "Uy vọng thương thành"})
mapArray:push({ id = 557, answer = "B", des = "Vượt phục cửa hàng"})
mapArray:push({ id = 558, answer = "C", des = "Quần hào cửa hàng"})
mapArray:push({ id = 559, answer = "A", des = "200 Nguyên Bảo"})
mapArray:push({ id = 560, answer = "B", des = "200 Vạn đồng tệ"})
mapArray:push({ id = 561, answer = "C", des = "200 Vạn điểm anh hùng"})
mapArray:push({ id = 562, answer = "A", des = "4000"})
mapArray:push({ id = 563, answer = "B", des = "3000"})
mapArray:push({ id = 564, answer = "C", des = "2000"})
mapArray:push({ id = 565, answer = "A", des = "500"})
mapArray:push({ id = 566, answer = "B", des = "600"})
mapArray:push({ id = 567, answer = "C", des = "800"})
mapArray:push({ id = 568, answer = "A", des = "Đơn phục Võ Lâm Đại Hội trước 8 tên"})
mapArray:push({ id = 569, answer = "B", des = "Quần hào phổ trước 8 tên"})
mapArray:push({ id = 570, answer = "C", des = "Chiến lực bảng xếp hạng trước 8 tên"})
mapArray:push({ id = 571, answer = "B", des = "Trung Nguyên"})
mapArray:push({ id = 572, answer = "C", des = "Tây Xuyên"})
mapArray:push({ id = 573, answer = "A", des = "Giang Nam"})
mapArray:push({ id = 574, answer = "B", des = "Trước 20 Tên"})
mapArray:push({ id = 575, answer = "C", des = "Trước 10 Tên"})
mapArray:push({ id = 576, answer = "A", des = "Trước 3 Tên"})
mapArray:push({ id = 577, answer = "B", des = "Chủ nhật"})
mapArray:push({ id = 578, answer = "C", des = "Thứ hai"})
mapArray:push({ id = 579, answer = "A", des = "Thứ bảy"})
mapArray:push({ id = 580, answer = "B", des = "60"})
mapArray:push({ id = 581, answer = "C", des = "50"})
mapArray:push({ id = 582, answer = "A", des = "40"})
mapArray:push({ id = 583, answer = "B", des = "30 Cái"})
mapArray:push({ id = 584, answer = "C", des = "20 Cái"})
mapArray:push({ id = 585, answer = "A", des = "25 Cái"})
mapArray:push({ id = 586, answer = "B", des = "5 Lần"})
mapArray:push({ id = 587, answer = "C", des = "3 Lần"})
mapArray:push({ id = 588, answer = "A", des = "1 Lần"})
mapArray:push({ id = 589, answer = "B", des = "20 Nguyên Bảo"})
mapArray:push({ id = 590, answer = "C", des = "50 Nguyên Bảo"})
mapArray:push({ id = 591, answer = "A", des = "100 Nguyên Bảo"})
mapArray:push({ id = 592, answer = "B", des = "Thái Huyền công tử"})
mapArray:push({ id = 593, answer = "C", des = "Thái Giám tiền Triều"})
mapArray:push({ id = 594, answer = "A", des = "Đạt Ma"})
mapArray:push({ id = 595, answer = "B", des = "Nữ tử áo vàng"})
mapArray:push({ id = 596, answer = "C", des = "Tinh nghịch lão nhân"})
mapArray:push({ id = 597, answer = "A", des = "Ngũ Nhạc minh chủ"})
mapArray:push({ id = 598, answer = "B", des = "Ngũ Nhạc Chưởng Môn"})
mapArray:push({ id = 599, answer = "C", des = "Lâm viễn Đồ"})
mapArray:push({ id = 600, answer = "A", des = "Kiếm Tông ẩn sĩ"})
return mapArray
