local mapArray = MEMapArray:new()
mapArray:push({ id = 1, name ="bang phái", open = 1, code = 17414})
mapArray:push({ id = 2, name ="kỹ năng sách lược", open = 1, code = 3883})
mapArray:push({ id = 3, name ="đổ thạch", open = 0, code = 22528})
mapArray:push({ id = 4, name ="trợ chiến phù hợp", open = 1, code = 17170})
mapArray:push({ id = 5, name ="Thần Nông mỏ", open = 1, code = 20480})
mapArray:push({ id = 6, name ="trang bị thăng giai", open = 1, code = 4218})
mapArray:push({ id = 7, name ="bang phái phía sau núi", open = 1, code = 17433})
mapArray:push({ id = 8, name ="đại hội võ lâm", open = 1, code = 17665})
mapArray:push({ id = 9, name ="bắc quật", open = 1, code = 18690})
mapArray:push({ id = 10, name ="kinh mạch đột phá", open = 1, code = 5376})
mapArray:push({ id = 11, name ="trang bị đúc lại", open = 1, code = 4226})
mapArray:push({ id = 12, name ="bang phái tranh phong", open = 1, code = 0})
mapArray:push({ id = 13, name ="kỳ môn chui", open = 1, code = 20992})
mapArray:push({ id = 14, name ="diễn viên thăng chanh", open = 1, code = 5380})
mapArray:push({ id = 15, name ="nhảy qua phục đại hội võ lâm", open = 1, code = 17685})
mapArray:push({ id = 16, name ="trận pháp", open = 1, code = 27136})
mapArray:push({ id = 17, name ="sấm trận", open = 1, code = 30209})
mapArray:push({ id = 18, name ="luyện thể", open = 1, code = 26112})
mapArray:push({ id = 19, name ="bang phái tu luyện tràng", open = 1, code = 17433})
mapArray:push({ id = 20, name ="vô lượng ác mộng", open = 1, code = 5890})
mapArray:push({ id = 21, name ="nhảy qua phục bang phái tranh phong", open = 1, code = 0})
mapArray:push({ id = 22, name ="du lịch", open = 1, code = 22784})
mapArray:push({ id = 23, name ="thiên thư", open = 1, code = 24577})
mapArray:push({ id = 24, name ="tiềm tu", open = 1, code = 26624})
mapArray:push({ id = 25, name ="màu đỏ hiệp khách", open = 1, code = 0})
mapArray:push({ id = 26, name ="phục ma lục thăng giai đoạn", open = 0, code = 0})
mapArray:push({ id = 27, name ="võ lâm", open = 1, code = 0})
mapArray:push({ id = 28, name ="kỳ nguyện", open = 1, code = 0})
mapArray:push({ id = 29, name ="trang bị thăng mười sao", open = 1, code = 0})
mapArray:push({ id = 30, name ="hộ giá", open = 0, code = 0})
mapArray:push({ id = 31, name ="hiệp khách truyện ký", open = 1, code = 0})
mapArray:push({ id = 32, name ="kế tiếp lễ độ", open = 1, code = 0})
mapArray:push({ id = 33, name ="mười bốn nhật hoạt động", open = 1, code = 0})
mapArray:push({ id = 34, name ="ngoạn gia trở về", open = 1, code = 0})
mapArray:push({ id = 35, name ="hoàn chỉnh túi kế tiếp lễ độ", open = 0, code = 0})
mapArray:push({ id = 36, name ="luận kiếm ngọn núi", open = 1, code = 0})
mapArray:push({ id = 37, name ="lãng nhân võ sĩ", open = 1, code = 0})
return mapArray
