local mapArray = MEMapArray:new()
mapArray:push({ id = 1, quality = 1, sub_count = 2, sub_type = 1, tppe_value = 0, describe_title = "Bảo thạch lỗ：+1"})
mapArray:push({ id = 2, quality = 2, sub_count = 3, sub_type = 3, tppe_value = 1000, describe_title = "Thuộc tính tăng：10%"})
mapArray:push({ id = 3, quality = 3, sub_count = 3, sub_type = 3, tppe_value = 3000, describe_title = "Thuộc tính tăng：30%"})
mapArray:push({ id = 5, quality = 3, sub_count = 2, sub_type = 3, tppe_value = 2000, describe_title = "Thuộc tính tăng：20%"})
mapArray:push({ id = 4, quality = 4, sub_count = 5, sub_type = 2, tppe_value = 0, describe_title = "Thuộc tính：+1"})
mapArray:push({ id = 6, quality = 4, sub_count = 1, sub_type = 3, tppe_value = 4000, describe_title = "Thuộc tính tăng：40%"})
mapArray:push({ id = 7, quality = 4, sub_count = 2, sub_type = 3, tppe_value = 5000, describe_title = "Thuộc tính tăng：50%"})
mapArray:push({ id = 8, quality = 4, sub_count = 3, sub_type = 3, tppe_value = 6000, describe_title = "Thuộc tính tăng：60%"})
mapArray:push({ id = 9, quality = 4, sub_count = 4, sub_type = 3, tppe_value = 7000, describe_title = "Thuộc tính tăng：70%"})
mapArray:push({ id = 10, quality = 5, sub_count = 3, sub_type = 3, tppe_value = 8000, describe_title = "Thuộc tính tăng：80%"})
mapArray:push({ id = 11, quality = 5, sub_count = 4, sub_type = 3, tppe_value = 9000, describe_title = "Thuộc tính tăng：90%"})
mapArray:push({ id = 12, quality = 5, sub_count = 5, sub_type = 3, tppe_value = 10000, describe_title = "Thuộc tính tăng：100%"})
mapArray:push({ id = 13, quality = 6, sub_count = 3, sub_type = 3, tppe_value = 11500, describe_title = "Thuộc tính tăng：115%"})
mapArray:push({ id = 14, quality = 6, sub_count = 4, sub_type = 3, tppe_value = 13000, describe_title = "Thuộc tính tăng：130%"})
mapArray:push({ id = 15, quality = 6, sub_count = 5, sub_type = 3, tppe_value = 15000, describe_title = "Thuộc tính tăng：150%"})
mapArray:push({ id = 16, quality = 7, sub_count = 3, sub_type = 3, tppe_value = 18000, describe_title = "Thuộc tính tăng：180%"})
mapArray:push({ id = 17, quality = 7, sub_count = 4, sub_type = 3, tppe_value = 21000, describe_title = "Thuộc tính tăng：210%"})
mapArray:push({ id = 18, quality = 7, sub_count = 5, sub_type = 3, tppe_value = 24000, describe_title = "Thuộc tính tăng：240%"})
mapArray:push({ id = 19, quality = 8, sub_count = 3, sub_type = 3, tppe_value = 28000, describe_title = "Thuộc tính tăng：280%"})
mapArray:push({ id = 20, quality = 8, sub_count = 4, sub_type = 3, tppe_value = 32000, describe_title = "Thuộc tính tăng：320%"})
mapArray:push({ id = 21, quality = 8, sub_count = 5, sub_type = 3, tppe_value = 36000, describe_title = "Thuộc tính tăng：360%"})
return mapArray
