local mapArray = MEMapArray:new()
mapArray:push({ id = 1, vip_level = 0, benefit_code = 2000, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 3thứ", show = 1})
mapArray:push({ id = 2, vip_level = 0, benefit_code = 2060, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 20thứ", show = 1})
mapArray:push({ id = 3, vip_level = 0, benefit_code = 2014, benefit_value = 10, benefit_percent = 0, desc ="kỹ năng đốt hạn 10", show = 1})
mapArray:push({ id = 4, vip_level = 0, benefit_code = 5000, benefit_value = 0, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 0thứ", show = 1})
mapArray:push({ id = 5, vip_level = 0, benefit_code = 3000, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 5thứ", show = 1})
mapArray:push({ id = 6, vip_level = 0, benefit_code = 6000, benefit_value = 30, benefit_percent = 0, desc ="bạn tốt dung lượng 30một", show = 1})
mapArray:push({ id = 7, vip_level = 0, benefit_code = 7001, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày bang phái kết bái 1thứ", show = 1})
mapArray:push({ id = 8, vip_level = 0, benefit_code = 7000, benefit_value = 1, benefit_percent = 0, desc ="bang phái gặp lại hận vãn mở ra", show = 1})
mapArray:push({ id = 9, vip_level = 0, benefit_code = 4007, benefit_value = 1, benefit_percent = 0, desc ="Nhạn Môn Quan nặng đưa trạm kiểm soát số lần 1thứ", show = 1})
mapArray:push({ id = 10, vip_level = 1, benefit_code = 2001, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 1thứ", show = 1})
mapArray:push({ id = 11, vip_level = 1, benefit_code = 2004, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 3thứ", show = 1})
mapArray:push({ id = 12, vip_level = 1, benefit_code = 2050, benefit_value = 3, benefit_percent = 0, desc ="huyết chiến mỗi ngày cổ vũ đoàn đội số lần hạn mức cao nhất vi 3", show = 1})
mapArray:push({ id = 13, vip_level = 1, benefit_code = 2020, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục trạm kiểm soát khiêu chiến số lần 1thứ", show = 1})
mapArray:push({ id = 14, vip_level = 1, benefit_code = 2000, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 5thứ", show = 1})
mapArray:push({ id = 15, vip_level = 1, benefit_code = 2010, benefit_value = 25, benefit_percent = 0, desc ="trạm kiểm soát thể lực hạn mức cao nhất giá trị tăng tới 25", show = 1})
mapArray:push({ id = 16, vip_level = 1, benefit_code = 2060, benefit_value = 50, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 50thứ", show = 1})
mapArray:push({ id = 17, vip_level = 1, benefit_code = 5000, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 20thứ", show = 1})
mapArray:push({ id = 18, vip_level = 1, benefit_code = 3000, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 10thứ", show = 1})
mapArray:push({ id = 19, vip_level = 1, benefit_code = 7000, benefit_value = 2, benefit_percent = 0, desc ="bang phái kết nghĩa kim lan mở ra", show = 1})
mapArray:push({ id = 20, vip_level = 2, benefit_code = 2020, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục trạm kiểm soát khiêu chiến số lần 2thứ", show = 1})
mapArray:push({ id = 21, vip_level = 2, benefit_code = 2050, benefit_value = 4, benefit_percent = 0, desc ="huyết chiến mỗi ngày cổ vũ đoàn đội số lần hạn mức cao nhất vi 4", show = 1})
mapArray:push({ id = 22, vip_level = 2, benefit_code = 2004, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 5thứ", show = 1})
mapArray:push({ id = 23, vip_level = 2, benefit_code = 2000, benefit_value = 8, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 8thứ", show = 1})
mapArray:push({ id = 24, vip_level = 2, benefit_code = 2002, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 1thứ", show = 1})
mapArray:push({ id = 25, vip_level = 2, benefit_code = 2001, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 1thứ", show = 1})
mapArray:push({ id = 26, vip_level = 1, benefit_code = 4001, benefit_value = 1, benefit_percent = 0, desc ="trang bị nhất kiện cường hóa mở ra", show = 1})
mapArray:push({ id = 27, vip_level = 2, benefit_code = 2060, benefit_value = 60, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 60thứ", show = 1})
mapArray:push({ id = 28, vip_level = 2, benefit_code = 3000, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 15thứ", show = 1})
mapArray:push({ id = 29, vip_level = 0, benefit_code = 4008, benefit_value = 0, benefit_percent = 0, desc ="mở ra nhất kiện tập được công năng", show = 1})
mapArray:push({ id = 30, vip_level = 3, benefit_code = 7001, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày bang phái kết bái 2thứ", show = 1})
mapArray:push({ id = 31, vip_level = 3, benefit_code = 4005, benefit_value = 0, benefit_percent = 0.1, desc ="Nhạn Môn Quan thêm vào tăng 10%thuộc tính đề thăng", show = 1})
mapArray:push({ id = 32, vip_level = 3, benefit_code = 2000, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 10thứ", show = 1})
mapArray:push({ id = 33, vip_level = 3, benefit_code = 2020, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục trạm kiểm soát khiêu chiến số lần 3thứ", show = 1})
mapArray:push({ id = 34, vip_level = 3, benefit_code = 2050, benefit_value = 5, benefit_percent = 0, desc ="huyết chiến mỗi ngày cổ vũ đoàn đội số lần hạn mức cao nhất vi 5", show = 1})
mapArray:push({ id = 35, vip_level = 3, benefit_code = 2001, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 1thứ", show = 1})
mapArray:push({ id = 36, vip_level = 3, benefit_code = 2004, benefit_value = 8, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 8thứ", show = 1})
mapArray:push({ id = 37, vip_level = 3, benefit_code = 2060, benefit_value = 70, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 70thứ", show = 1})
mapArray:push({ id = 38, vip_level = 3, benefit_code = 3000, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 20thứ", show = 1})
mapArray:push({ id = 39, vip_level = 3, benefit_code = 8000, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày nhưng cướp mỏ số lần 3thứ", show = 1})
mapArray:push({ id = 40, vip_level = 3, benefit_code = 8100, benefit_value = 0, benefit_percent = 0, desc ="mở ra nhất kiện đổ thạch công năng", show = 1})
mapArray:push({ id = 41, vip_level = 4, benefit_code = 2000, benefit_value = 11, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 11thứ", show = 1})
mapArray:push({ id = 42, vip_level = 4, benefit_code = 2020, benefit_value = 4, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục trạm kiểm soát khiêu chiến số lần 4thứ", show = 1})
mapArray:push({ id = 43, vip_level = 4, benefit_code = 2002, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 2thứ", show = 1})
mapArray:push({ id = 44, vip_level = 4, benefit_code = 2004, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 10thứ", show = 1})
mapArray:push({ id = 45, vip_level = 4, benefit_code = 2050, benefit_value = 6, benefit_percent = 0, desc ="huyết chiến mỗi ngày cổ vũ đoàn đội số lần hạn mức cao nhất vi 6", show = 1})
mapArray:push({ id = 46, vip_level = 4, benefit_code = 2001, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 2thứ", show = 1})
mapArray:push({ id = 47, vip_level = 4, benefit_code = 2060, benefit_value = 80, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 80thứ", show = 1})
mapArray:push({ id = 48, vip_level = 4, benefit_code = 3000, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 30thứ", show = 1})
mapArray:push({ id = 49, vip_level = 4, benefit_code = 4009, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày tăng kỳ nguyện số lần 1thứ", show = 1})
mapArray:push({ id = 50, vip_level = 5, benefit_code = 7001, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày bang phái kết bái 3thứ", show = 1})
mapArray:push({ id = 51, vip_level = 5, benefit_code = 4003, benefit_value = 0, benefit_percent = 0, desc ="thủ tiêu quần hào phổ làm lạnh thời gian", show = 1})
mapArray:push({ id = 52, vip_level = 5, benefit_code = 2020, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục trạm kiểm soát khiêu chiến số lần 5thứ", show = 1})
mapArray:push({ id = 53, vip_level = 5, benefit_code = 2000, benefit_value = 12, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 12thứ", show = 1})
mapArray:push({ id = 54, vip_level = 5, benefit_code = 2001, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 3thứ", show = 1})
mapArray:push({ id = 55, vip_level = 5, benefit_code = 2050, benefit_value = 7, benefit_percent = 0, desc ="huyết chiến mỗi ngày cổ vũ đoàn đội số lần hạn mức cao nhất vi 7", show = 1})
mapArray:push({ id = 56, vip_level = 5, benefit_code = 2004, benefit_value = 11, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 11thứ", show = 1})
mapArray:push({ id = 57, vip_level = 5, benefit_code = 2060, benefit_value = 90, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 90thứ", show = 1})
mapArray:push({ id = 58, vip_level = 7, benefit_code = 4000, benefit_value = 1, benefit_percent = 0, desc ="võ học nhất kiện chăm học khổ luyện mở ra", show = 1})
mapArray:push({ id = 59, vip_level = 5, benefit_code = 5000, benefit_value = 100, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 100thứ", show = 1})
mapArray:push({ id = 60, vip_level = 5, benefit_code = 3000, benefit_value = 40, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 40thứ", show = 1})
mapArray:push({ id = 61, vip_level = 5, benefit_code = 6000, benefit_value = 50, benefit_percent = 0, desc ="bạn tốt dung lượng 50một", show = 1})
mapArray:push({ id = 62, vip_level = 6, benefit_code = 7000, benefit_value = 3, benefit_percent = 0, desc ="bang phái cùng cam cộng tử mở ra", show = 1})
mapArray:push({ id = 63, vip_level = 6, benefit_code = 2004, benefit_value = 12, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 12thứ", show = 1})
mapArray:push({ id = 64, vip_level = 5, benefit_code = 4004, benefit_value = 0, benefit_percent = 0, desc ="tăng áp phiêu ra roi thúc ngựa công năng", show = 1})
mapArray:push({ id = 65, vip_level = 6, benefit_code = 2010, benefit_value = 30, benefit_percent = 0, desc ="trạm kiểm soát thể lực hạn mức cao nhất giá trị tăng tới 30", show = 1})
mapArray:push({ id = 66, vip_level = 6, benefit_code = 2000, benefit_value = 13, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 13thứ", show = 1})
mapArray:push({ id = 67, vip_level = 6, benefit_code = 2020, benefit_value = 6, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục trạm kiểm soát khiêu chiến số lần 6thứ", show = 1})
mapArray:push({ id = 68, vip_level = 6, benefit_code = 2001, benefit_value = 4, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 4thứ", show = 1})
mapArray:push({ id = 69, vip_level = 6, benefit_code = 2060, benefit_value = 100, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 100thứ", show = 1})
mapArray:push({ id = 70, vip_level = 6, benefit_code = 3000, benefit_value = 50, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 50thứ", show = 1})
mapArray:push({ id = 71, vip_level = 6, benefit_code = 4007, benefit_value = 2, benefit_percent = 0, desc ="Nhạn Môn Quan nặng đưa trạm kiểm soát số lần 2thứ", show = 1})
mapArray:push({ id = 72, vip_level = 6, benefit_code = 8000, benefit_value = 4, benefit_percent = 0, desc ="mỗi ngày nhưng cướp mỏ số lần 4thứ", show = 1})
mapArray:push({ id = 73, vip_level = 7, benefit_code = 2004, benefit_value = 13, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 13thứ", show = 1})
mapArray:push({ id = 74, vip_level = 7, benefit_code = 4006, benefit_value = 0, benefit_percent = 0.2, desc ="vô lượng sơn chân khí thu hoạch thêm vào tăng 20%", show = 1})
mapArray:push({ id = 75, vip_level = 7, benefit_code = 2000, benefit_value = 14, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 14thứ", show = 1})
mapArray:push({ id = 76, vip_level = 7, benefit_code = 2020, benefit_value = 7, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục trạm kiểm soát khiêu chiến số lần 7thứ", show = 1})
mapArray:push({ id = 77, vip_level = 7, benefit_code = 2001, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 5thứ", show = 1})
mapArray:push({ id = 78, vip_level = 7, benefit_code = 2050, benefit_value = 8, benefit_percent = 0, desc ="huyết chiến mỗi ngày cổ vũ đoàn đội số lần hạn mức cao nhất vi 8", show = 1})
mapArray:push({ id = 79, vip_level = 7, benefit_code = 2014, benefit_value = 20, benefit_percent = 0, desc ="kỹ năng đốt hạn 20", show = 1})
mapArray:push({ id = 80, vip_level = 7, benefit_code = 2060, benefit_value = 110, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 110thứ", show = 1})
mapArray:push({ id = 81, vip_level = 7, benefit_code = 3000, benefit_value = 60, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 60thứ", show = 1})
mapArray:push({ id = 82, vip_level = 8, benefit_code = 2002, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 3thứ", show = 1})
mapArray:push({ id = 83, vip_level = 8, benefit_code = 2001, benefit_value = 6, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 6thứ", show = 1})
mapArray:push({ id = 84, vip_level = 8, benefit_code = 2004, benefit_value = 14, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 14thứ", show = 1})
mapArray:push({ id = 85, vip_level = 8, benefit_code = 2000, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 15thứ", show = 1})
mapArray:push({ id = 86, vip_level = 8, benefit_code = 2060, benefit_value = 120, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 120thứ", show = 1})
mapArray:push({ id = 87, vip_level = 8, benefit_code = 3000, benefit_value = 70, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 70thứ", show = 1})
mapArray:push({ id = 88, vip_level = 9, benefit_code = 2004, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 15thứ", show = 1})
mapArray:push({ id = 89, vip_level = 9, benefit_code = 2002, benefit_value = 4, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 4thứ", show = 1})
mapArray:push({ id = 90, vip_level = 9, benefit_code = 2001, benefit_value = 7, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 7thứ", show = 1})
mapArray:push({ id = 91, vip_level = 9, benefit_code = 2050, benefit_value = 9, benefit_percent = 0, desc ="huyết chiến mỗi ngày cổ vũ đoàn đội số lần hạn mức cao nhất vi 9", show = 1})
mapArray:push({ id = 92, vip_level = 9, benefit_code = 2000, benefit_value = 16, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 16thứ", show = 1})
mapArray:push({ id = 93, vip_level = 9, benefit_code = 2060, benefit_value = 130, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 130thứ", show = 1})
mapArray:push({ id = 94, vip_level = 9, benefit_code = 3000, benefit_value = 80, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 80thứ", show = 1})
mapArray:push({ id = 95, vip_level = 9, benefit_code = 8000, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày nhưng cướp mỏ số lần 5thứ", show = 1})
mapArray:push({ id = 96, vip_level = 10, benefit_code = 2050, benefit_value = 10, benefit_percent = 0, desc ="huyết chiến mỗi ngày cổ vũ đoàn đội số lần hạn mức cao nhất vi 10", show = 1})
mapArray:push({ id = 97, vip_level = 10, benefit_code = 2002, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 5thứ", show = 1})
mapArray:push({ id = 98, vip_level = 10, benefit_code = 2001, benefit_value = 8, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 8thứ", show = 1})
mapArray:push({ id = 99, vip_level = 10, benefit_code = 2004, benefit_value = 16, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 16thứ", show = 1})
mapArray:push({ id = 100, vip_level = 10, benefit_code = 2000, benefit_value = 17, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 17thứ", show = 1})
mapArray:push({ id = 101, vip_level = 10, benefit_code = 2060, benefit_value = 140, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 140thứ", show = 1})
mapArray:push({ id = 102, vip_level = 10, benefit_code = 5000, benefit_value = 200, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 200thứ", show = 1})
mapArray:push({ id = 103, vip_level = 10, benefit_code = 3000, benefit_value = 100, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 100thứ", show = 1})
mapArray:push({ id = 104, vip_level = 11, benefit_code = 2004, benefit_value = 17, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 17thứ", show = 1})
mapArray:push({ id = 105, vip_level = 11, benefit_code = 2002, benefit_value = 6, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 6thứ", show = 1})
mapArray:push({ id = 106, vip_level = 11, benefit_code = 2001, benefit_value = 9, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 9thứ", show = 1})
mapArray:push({ id = 107, vip_level = 11, benefit_code = 2000, benefit_value = 18, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 18thứ", show = 1})
mapArray:push({ id = 108, vip_level = 11, benefit_code = 2060, benefit_value = 150, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 150thứ", show = 1})
mapArray:push({ id = 109, vip_level = 11, benefit_code = 3000, benefit_value = 120, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 120thứ", show = 1})
mapArray:push({ id = 110, vip_level = 12, benefit_code = 2002, benefit_value = 7, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 7thứ", show = 1})
mapArray:push({ id = 111, vip_level = 12, benefit_code = 2001, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày nhưng mua quần hào phổ khiêu chiến số lần 10thứ", show = 1})
mapArray:push({ id = 112, vip_level = 12, benefit_code = 2004, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 20thứ", show = 1})
mapArray:push({ id = 113, vip_level = 12, benefit_code = 2000, benefit_value = 19, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 19thứ", show = 1})
mapArray:push({ id = 114, vip_level = 12, benefit_code = 2060, benefit_value = 160, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 160thứ", show = 1})
mapArray:push({ id = 115, vip_level = 12, benefit_code = 3000, benefit_value = 140, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 140thứ", show = 1})
mapArray:push({ id = 116, vip_level = 13, benefit_code = 2002, benefit_value = 8, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 8thứ", show = 1})
mapArray:push({ id = 117, vip_level = 13, benefit_code = 2000, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 20thứ", show = 1})
mapArray:push({ id = 118, vip_level = 13, benefit_code = 2060, benefit_value = 170, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 170thứ", show = 1})
mapArray:push({ id = 119, vip_level = 13, benefit_code = 3000, benefit_value = 160, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 160thứ", show = 1})
mapArray:push({ id = 120, vip_level = 14, benefit_code = 2002, benefit_value = 9, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 9thứ", show = 1})
mapArray:push({ id = 121, vip_level = 14, benefit_code = 2000, benefit_value = 21, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 21thứ", show = 1})
mapArray:push({ id = 122, vip_level = 14, benefit_code = 2060, benefit_value = 180, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 180thứ", show = 1})
mapArray:push({ id = 123, vip_level = 14, benefit_code = 3000, benefit_value = 180, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 180thứ", show = 1})
mapArray:push({ id = 124, vip_level = 15, benefit_code = 2002, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 10thứ", show = 1})
mapArray:push({ id = 125, vip_level = 15, benefit_code = 2004, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 30thứ", show = 1})
mapArray:push({ id = 126, vip_level = 15, benefit_code = 2000, benefit_value = 22, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 22thứ", show = 1})
mapArray:push({ id = 127, vip_level = 15, benefit_code = 2060, benefit_value = 200, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 200thứ", show = 1})
mapArray:push({ id = 128, vip_level = 15, benefit_code = 3000, benefit_value = 200, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 200thứ", show = 1})
mapArray:push({ id = 129, vip_level = 5, benefit_code = 9000, benefit_value = 1, benefit_percent = 0, desc ="mở ra mau lẹ càn quét công năng", show = 1})
mapArray:push({ id = 130, vip_level = 0, benefit_code = 5001, benefit_value = 0, benefit_percent = 0, desc ="mỗi ngày miễn phí nhảy qua phục nói chuyện phiếm số lần 0thứ", show = 1})
mapArray:push({ id = 131, vip_level = 8, benefit_code = 5001, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày miễn phí nhảy qua phục nói chuyện phiếm số lần 5thứ", show = 1})
mapArray:push({ id = 132, vip_level = 10, benefit_code = 5001, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày miễn phí nhảy qua phục nói chuyện phiếm số lần 10thứ", show = 1})
mapArray:push({ id = 133, vip_level = 15, benefit_code = 5001, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày miễn phí nhảy qua phục nói chuyện phiếm số lần 20thứ", show = 1})
mapArray:push({ id = 134, vip_level = 0, benefit_code = 2005, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 2thứ", show = 1})
mapArray:push({ id = 135, vip_level = 1, benefit_code = 2005, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 3thứ", show = 1})
mapArray:push({ id = 136, vip_level = 2, benefit_code = 2005, benefit_value = 4, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 4thứ", show = 1})
mapArray:push({ id = 137, vip_level = 3, benefit_code = 2005, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 5thứ", show = 1})
mapArray:push({ id = 138, vip_level = 4, benefit_code = 2005, benefit_value = 6, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 6thứ", show = 1})
mapArray:push({ id = 139, vip_level = 5, benefit_code = 2005, benefit_value = 7, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 7thứ", show = 1})
mapArray:push({ id = 140, vip_level = 6, benefit_code = 2005, benefit_value = 8, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 8thứ", show = 1})
mapArray:push({ id = 141, vip_level = 7, benefit_code = 2005, benefit_value = 9, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 9thứ", show = 1})
mapArray:push({ id = 142, vip_level = 8, benefit_code = 2005, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 10thứ", show = 1})
mapArray:push({ id = 143, vip_level = 9, benefit_code = 2005, benefit_value = 11, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 11thứ", show = 1})
mapArray:push({ id = 144, vip_level = 10, benefit_code = 2005, benefit_value = 12, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 12thứ", show = 1})
mapArray:push({ id = 145, vip_level = 11, benefit_code = 2005, benefit_value = 13, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 13thứ", show = 1})
mapArray:push({ id = 146, vip_level = 12, benefit_code = 2005, benefit_value = 14, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 14thứ", show = 1})
mapArray:push({ id = 147, vip_level = 13, benefit_code = 2005, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 15thứ", show = 1})
mapArray:push({ id = 148, vip_level = 14, benefit_code = 2005, benefit_value = 16, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 16thứ", show = 1})
mapArray:push({ id = 149, vip_level = 15, benefit_code = 2005, benefit_value = 17, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 17thứ", show = 1})
mapArray:push({ id = 150, vip_level = 0, benefit_code = 2006, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 1thứ", show = 1})
mapArray:push({ id = 151, vip_level = 1, benefit_code = 2006, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 2thứ", show = 1})
mapArray:push({ id = 152, vip_level = 2, benefit_code = 2006, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 3thứ", show = 1})
mapArray:push({ id = 153, vip_level = 3, benefit_code = 2006, benefit_value = 4, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 4thứ", show = 1})
mapArray:push({ id = 154, vip_level = 4, benefit_code = 2006, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 5thứ", show = 1})
mapArray:push({ id = 155, vip_level = 5, benefit_code = 2006, benefit_value = 6, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 6thứ", show = 1})
mapArray:push({ id = 156, vip_level = 6, benefit_code = 2006, benefit_value = 7, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 7thứ", show = 1})
mapArray:push({ id = 157, vip_level = 7, benefit_code = 2006, benefit_value = 8, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 8thứ", show = 1})
mapArray:push({ id = 158, vip_level = 8, benefit_code = 2006, benefit_value = 9, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 9thứ", show = 1})
mapArray:push({ id = 159, vip_level = 9, benefit_code = 2006, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 10thứ", show = 1})
mapArray:push({ id = 160, vip_level = 10, benefit_code = 2006, benefit_value = 11, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 11thứ", show = 1})
mapArray:push({ id = 161, vip_level = 11, benefit_code = 2006, benefit_value = 12, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 12thứ", show = 1})
mapArray:push({ id = 162, vip_level = 12, benefit_code = 2006, benefit_value = 13, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 13thứ", show = 1})
mapArray:push({ id = 163, vip_level = 13, benefit_code = 2006, benefit_value = 14, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 14thứ", show = 1})
mapArray:push({ id = 164, vip_level = 14, benefit_code = 2006, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 15thứ", show = 1})
mapArray:push({ id = 165, vip_level = 15, benefit_code = 2006, benefit_value = 16, benefit_percent = 0, desc ="mỗi ngày mua luận bàn số lần 16thứ", show = 1})
mapArray:push({ id = 166, vip_level = 1, benefit_code = 2021, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục du lịch trạm kiểm soát khiêu chiến số lần 1thứ", show = 1})
mapArray:push({ id = 167, vip_level = 2, benefit_code = 2021, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục du lịch trạm kiểm soát khiêu chiến số lần 2thứ", show = 1})
mapArray:push({ id = 168, vip_level = 3, benefit_code = 2021, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục du lịch trạm kiểm soát khiêu chiến số lần 3thứ", show = 1})
mapArray:push({ id = 169, vip_level = 4, benefit_code = 2021, benefit_value = 4, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục du lịch trạm kiểm soát khiêu chiến số lần 4thứ", show = 1})
mapArray:push({ id = 170, vip_level = 5, benefit_code = 2021, benefit_value = 5, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục du lịch trạm kiểm soát khiêu chiến số lần 5thứ", show = 1})
mapArray:push({ id = 171, vip_level = 6, benefit_code = 2021, benefit_value = 6, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục du lịch trạm kiểm soát khiêu chiến số lần 6thứ", show = 1})
mapArray:push({ id = 172, vip_level = 7, benefit_code = 2021, benefit_value = 7, benefit_percent = 0, desc ="mỗi ngày nhưng khôi phục du lịch trạm kiểm soát khiêu chiến số lần 7thứ", show = 1})
mapArray:push({ id = 173, vip_level = 16, benefit_code = 2000, benefit_value = 23, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 23thứ", show = 1})
mapArray:push({ id = 174, vip_level = 17, benefit_code = 2000, benefit_value = 24, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 24thứ", show = 1})
mapArray:push({ id = 175, vip_level = 18, benefit_code = 2000, benefit_value = 25, benefit_percent = 0, desc ="mỗi ngày mua trạm kiểm soát thể lực 25thứ", show = 1})
mapArray:push({ id = 176, vip_level = 16, benefit_code = 2002, benefit_value = 12, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 12thứ", show = 1})
mapArray:push({ id = 177, vip_level = 17, benefit_code = 2002, benefit_value = 14, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 14thứ", show = 1})
mapArray:push({ id = 178, vip_level = 18, benefit_code = 2002, benefit_value = 16, benefit_percent = 0, desc ="mỗi ngày khôi phục vô lượng sơn số lần 16thứ", show = 1})
mapArray:push({ id = 179, vip_level = 16, benefit_code = 2004, benefit_value = 32, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 32thứ", show = 1})
mapArray:push({ id = 180, vip_level = 17, benefit_code = 2004, benefit_value = 34, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 34thứ", show = 1})
mapArray:push({ id = 181, vip_level = 18, benefit_code = 2004, benefit_value = 36, benefit_percent = 0, desc ="mỗi ngày nhưng mua kỹ năng điểm 36thứ", show = 1})
mapArray:push({ id = 182, vip_level = 16, benefit_code = 2005, benefit_value = 18, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 18thứ", show = 1})
mapArray:push({ id = 183, vip_level = 17, benefit_code = 2005, benefit_value = 19, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 19thứ", show = 1})
mapArray:push({ id = 184, vip_level = 18, benefit_code = 2005, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày mua du lịch Bánh bao 20thứ", show = 1})
mapArray:push({ id = 185, vip_level = 16, benefit_code = 2060, benefit_value = 220, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 220thứ", show = 1})
mapArray:push({ id = 186, vip_level = 17, benefit_code = 2060, benefit_value = 240, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 240thứ", show = 1})
mapArray:push({ id = 187, vip_level = 18, benefit_code = 2060, benefit_value = 260, benefit_percent = 0, desc ="mỗi ngày miễn phí càn quét số lần 260thứ", show = 1})
mapArray:push({ id = 188, vip_level = 16, benefit_code = 3000, benefit_value = 220, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 220thứ", show = 1})
mapArray:push({ id = 189, vip_level = 17, benefit_code = 3000, benefit_value = 240, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 240thứ", show = 1})
mapArray:push({ id = 190, vip_level = 18, benefit_code = 3000, benefit_value = 260, benefit_percent = 0, desc ="mỗi ngày nhưng mua tiền đồng số lần 260thứ", show = 1})
mapArray:push({ id = 191, vip_level = 16, benefit_code = 5001, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày miễn phí nhảy qua phục nói chuyện phiếm số lần 30thứ", show = 1})
mapArray:push({ id = 192, vip_level = 17, benefit_code = 5001, benefit_value = 50, benefit_percent = 0, desc ="mỗi ngày miễn phí nhảy qua phục nói chuyện phiếm số lần 50thứ", show = 1})
mapArray:push({ id = 193, vip_level = 18, benefit_code = 5001, benefit_value = 75, benefit_percent = 0, desc ="mỗi ngày miễn phí nhảy qua phục nói chuyện phiếm số lần 75thứ", show = 1})
mapArray:push({ id = 194, vip_level = 2, benefit_code = 5000, benefit_value = 40, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 40thứ", show = 1})
mapArray:push({ id = 195, vip_level = 3, benefit_code = 5000, benefit_value = 60, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 60thứ", show = 1})
mapArray:push({ id = 196, vip_level = 4, benefit_code = 5000, benefit_value = 80, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 80thứ", show = 1})
mapArray:push({ id = 197, vip_level = 6, benefit_code = 5000, benefit_value = 120, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 120thứ", show = 1})
mapArray:push({ id = 198, vip_level = 7, benefit_code = 5000, benefit_value = 140, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 140thứ", show = 1})
mapArray:push({ id = 199, vip_level = 8, benefit_code = 5000, benefit_value = 160, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 160thứ", show = 1})
mapArray:push({ id = 200, vip_level = 9, benefit_code = 5000, benefit_value = 180, benefit_percent = 0, desc ="mỗi ngày miễn phí nói chuyện phiếm số lần 180thứ", show = 1})
mapArray:push({ id = 201, vip_level = 16, benefit_code = 8200, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày VIP16miễn phí tuyên ngôn 2thứ", show = 1})
mapArray:push({ id = 202, vip_level = 17, benefit_code = 8200, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày VIP17miễn phí tuyên ngôn 2thứ", show = 1})
mapArray:push({ id = 203, vip_level = 18, benefit_code = 8200, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày VIP18miễn phí tuyên ngôn 2thứ", show = 1})
mapArray:push({ id = 204, vip_level = 0, benefit_code = 5002, benefit_value = 25, benefit_percent = 0, desc ="mỗi ngày VIP0nhưng mua luận kiếm ngọn núi số lần 25thứ", show = 1})
mapArray:push({ id = 205, vip_level = 0, benefit_code = 8101, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng đổ thạch tinh công 20thứ", show = 1})
mapArray:push({ id = 206, vip_level = 0, benefit_code = 8102, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng đổ thạch điêu mài 20thứ", show = 1})
mapArray:push({ id = 207, vip_level = 0, benefit_code = 8300, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông chiêu mộ 20thứ", show = 1})
mapArray:push({ id = 208, vip_level = 0, benefit_code = 8301, benefit_value = 19, benefit_percent = 0, desc ="mỗi ngày nhưng trung cấp chiêu mộ 20thứ", show = 1})
mapArray:push({ id = 209, vip_level = 0, benefit_code = 8302, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng cao cấp chiêu mộ 30thứ", show = 1})
mapArray:push({ id = 210, vip_level = 0, benefit_code = 8401, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 211, vip_level = 0, benefit_code = 8402, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng quần hào phổ thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 212, vip_level = 0, benefit_code = 8403, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng hi hữu thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 213, vip_level = 0, benefit_code = 8404, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng trân bảo thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 214, vip_level = 0, benefit_code = 8405, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng hiệp khách thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 215, vip_level = 0, benefit_code = 8406, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 216, vip_level = 0, benefit_code = 8407, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái tinh phẩm thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 217, vip_level = 0, benefit_code = 8408, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái thuật lại thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 218, vip_level = 0, benefit_code = 8409, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nhảy qua phục phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 219, vip_level = 0, benefit_code = 8410, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nhảy qua phục tinh phẩm thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 220, vip_level = 0, benefit_code = 8411, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông đỉnh thương điếm nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 221, vip_level = 0, benefit_code = 8412, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng tinh phẩm đỉnh thương điếm nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 222, vip_level = 5, benefit_code = 8101, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng đổ thạch tinh công 20thứ", show = 1})
mapArray:push({ id = 223, vip_level = 5, benefit_code = 8102, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng đổ thạch điêu mài 20thứ", show = 1})
mapArray:push({ id = 224, vip_level = 5, benefit_code = 8300, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông chiêu mộ 15thứ", show = 1})
mapArray:push({ id = 225, vip_level = 5, benefit_code = 8301, benefit_value = 19, benefit_percent = 0, desc ="mỗi ngày nhưng trung cấp chiêu mộ 19thứ", show = 1})
mapArray:push({ id = 226, vip_level = 5, benefit_code = 8302, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng cao cấp chiêu mộ 20thứ", show = 1})
mapArray:push({ id = 227, vip_level = 5, benefit_code = 8401, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 228, vip_level = 5, benefit_code = 8402, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng quần hào phổ thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 229, vip_level = 5, benefit_code = 8403, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng hi hữu thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 230, vip_level = 5, benefit_code = 8404, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng trân bảo thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 231, vip_level = 5, benefit_code = 8405, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng hiệp khách thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 232, vip_level = 5, benefit_code = 8406, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 233, vip_level = 5, benefit_code = 8407, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái tinh phẩm thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 234, vip_level = 5, benefit_code = 8408, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái thuật lại thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 235, vip_level = 5, benefit_code = 8409, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nhảy qua phục phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 236, vip_level = 5, benefit_code = 8410, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nhảy qua phục tinh phẩm thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 237, vip_level = 5, benefit_code = 8411, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông đỉnh thương điếm nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 238, vip_level = 5, benefit_code = 8412, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng tinh phẩm đỉnh thương điếm nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 239, vip_level = 10, benefit_code = 8101, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng đổ thạch tinh công 20thứ", show = 1})
mapArray:push({ id = 240, vip_level = 10, benefit_code = 8102, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng đổ thạch điêu mài 20thứ", show = 1})
mapArray:push({ id = 241, vip_level = 10, benefit_code = 8300, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông chiêu mộ 15thứ", show = 1})
mapArray:push({ id = 242, vip_level = 10, benefit_code = 8301, benefit_value = 19, benefit_percent = 0, desc ="mỗi ngày nhưng trung cấp chiêu mộ 19thứ", show = 1})
mapArray:push({ id = 243, vip_level = 10, benefit_code = 8302, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng cao cấp chiêu mộ 20thứ", show = 1})
mapArray:push({ id = 244, vip_level = 10, benefit_code = 8401, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 245, vip_level = 10, benefit_code = 8402, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng quần hào phổ thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 246, vip_level = 10, benefit_code = 8403, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng hi hữu thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 247, vip_level = 10, benefit_code = 8404, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng trân bảo thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 248, vip_level = 10, benefit_code = 8405, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng hiệp khách thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 249, vip_level = 10, benefit_code = 8406, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 250, vip_level = 10, benefit_code = 8407, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái tinh phẩm thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 251, vip_level = 10, benefit_code = 8408, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái thuật lại thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 252, vip_level = 10, benefit_code = 8409, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nhảy qua phục phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 253, vip_level = 10, benefit_code = 8410, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nhảy qua phục tinh phẩm thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 254, vip_level = 10, benefit_code = 8411, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông đỉnh thương điếm nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 255, vip_level = 10, benefit_code = 8412, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng tinh phẩm đỉnh thương điếm nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 256, vip_level = 15, benefit_code = 8101, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng đổ thạch tinh công 20thứ", show = 1})
mapArray:push({ id = 257, vip_level = 15, benefit_code = 8102, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng đổ thạch điêu mài 20thứ", show = 1})
mapArray:push({ id = 258, vip_level = 15, benefit_code = 8300, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông chiêu mộ 15thứ", show = 1})
mapArray:push({ id = 259, vip_level = 15, benefit_code = 8301, benefit_value = 19, benefit_percent = 0, desc ="mỗi ngày nhưng trung cấp chiêu mộ 19thứ", show = 1})
mapArray:push({ id = 260, vip_level = 15, benefit_code = 8302, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng cao cấp chiêu mộ 20thứ", show = 1})
mapArray:push({ id = 261, vip_level = 15, benefit_code = 8401, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 262, vip_level = 15, benefit_code = 8402, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng quần hào phổ thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 263, vip_level = 15, benefit_code = 8403, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng hi hữu thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 264, vip_level = 15, benefit_code = 8404, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng trân bảo thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 265, vip_level = 15, benefit_code = 8405, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng hiệp khách thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 266, vip_level = 15, benefit_code = 8406, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 267, vip_level = 15, benefit_code = 8407, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái tinh phẩm thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 268, vip_level = 15, benefit_code = 8408, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày giúp đỡ phái thuật lại thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 269, vip_level = 15, benefit_code = 8409, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nhảy qua phục phổ thông thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 270, vip_level = 15, benefit_code = 8410, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nhảy qua phục tinh phẩm thương thành nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 271, vip_level = 15, benefit_code = 8411, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng phổ thông đỉnh thương điếm nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 272, vip_level = 15, benefit_code = 8412, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng tinh phẩm đỉnh thương điếm nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 273, vip_level = 0, benefit_code = 5003, benefit_value = 15, benefit_percent = 0, desc ="mỗi ngày VIP0nhưng mua vô lượng sơn (ác mộng ）số lần 15thứ", show = 1})
mapArray:push({ id = 274, vip_level = 0, benefit_code = 8413, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày phổ thông chiêu mộ đạo cụ 20thứ", show = 1})
mapArray:push({ id = 275, vip_level = 0, benefit_code = 8414, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày trung cấp chiêu mộ đạo cụ 20thứ", show = 1})
mapArray:push({ id = 276, vip_level = 0, benefit_code = 8415, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày cao cấp chiêu mộ đạo cụ 20thứ", show = 1})
mapArray:push({ id = 277, vip_level = 3, benefit_code = 8416, benefit_value = 1, benefit_percent = 0, desc ="nhất kiện uỷ trị mở ra", show = 1})
mapArray:push({ id = 278, vip_level = 0, benefit_code = 9001, benefit_value = 1, benefit_percent = 0, desc ="đông doanh đảo thắng lợi hậu ，khả dĩ trở mình một lần bài tử", show = 1})
mapArray:push({ id = 279, vip_level = 4, benefit_code = 9001, benefit_value = 2, benefit_percent = 0, desc ="đông doanh đảo thắng lợi hậu ，khả dĩ trở mình hai lần bài tử", show = 1})
mapArray:push({ id = 280, vip_level = 0, benefit_code = 8450, benefit_value = 10, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 10thứ", show = 1})
mapArray:push({ id = 281, vip_level = 1, benefit_code = 8450, benefit_value = 12, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 12thứ", show = 1})
mapArray:push({ id = 282, vip_level = 2, benefit_code = 8450, benefit_value = 14, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 14thứ", show = 1})
mapArray:push({ id = 283, vip_level = 3, benefit_code = 8450, benefit_value = 16, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 16thứ", show = 1})
mapArray:push({ id = 284, vip_level = 4, benefit_code = 8450, benefit_value = 18, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 18thứ", show = 1})
mapArray:push({ id = 285, vip_level = 5, benefit_code = 8450, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 20thứ", show = 1})
mapArray:push({ id = 286, vip_level = 6, benefit_code = 8450, benefit_value = 22, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 22thứ", show = 1})
mapArray:push({ id = 287, vip_level = 7, benefit_code = 8450, benefit_value = 24, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 24thứ", show = 1})
mapArray:push({ id = 288, vip_level = 8, benefit_code = 8450, benefit_value = 26, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 26thứ", show = 1})
mapArray:push({ id = 289, vip_level = 9, benefit_code = 8450, benefit_value = 28, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 28thứ", show = 1})
mapArray:push({ id = 290, vip_level = 10, benefit_code = 8450, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 30thứ", show = 1})
mapArray:push({ id = 291, vip_level = 11, benefit_code = 8450, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 30thứ", show = 1})
mapArray:push({ id = 292, vip_level = 12, benefit_code = 8450, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 30thứ", show = 1})
mapArray:push({ id = 293, vip_level = 13, benefit_code = 8450, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 30thứ", show = 1})
mapArray:push({ id = 294, vip_level = 14, benefit_code = 8450, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 30thứ", show = 1})
mapArray:push({ id = 295, vip_level = 15, benefit_code = 8450, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua hiệp nghĩa giá trị 30thứ", show = 1})
mapArray:push({ id = 296, vip_level = 0, benefit_code = 8419, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng tịnh tâm trai nảy sinh cái mới 20thứ", show = 1})
mapArray:push({ id = 297, vip_level = 0, benefit_code = 8420, benefit_value = 8, benefit_percent = 0, desc ="mỗi ngày nhưng mua truy tung lệnh 8thứ", show = 1})
mapArray:push({ id = 298, vip_level = 0, benefit_code = 8888, benefit_value = 0, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 0thứ", show = 1})
mapArray:push({ id = 299, vip_level = 1, benefit_code = 8888, benefit_value = 0, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 0thứ", show = 1})
mapArray:push({ id = 300, vip_level = 2, benefit_code = 8888, benefit_value = 0, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 0thứ", show = 1})
mapArray:push({ id = 301, vip_level = 3, benefit_code = 8888, benefit_value = 0, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 0thứ", show = 1})
mapArray:push({ id = 302, vip_level = 4, benefit_code = 8888, benefit_value = 0, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 0thứ", show = 1})
mapArray:push({ id = 303, vip_level = 5, benefit_code = 8888, benefit_value = 0, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 0thứ", show = 1})
mapArray:push({ id = 304, vip_level = 6, benefit_code = 8888, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 1thứ", show = 1})
mapArray:push({ id = 305, vip_level = 7, benefit_code = 8888, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 1thứ", show = 1})
mapArray:push({ id = 306, vip_level = 8, benefit_code = 8888, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 1thứ", show = 1})
mapArray:push({ id = 307, vip_level = 9, benefit_code = 8888, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 1thứ", show = 1})
mapArray:push({ id = 308, vip_level = 10, benefit_code = 8888, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 1thứ", show = 1})
mapArray:push({ id = 309, vip_level = 11, benefit_code = 8888, benefit_value = 1, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 1thứ", show = 1})
mapArray:push({ id = 310, vip_level = 12, benefit_code = 8888, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 2thứ", show = 1})
mapArray:push({ id = 311, vip_level = 13, benefit_code = 8888, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 2thứ", show = 1})
mapArray:push({ id = 312, vip_level = 14, benefit_code = 8888, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 2thứ", show = 1})
mapArray:push({ id = 313, vip_level = 15, benefit_code = 8888, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 3thứ", show = 1})
mapArray:push({ id = 314, vip_level = 16, benefit_code = 8888, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 3thứ", show = 1})
mapArray:push({ id = 315, vip_level = 17, benefit_code = 8888, benefit_value = 3, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 3thứ", show = 1})
mapArray:push({ id = 316, vip_level = 18, benefit_code = 8888, benefit_value = 4, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới quý khách thương thành 4thứ", show = 1})
mapArray:push({ id = 317, vip_level = 0, benefit_code = 8421, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới Anh Hùng thương điếm 20thứ", show = 1})
mapArray:push({ id = 318, vip_level = 0, benefit_code = 8422, benefit_value = 2, benefit_percent = 0, desc ="mỗi ngày nhưng mua Anh Hùng thể lực 2thứ", show = 1})
mapArray:push({ id = 319, vip_level = 0, benefit_code = 8423, benefit_value = 30, benefit_percent = 0, desc ="mỗi ngày nhưng mua linh khí 30thứ", show = 1})
mapArray:push({ id = 320, vip_level = 0, benefit_code = 8424, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới tinh phách thương thành 20thứ", show = 1})
mapArray:push({ id = 321, vip_level = 0, benefit_code = 8426, benefit_value = 20, benefit_percent = 0, desc ="mỗi ngày nhưng nảy sinh cái mới phong vân các 20thứ", show = 1})
return mapArray
