local mapArray = MEMapArray:new()
mapArray:push({ id = 0, type = 0, kind = 0, icon = 0, desc = ""})
mapArray:push({ id = 1, type = 1, kind = 1, icon = 19, desc = "Có thể ở trong thương thành mua"})
mapArray:push({ id = 2, type = 1, kind = 2, icon = 19, desc = "Có thể ở quần hào trong thương thành mua"})
mapArray:push({ id = 3, type = 1, kind = 3, icon = 19, desc = "Có thể ở hi hữu trong thương thành mua"})
mapArray:push({ id = 4, type = 1, kind = 4, icon = 19, desc = "Có thể ở trân bảo trong thương thành mua"})
mapArray:push({ id = 5, type = 1, kind = 5, icon = 19, desc = "Có thể ở hiệp hồn trong thương thành mua"})
mapArray:push({ id = 6, type = 1, kind = 6, icon = 19, desc = "Có thể bang phái cửa hàng phổ thông mua"})
mapArray:push({ id = 7, type = 1, kind = 7, icon = 19, desc = "Có thể bang phái cửa hàng tinh phẩm mua"})
mapArray:push({ id = 8, type = 1, kind = 8, icon = 19, desc = "Có thể bang phái cửa hàng mua"})
mapArray:push({ id = 9, type = 1, kind = 9, icon = 19, desc = "Có thể ở vượt dùng thương thành Phổ thông mua"})
mapArray:push({ id = 10, type = 1, kind = 10, icon = 19, desc = "Có thể ở vượt dùng thương thành Tinh phẩm mua"})
mapArray:push({ id = 11, type = 1, kind = 11, icon = 19, desc = "Có thể ở đỉnh cao thương thành · phổ thông bên trong mua"})
mapArray:push({ id = 12, type = 1, kind = 12, icon = 19, desc = "Có thể ở đỉnh cao thương thành · tinh phẩm bên trong mua"})
mapArray:push({ id = 13, type = 3, kind = 0, icon = 10, desc = "Qua cửa Ma Ha nhai chỉ định cửa ải thu được"})
mapArray:push({ id = 14, type = 4, kind = 0, icon = 26, desc = "Thông qua Thần Nông quặng mỏ ngoạn pháp thu được"})
mapArray:push({ id = 15, type = 5, kind = 0, icon = 28, desc = "Thông qua du lịch ngoạn pháp thu được"})
mapArray:push({ id = 16, type = 6, kind = 0, icon = 11, desc = "Qua cửa Vô Lượng sơn chỉ định số tầng thu được"})
mapArray:push({ id = 17, type = 7, kind = 0, icon = 11, desc = "Qua cửa Vô Lượng sơn Bắc quật chỉ định số tầng thu được"})
mapArray:push({ id = 18, type = 8, kind = 0, icon = 35, desc = "Qua cửa xông trận chỉ định cửa ải thu được"})
mapArray:push({ id = 19, type = 9, kind = 0, icon = 30, desc = "Thông qua quán rượu ngoạn pháp thu được"})
mapArray:push({ id = 20, type = 1, kind = 50, icon = 19, desc = "Có thể ở gói quà trong thương thành mua"})
mapArray:push({ id = 21, type = 2, kind = 1001, icon = 1, desc = "Tông Sư thứ 1 Chương 1 Về"})
mapArray:push({ id = 22, type = 2, kind = 1002, icon = 1, desc = "Tông Sư thứ 1 Chương 2 Về"})
mapArray:push({ id = 23, type = 2, kind = 1003, icon = 1, desc = "Tông Sư thứ 1 Chương 3 Về"})
mapArray:push({ id = 24, type = 2, kind = 1004, icon = 1, desc = "Tông Sư thứ 2 Chương 1 Về"})
mapArray:push({ id = 25, type = 2, kind = 1005, icon = 1, desc = "Tông Sư thứ 2 Chương 2 Về"})
mapArray:push({ id = 26, type = 2, kind = 1006, icon = 1, desc = "Tông Sư thứ 2 Chương 3 Về"})
mapArray:push({ id = 27, type = 2, kind = 1007, icon = 1, desc = "Tông Sư thứ 3 Chương 1 Về"})
mapArray:push({ id = 28, type = 2, kind = 1008, icon = 1, desc = "Tông Sư thứ 3 Chương 2 Về"})
mapArray:push({ id = 29, type = 2, kind = 1009, icon = 1, desc = "Tông Sư thứ 3 Chương 3 Về"})
mapArray:push({ id = 30, type = 2, kind = 1010, icon = 1, desc = "Tông Sư thứ 4 Chương 1 Về"})
mapArray:push({ id = 31, type = 2, kind = 1011, icon = 1, desc = "Tông Sư thứ 4 Chương 2 Về"})
mapArray:push({ id = 32, type = 2, kind = 1012, icon = 1, desc = "Tông Sư thứ 4 Chương 3 Về"})
mapArray:push({ id = 33, type = 2, kind = 1013, icon = 1, desc = "Tông Sư thứ 5 Chương 1 Về"})
mapArray:push({ id = 34, type = 2, kind = 1014, icon = 1, desc = "Tông Sư thứ 5 Chương 2 Về"})
mapArray:push({ id = 35, type = 2, kind = 1015, icon = 1, desc = "Tông Sư thứ 5 Chương 3 Về"})
mapArray:push({ id = 36, type = 2, kind = 1016, icon = 1, desc = "Tông Sư thứ 6 Chương 1 Về"})
mapArray:push({ id = 37, type = 2, kind = 1017, icon = 1, desc = "Tông Sư thứ 6 Chương 2 Về"})
mapArray:push({ id = 38, type = 2, kind = 1018, icon = 1, desc = "Tông Sư thứ 6 Chương 3 Về"})
mapArray:push({ id = 39, type = 2, kind = 1019, icon = 1, desc = "Tông Sư thứ 7 Chương 1 Về"})
mapArray:push({ id = 40, type = 2, kind = 1020, icon = 1, desc = "Tông Sư thứ 7 Chương 2 Về"})
mapArray:push({ id = 41, type = 2, kind = 1021, icon = 1, desc = "Tông Sư thứ 7 Chương 3 Về"})
mapArray:push({ id = 42, type = 2, kind = 1022, icon = 1, desc = "Tông Sư thứ 8 Chương 1 Về"})
mapArray:push({ id = 43, type = 2, kind = 1023, icon = 1, desc = "Tông Sư thứ 8 Chương 2 Về"})
mapArray:push({ id = 44, type = 2, kind = 1024, icon = 1, desc = "Tông Sư thứ 8 Chương 3 Về"})
mapArray:push({ id = 45, type = 2, kind = 1025, icon = 1, desc = "Tông Sư thứ 9 Chương 1 Về"})
mapArray:push({ id = 46, type = 2, kind = 1026, icon = 1, desc = "Tông Sư thứ 9 Chương 2 Về"})
mapArray:push({ id = 47, type = 2, kind = 1027, icon = 1, desc = "Tông Sư thứ 9 Chương 3 Về"})
mapArray:push({ id = 48, type = 2, kind = 1028, icon = 1, desc = "Tông Sư thứ 10 Chương 1 Về"})
mapArray:push({ id = 49, type = 2, kind = 1029, icon = 1, desc = "Tông Sư thứ 10 Chương 2 Về"})
mapArray:push({ id = 50, type = 2, kind = 1030, icon = 1, desc = "Tông Sư thứ 10 Chương 3 Về"})
mapArray:push({ id = 51, type = 2, kind = 1031, icon = 1, desc = "Tông Sư thứ 11 Chương 1 Về"})
mapArray:push({ id = 52, type = 2, kind = 1032, icon = 1, desc = "Tông Sư thứ 11 Chương 2 Về"})
mapArray:push({ id = 53, type = 2, kind = 1033, icon = 1, desc = "Tông Sư thứ 11 Chương 3 Về"})
mapArray:push({ id = 54, type = 2, kind = 1034, icon = 1, desc = "Tông Sư thứ 12 Chương 1 Về"})
mapArray:push({ id = 55, type = 2, kind = 1035, icon = 1, desc = "Tông Sư thứ 12 Chương 2 Về"})
mapArray:push({ id = 56, type = 2, kind = 1036, icon = 1, desc = "Tông Sư thứ 12 Chương 3 Về"})
mapArray:push({ id = 57, type = 2, kind = 1037, icon = 1, desc = "Tông Sư thứ 13 Chương 1 Về"})
mapArray:push({ id = 58, type = 2, kind = 1038, icon = 1, desc = "Tông Sư thứ 13 Chương 2 Về"})
mapArray:push({ id = 59, type = 2, kind = 1039, icon = 1, desc = "Tông Sư thứ 13 Chương 3 Về"})
mapArray:push({ id = 60, type = 2, kind = 1040, icon = 1, desc = "Tông Sư thứ 14 Chương 1 Về"})
mapArray:push({ id = 61, type = 2, kind = 1041, icon = 1, desc = "Tông Sư thứ 14 Chương 2 Về"})
mapArray:push({ id = 62, type = 2, kind = 1042, icon = 1, desc = "Tông Sư thứ 14 Chương 3 Về"})
mapArray:push({ id = 63, type = 2, kind = 1043, icon = 1, desc = "Tông Sư thứ 15 Chương 1 Về"})
mapArray:push({ id = 64, type = 2, kind = 1044, icon = 1, desc = "Tông Sư thứ 15 Chương 2 Về"})
mapArray:push({ id = 65, type = 2, kind = 1045, icon = 1, desc = "Tông Sư thứ 15 Chương 3 Về"})
mapArray:push({ id = 66, type = 2, kind = 1046, icon = 1, desc = "Tông Sư thứ 16 Chương 1 Về"})
mapArray:push({ id = 67, type = 2, kind = 1047, icon = 1, desc = "Tông Sư thứ 16 Chương 2 Về"})
mapArray:push({ id = 68, type = 2, kind = 1048, icon = 1, desc = "Tông Sư thứ 16 Chương 3 Về"})
mapArray:push({ id = 69, type = 2, kind = 1049, icon = 1, desc = "Tông Sư thứ 17 Chương 1 Về"})
mapArray:push({ id = 70, type = 2, kind = 1050, icon = 1, desc = "Tông Sư thứ 17 Chương 2 Về"})
mapArray:push({ id = 71, type = 2, kind = 1051, icon = 1, desc = "Tông Sư thứ 17 Chương 3 Về"})
mapArray:push({ id = 72, type = 2, kind = 1052, icon = 1, desc = "Tông Sư thứ 18 Chương 1 Về"})
mapArray:push({ id = 73, type = 2, kind = 1053, icon = 1, desc = "Tông Sư thứ 18 Chương 2 Về"})
mapArray:push({ id = 74, type = 2, kind = 1054, icon = 1, desc = "Tông Sư thứ 18 Chương 3 Về"})
mapArray:push({ id = 75, type = 2, kind = 1055, icon = 1, desc = "Tông Sư thứ 19 Chương 1 Về"})
mapArray:push({ id = 76, type = 2, kind = 1056, icon = 1, desc = "Tông Sư thứ 19 Chương 2 Về"})
mapArray:push({ id = 77, type = 2, kind = 1057, icon = 1, desc = "Tông Sư thứ 19 Chương 3 Về"})
mapArray:push({ id = 78, type = 2, kind = 1058, icon = 1, desc = "Tông Sư thứ 20 Chương 1 Về"})
mapArray:push({ id = 79, type = 2, kind = 1059, icon = 1, desc = "Tông Sư thứ 20 Chương 2 Về"})
mapArray:push({ id = 80, type = 2, kind = 1060, icon = 1, desc = "Tông Sư thứ 20 Chương 3 Về"})
mapArray:push({ id = 81, type = 2, kind = 1061, icon = 1, desc = "Tông Sư thứ 21 Chương 1 Về"})
mapArray:push({ id = 82, type = 2, kind = 1062, icon = 1, desc = "Tông Sư thứ 21 Chương 2 Về"})
mapArray:push({ id = 83, type = 2, kind = 1063, icon = 1, desc = "Tông Sư thứ 21 Chương 3 Về"})
mapArray:push({ id = 84, type = 2, kind = 1064, icon = 1, desc = "Tông Sư thứ 22 Chương 1 Về"})
mapArray:push({ id = 85, type = 2, kind = 1065, icon = 1, desc = "Tông Sư thứ 22 Chương 2 Về"})
mapArray:push({ id = 86, type = 2, kind = 1066, icon = 1, desc = "Tông Sư thứ 22 Chương 3 Về"})
mapArray:push({ id = 87, type = 2, kind = 1067, icon = 1, desc = "Tông Sư thứ 23 Chương 1 Về"})
mapArray:push({ id = 88, type = 2, kind = 1068, icon = 1, desc = "Tông Sư thứ 23 Chương 2 Về"})
mapArray:push({ id = 89, type = 2, kind = 1069, icon = 1, desc = "Tông Sư thứ 23 Chương 3 Về"})
mapArray:push({ id = 90, type = 2, kind = 1070, icon = 1, desc = "Tông Sư thứ 24 Chương 1 Về"})
mapArray:push({ id = 91, type = 2, kind = 1071, icon = 1, desc = "Tông Sư thứ 24 Chương 2 Về"})
mapArray:push({ id = 92, type = 2, kind = 1072, icon = 1, desc = "Tông Sư thứ 24 Chương 3 Về"})
mapArray:push({ id = 93, type = 2, kind = 1073, icon = 1, desc = "Tông Sư thứ 25 Chương 1 Về"})
mapArray:push({ id = 94, type = 2, kind = 1074, icon = 1, desc = "Tông Sư thứ 25 Chương 2 Về"})
mapArray:push({ id = 95, type = 2, kind = 1075, icon = 1, desc = "Tông Sư thứ 25 Chương 3 Về"})
mapArray:push({ id = 96, type = 2, kind = 1076, icon = 1, desc = "Tông Sư thứ 26 Chương 1 Về"})
mapArray:push({ id = 97, type = 2, kind = 1077, icon = 1, desc = "Tông Sư thứ 26 Chương 2 Về"})
mapArray:push({ id = 98, type = 2, kind = 1078, icon = 1, desc = "Tông Sư thứ 26 Chương 3 Về"})
mapArray:push({ id = 99, type = 2, kind = 1079, icon = 1, desc = "Tông Sư thứ 27 Chương 1 Về"})
mapArray:push({ id = 100, type = 2, kind = 1080, icon = 1, desc = "Tông Sư thứ 27 Chương 2 Về"})
mapArray:push({ id = 101, type = 2, kind = 1081, icon = 1, desc = "Tông Sư thứ 27 Chương 3 Về"})
mapArray:push({ id = 102, type = 2, kind = 1082, icon = 1, desc = "Tông Sư thứ 28 Chương 1 Về"})
mapArray:push({ id = 103, type = 2, kind = 1083, icon = 1, desc = "Tông Sư thứ 28 Chương 2 Về"})
mapArray:push({ id = 104, type = 2, kind = 1084, icon = 1, desc = "Tông Sư thứ 28 Chương 3 Về"})
mapArray:push({ id = 105, type = 2, kind = 1085, icon = 1, desc = "Tông Sư thứ 29 Chương 1 Về"})
mapArray:push({ id = 106, type = 2, kind = 1086, icon = 1, desc = "Tông Sư thứ 29 Chương 2 Về"})
mapArray:push({ id = 107, type = 2, kind = 1087, icon = 1, desc = "Tông Sư thứ 29 Chương 3 Về"})
return mapArray
