local mapArray = MEMapArray:new()
mapArray:push({ order = 1, type = 1, title = "Phổ công tổn thương tăng thêm"})
mapArray:push({ order = 2, type = 2, title = "Kỹ có thể tổn thương tăng thêm"})
mapArray:push({ order = 3, type = 3, title = "Tiếp tục tổn thương tăng thêm"})
mapArray:push({ order = 4, type = 4, title = "Phổ công giảm tổn thương"})
mapArray:push({ order = 5, type = 5, title = "Kỹ có thể giảm tổn thương"})
mapArray:push({ order = 6, type = 6, title = "Tiếp tục giảm tổn thương"})
mapArray:push({ order = 7, type = 7, title = "Khí Huyết Thuộc Tính đề cao"})
mapArray:push({ order = 8, type = 8, title = "Võ lực thuộc tính đề cao"})
mapArray:push({ order = 9, type = 9, title = "Phòng ngự thuộc tính đề cao"})
mapArray:push({ order = 10, type = 10, title = "Nội lực thuộc tính đề cao"})
mapArray:push({ order = 11, type = 11, title = "Thân pháp thuộc tính đề cao"})
mapArray:push({ order = 12, type = 12, title = "Trúng đích thuộc tính đề cao"})
mapArray:push({ order = 13, type = 13, title = "Trúng đích thuộc tính đề cao"})
mapArray:push({ order = 14, type = 14, title = "Né tránh thuộc tính đề cao"})
mapArray:push({ order = 15, type = 15, title = "Bạo kích thuộc tính đề cao"})
mapArray:push({ order = 16, type = 16, title = "Kháng bạo thuộc tính đề cao"})
return mapArray
