local mapArray = MEMapArray:new()
mapArray:push({ id = 1, activityType = 41, missionType = 1, target = 9, reward = "1_30445_5", desc = "Vượt quan : phổ thông thông quan đạt tới（{p1})Lần"})
mapArray:push({ id = 2, activityType = 41, missionType = 2, target = 3, reward = "1_30445_5", desc = "Vượt quan : Tông Sư thông quan đạt tới（{p1}）Lần"})
mapArray:push({ id = 3, activityType = 41, missionType = 5, target = 1, reward = "1_30445_5", desc = "Quần hào phổ thu hoạch được（{p1})Lần Thắng lợi"})
mapArray:push({ id = 4, activityType = 41, missionType = 6, target = 1, reward = "1_30445_5", desc = "Nhạn Môn Quan mở ra（{p1}）bảo rương"})
mapArray:push({ id = 5, activityType = 41, missionType = 7, target = 1, reward = "1_30445_5", desc = "Thần Nông mỏ đào quáng（{p1})Lần"})
mapArray:push({ id = 6, activityType = 41, missionType = 8, target = 1, reward = "1_30445_5", desc = "Thần Nông mỏ kiếp mỏ（{p1})Lần"})
mapArray:push({ id = 7, activityType = 41, missionType = 9, target = 1, reward = "1_30445_5", desc = "Tham dự Phục Ma ghi chép（{p1}）Lần"})
mapArray:push({ id = 9, activityType = 41, missionType = 12, target = 1, reward = "1_30445_5", desc = "Thiên Giai tranh bá thu hoạch được（{p1}）Lần Thắng lợi"})
mapArray:push({ id = 10, activityType = 41, missionType = 14, target = 2, reward = "1_30445_10", desc = "Nhận lấy（{p1}）Lần Mỗi ngày tháng thẻ ban thưởng"})
mapArray:push({ id = 11, activityType = 42, missionType = 1, target = 288, reward = "1_30445_30", desc = "Vượt quan : phổ thông thông quan đạt tới（{p1})Lần"})
mapArray:push({ id = 12, activityType = 42, missionType = 2, target = 88, reward = "1_30445_35", desc = "Vượt quan : Tông Sư thông quan đạt tới（{p1}）Lần"})
mapArray:push({ id = 13, activityType = 42, missionType = 3, target = 10, reward = "1_30445_28", desc = "Tham dự du lịch ngẫu nhiên sự kiện（{p1})Lần"})
mapArray:push({ id = 15, activityType = 42, missionType = 5, target = 20, reward = "1_30445_35", desc = "Quần hào phổ thu hoạch được（{p1})Lần Thắng lợi"})
mapArray:push({ id = 16, activityType = 42, missionType = 6, target = 20, reward = "1_30445_40", desc = "Nhạn Môn Quan mở ra（{p1}）bảo rương"})
mapArray:push({ id = 17, activityType = 42, missionType = 7, target = 20, reward = "1_30445_35", desc = "Thần Nông mỏ đào quáng（{p1})Lần"})
mapArray:push({ id = 18, activityType = 42, missionType = 8, target = 20, reward = "1_30445_30", desc = "Thần Nông mỏ kiếp mỏ（{p1})Lần"})
mapArray:push({ id = 19, activityType = 42, missionType = 9, target = 20, reward = "1_30445_35", desc = "Tham dự Phục Ma ghi chép（{p1}）Lần"})
mapArray:push({ id = 21, activityType = 42, missionType = 11, target = 21, reward = "1_30445_42", desc = "Thiên Giai tranh bá đạt tới vương giả đẳng cấp（{p1}）"})
mapArray:push({ id = 22, activityType = 42, missionType = 12, target = 20, reward = "1_30445_42", desc = "Thiên Giai tranh bá thu hoạch được（{p1}）Lần Thắng lợi"})
mapArray:push({ id = 23, activityType = 42, missionType = 13, target = 10, reward = "1_30445_50", desc = "Nhiệm vụ hàng ngày thu hoạch được（{p1}）Lần Cuối cùng tiến độ ban thưởng"})
mapArray:push({ id = 24, activityType = 42, missionType = 14, target = 20, reward = "1_30445_35", desc = "Nhận lấy（{p1}）Lần Lớn nhỏ tháng thẻ ban thưởng"})
mapArray:push({ id = 25, activityType = 42, missionType = 15, target = 5, reward = "1_30445_40", desc = "Cấp cho（{p1}）Lần Bang phái hồng bao"})
return mapArray
