local mapArray = MEMapArray:new()
mapArray:push({ id = 1, context = "Ai không biết Hàng Long Thập Bát Chưởng?", answers = "1,2,3"})
mapArray:push({ id = 2, context = "Nga Mi đời thứ hai Chưởng môn nhân tên gọi là gì?", answers = "4,5,6"})
mapArray:push({ id = 3, context = "Dương Quá tại Toàn Chân giáo bái sư phụ là ai?", answers = "7,8,9"})
mapArray:push({ id = 4, context = "Đông Tà cả đời tổng cộng thu bao nhiêu tên đệ tử?", answers = "10,11,12"})
mapArray:push({ id = 5, context = "Toàn Chân thất tử, Khâu Xử Cơ đạo hiệu là cái gì?", answers = "13,14,15"})
mapArray:push({ id = 6, context = "Võ Đang Thất Hiệp,cha của Trương Vô Kỵ thứ mấy?", answers = "16,17,18"})
mapArray:push({ id = 7, context = "Phi Hồ Ngoại Truyền được xưng là đệ nhất độc vật là cái gì?", answers = "19,20,21"})
mapArray:push({ id = 8, context = "Thành Côn tại Thiếu Lâm tự Pháp Danh là cái gì?", answers = "22,23,24"})
mapArray:push({ id = 9, context = "Lâm gia Tịch Tà Kiếm Phổ là viết tại cái gì bên trên?", answers = "25,26,27"})
mapArray:push({ id = 10, context = "Đông Tà thê tử tên gọi là gì?", answers = "28,29,30"})
mapArray:push({ id = 11, context = "Quách Tĩnh đánh bại Hoàng Hà Tứ Quỷ là ai đồ đệ?", answers = "31,32,33"})
mapArray:push({ id = 12, context = "Thanh Thành Tứ Tú ngoại trừ Hầu Nhân Anh,Hồng Nhân Hùng,Vu Nhân Hào,là ai?", answers = "34,35,36"})
mapArray:push({ id = 13, context = "Dây dưa dài dòng là cái nào hạng tuyệt học chiêu thức?", answers = "37,38,39"})
mapArray:push({ id = 14, context = "Mai Siêu Phong bản danh kêu cái gì?", answers = "40,41,42"})
mapArray:push({ id = 15, context = "Đoàn Dự cha ruột là ai?", answers = "43,44,45"})
mapArray:push({ id = 16, context = "Quân Tử Kiếm cùng Thục Nữ Kiếm ban sơ thu giấu ở nơi nào?", answers = "46,47,48"})
mapArray:push({ id = 17, context = "Đả Cẩu Bổng Pháp một chiêu cuối cùng tên gọi là gì?", answers = "49,50,51"})
mapArray:push({ id = 18, context = "Nam Nhạc Hành Sơn Phái Chưởng môn nhân là ai?", answers = "52,53,54"})
mapArray:push({ id = 19, context = "Lần thứ nhất Hoa Sơn Luận Kiếm là ai cuối cùng thắng được?", answers = "55,56,57"})
mapArray:push({ id = 20, context = "Mới Ngũ Tuyệt, Dương Quá danh xưng là cái gì?", answers = "58,59,60"})
mapArray:push({ id = 21, context = "Chưởng môn Tả Lãnh Thiện đắc ý võ học là cái gì?", answers = "61,62,63"})
mapArray:push({ id = 22, context = "Đồ Long Đao giấu có cái gì?", answers = "64,65,66"})
mapArray:push({ id = 23, context = "Ỷ Thiên Kiếm giấu có cái gì?", answers = "67,68,69"})
mapArray:push({ id = 24, context = "Chưa học qua Cửu Âm Chân Kinh chính là ai?", answers = "70,71,72"})
mapArray:push({ id = 25, context = "Minh giáo Trấn Giáo thần công là cái gì?", answers = "73,74,75"})
mapArray:push({ id = 26, context = "Minh giáo nổi danh Điệp cốc Y Tiên tên gọi là gì?", answers = "76,77,78"})
mapArray:push({ id = 27, context = "Cùng lão đầu tử tịnh xưng Hoàng Hà lão tổ chính là ai?", answers = "79,80,81"})
mapArray:push({ id = 28, context = "chiêu thức không thuộc về Lục Mạch Thần Kiếm?", answers = "82,83,84"})
mapArray:push({ id = 29, context = "chiêu thức không thuộc về Thiên Sơn Lục Dương Chưởng?", answers = "85,86,87"})
mapArray:push({ id = 30, context = "chiêu thức không thuộc về Hàng Long Thập Bát Chưởng?", answers = "88,89,90"})
mapArray:push({ id = 31, context = "người nào là Trương Vô Kỵ mối tình đầu?", answers = "91,92,93"})
mapArray:push({ id = 32, context = "Triệu Mẫn từng sử dụng tới liều mạng ba chiêu?", answers = "94,95,96"})
mapArray:push({ id = 33, context = "Liên Thành Quyết,bốn vị đại hiệp hoa là ai?", answers = "97,98,99"})
mapArray:push({ id = 34, context = "Ngốc cô là nữ nhi của ai?", answers = "100,101,102"})
mapArray:push({ id = 35, context = "Đinh Điển Hồng Nhan Tri Kỷ là ai?", answers = "103,104,105"})
mapArray:push({ id = 36, context = "Giang Nam Thất Quái Kha Trấn Ác ngoại hiệu là cái gì?", answers = "106,107,108"})
mapArray:push({ id = 37, context = "Đấu Chuyển Tinh Di là do ai sáng tạo ra?", answers = "109,110,111"})
mapArray:push({ id = 38, context = "Nhậm Ngã Hành có ba cái bội phục người,trong đó bội phục nhất là ai?", answers = "112,113,114"})
mapArray:push({ id = 39, context = "Lưu Chính Phong trong phủ trêu đùa Dư Thương Hải chính là ai?", answers = "115,116,117"})
mapArray:push({ id = 40, context = "Hướng Vấn Thiên ngoại hiệu là cái gì?", answers = "118,119,120"})
mapArray:push({ id = 41, context = "Thần Mộc Vương Đỉnh là dùng tu luyện võ học?", answers = "121,122,123"})
mapArray:push({ id = 42, context = "Hàm Hương Công Chúa tên gọi là gì?", answers = "124,125,126"})
mapArray:push({ id = 43, context = "Tạ Tốn con mắt là bị ai lộng mù?", answers = "127,128,129"})
mapArray:push({ id = 44, context = "Mười tám Học Sĩ là loại thượng phẩm?", answers = "130,131,132"})
mapArray:push({ id = 45, context = "Mộc Vương Phủ Tiểu Quận Chúa tên gọi là gì?", answers = "133,134,135"})
mapArray:push({ id = 46, context = "Yêu râu xanh Điền Bá Quang ngoại hiệu là cái gì?", answers = "136,137,138"})
mapArray:push({ id = 47, context = "Tây Hạ Nhất Phẩm Đường am hiểu độc vật kêu cái gì?", answers = "139,140,141"})
mapArray:push({ id = 48, context = "Loại kia võ học là Tây Độc Cáp Mô Công khắc tinh?", answers = "142,143,144"})
mapArray:push({ id = 49, context = "Thiên hạ vô địch người Miêu ngoại hiệu kêu cái gì?", answers = "145,146,147"})
mapArray:push({ id = 50, context = "Thích Phương đối Địch Vân nick name là cái gì?", answers = "148,149,150"})
mapArray:push({ id = 51, context = "Địch Vân sư phụ Thích Trường Phát ngoại hiệu là cái gì?", answers = "151,152,153"})
mapArray:push({ id = 52, context = "Người nào không phải Mộ Dung Phục gia thần?", answers = "154,155,156"})
mapArray:push({ id = 53, context = "Đem Thiên Sơn Đồng Lão bắt đi chính là ai?", answers = "157,158,159"})
mapArray:push({ id = 54, context = "Kiều Phong dùng võ công gì đánh thắng Thiếu Lâm Cao tăng?", answers = "160,161,162"})
mapArray:push({ id = 55, context = "Kiều Phong lấy một địch ba, đối thủ không có người nào?", answers = "163,164,165"})
mapArray:push({ id = 56, context = "Từng cùng Quách Tĩnh lập thành hôn ước chính là ai?", answers = "166,167,168"})
mapArray:push({ id = 57, context = "Quách Tĩnh tại thảo nguyên được xưng là cái gì?", answers = "169,170,171"})
mapArray:push({ id = 58, context = "Dương Quá chữ đổi chi là ai vì hắn lấy?", answers = "172,173,174"})
mapArray:push({ id = 59, context = "Vi Tiểu Bảo là Thần Long Giáo chưởng Long Sứ?", answers = "175,176,177"})
mapArray:push({ id = 60, context = "Cùng Địch Vân tại tuyết cốc gặp gỡ chính là ai?", answers = "178,179,180"})
mapArray:push({ id = 61, context = "Trong tứ đại ác nhân lão đại ngoại hiệu là cái gì?", answers = "181,182,183"})
mapArray:push({ id = 62, context = "A Chu cùng mẫu thân của A Tử là ai?", answers = "184,185,186"})
mapArray:push({ id = 63, context = "Đại Luân Minh Vương bản lĩnh giữ nhà là cái gì?", answers = "187,188,189"})
mapArray:push({ id = 64, context = "người nào không phải Nhất Đăng đồ đệ?", answers = "190,191,192"})
mapArray:push({ id = 65, context = "rất tốt rất tốt,nhưng ta không thích. Ai nói?", answers = "193,194,195"})
mapArray:push({ id = 66, context = "Vi Tiểu Bảo là Thiên Địa Hội Phân Đường Hương chủ?", answers = "196,197,198"})
mapArray:push({ id = 67, context = "người nào không thuộc về Mai Trang tứ hữu?", answers = "199,200,201"})
mapArray:push({ id = 68, context = "Võ Đang Thất Hiệp,bị người ám toán cả đời tàn tật là ai?", answers = "202,203,204"})
mapArray:push({ id = 69, context = "Mỹ Nữ Quyền Pháp,Dương Quá tự sáng tạo chiêu thức là cái gì?", answers = "205,206,207"})
mapArray:push({ id = 70, context = "Viên Tử Y thân phận chân thật là cái gì?", answers = "208,209,210"})
mapArray:push({ id = 71, context = "Cô Hồng Hải Là loại chiêu thức?", answers = "211,212,213"})
mapArray:push({ id = 72, context = "Địch Vân thần chiếu công là ai truyền thụ cho?", answers = "214,215,216"})
mapArray:push({ id = 73, context = "Thủy Sanh cùng biểu ca của nàng bị xưng làm cái gì?", answers = "217,218,219"})
mapArray:push({ id = 74, context = "Kiều Phong dưỡng phụ tên gọi là gì?", answers = "220,221,222"})
mapArray:push({ id = 75, context = "ai không có tham dự Tụ Hiền Trang đại chiến?", answers = "223,224,225"})
mapArray:push({ id = 76, context = "Quần hùng vây công Kiều Phong,Đoàn vương gia thái độ là?", answers = "226,227,228"})
mapArray:push({ id = 77, context = "Hư Trúc dùng võ học đánh thắng Đinh Xuân Thu?", answers = "229,230,231"})
mapArray:push({ id = 78, context = "Vô Nhai Tử cho Hư Trúc một bức họa,là ai?", answers = "232,233,234"})
mapArray:push({ id = 79, context = "Mai Kiếm Lan Kiếm Trúc Kiếm,còn lại là?", answers = "235,236,237"})
mapArray:push({ id = 80, context = "Bao Bất Đồng cuối cùng chết bởi ai?", answers = "238,239,240"})
mapArray:push({ id = 81, context = "Quách Tĩnh Tiểu Hồng Mã là cái gì chủng loại?", answers = "241,242,243"})
mapArray:push({ id = 82, context = "Quách Tĩnh, Hoàng Dung gặp nhau là nơi nào?", answers = "244,245,246"})
mapArray:push({ id = 83, context = "Đông Tà vị nào đồ đệ vì cứu hắn mà chết?", answers = "247,248,249"})
mapArray:push({ id = 84, context = "Dương Khang cầm đi Mục Niệm Từ vật phẩm gì?", answers = "250,251,252"})
mapArray:push({ id = 85, context = "Giang Nam Thất Quái nữ tử Hàn Tiểu Oánh thứ mấy?", answers = "253,254,255"})
mapArray:push({ id = 86, context = "Toàn Chân thất tử võ công người mạnh nhất là ai?", answers = "256,257,258"})
mapArray:push({ id = 87, context = "Quách Tương nghe được thần điêu đại hiệp là ở đâu?", answers = "259,260,261"})
mapArray:push({ id = 88, context = "Lệnh Hồ Xung từng làm Ngũ Nhạc Kiếm Phái Chưởng môn?", answers = "262,263,264"})
mapArray:push({ id = 89, context = "Nhật Nguyệt Thần Giáo độc dược là cái gì?", answers = "265,266,267"})
mapArray:push({ id = 90, context = "Dương Quá lấy được kiếm là cái gì kiếm?", answers = "268,269,270"})
mapArray:push({ id = 91, context = "Trình Anh cứu được Dương Quá,trên giấy viết rất nhiều lần câu gì?", answers = "271,272,273"})
mapArray:push({ id = 92, context = "Kim Luân Pháp Vương học thành tuyệt học quay về Trung Nguyên?", answers = "274,275,276"})
mapArray:push({ id = 93, context = "Sử Tiểu Thúy vi Thạch Phá Thiên lấy danh tự là cái gì?", answers = "277,278,279"})
mapArray:push({ id = 94, context = "Triệu Mẫn dùng vật phẩm gì làm mồi nhử Trương Vô Kỵ", answers = "280,281,282"})
mapArray:push({ id = 95, context = "Trương Vô Kỵ cùng Chu Chỉ Nhược lần đầu gặp mặt là ở đâu?", answers = "283,284,285"})
mapArray:push({ id = 96, context = "Từng cùng Viên Thừa Chí trốn trong áo ngủ chính là ai?", answers = "286,287,288"})
mapArray:push({ id = 97, context = "Tiêu Trung Tuệ chân chính dòng họ là cái gì?", answers = "289,290,291"})
mapArray:push({ id = 98, context = "Bố trí xuống Trân Lung ván cờ người là ai?", answers = "292,293,294"})
mapArray:push({ id = 99, context = "một hạng không phải Đào hoa đảo võ học?", answers = "295,296,297"})
mapArray:push({ id = 100, context = "Triệu Mẫn phong hào là cái gì?", answers = "298,299,300"})
mapArray:push({ id = 101, context = "Trang Sinh Hiểu Mộng mê hồ điệp, câu tiếp theo là?", answers = "301,302,303"})
mapArray:push({ id = 102, context = "Tinh rủ xuống bình dã rộng rãi, câu tiếp theo là?", answers = "304,305,306"})
mapArray:push({ id = 103, context = "Lưu luyến hí điệp nào cũng múa, câu tiếp theo là?", answers = "307,308,309"})
mapArray:push({ id = 104, context = "Dưới đây thuộc về tứ đại có tên chính là?", answers = "310,311,312"})
mapArray:push({ id = 105, context = "Liễu Mộng May cùng Đỗ Lệ nương là nhân vật?", answers = "313,314,315"})
mapArray:push({ id = 106, context = "《 Tư Trì Thông Giám 》 tác giả là?", answers = "316,317,318"})
mapArray:push({ id = 107, context = "Bạch Cư Dịch hào là cái gì?", answers = "319,320,321"})
mapArray:push({ id = 108, context = "Hào Túy Ông Chính là vị nào?", answers = "322,323,324"})
mapArray:push({ id = 109, context = "Long Thành Phi Tướng tại,Hồ Mã độ Âm Sơn.tác giả là?", answers = "325,326,327"})
mapArray:push({ id = 110, context = "Hào quang muôn trượng dài. Câu Lý Đỗ chỉ là?", answers = "328,329,330"})
mapArray:push({ id = 111, context = "Không thuộc về Đường Tống Bát đại gia chính là?", answers = "331,332,333"})
mapArray:push({ id = 112, context = "Tu thân, Tề gia, trị quốc, bình thiên hạ xuất xứ?", answers = "334,335,336"})
mapArray:push({ id = 113, context = "không thuộc về Tứ Thư chính là?", answers = "337,338,339"})
mapArray:push({ id = 114, context = "Sàng tiền minh nguyệt quang,Đất trắng ngỡ như sương.đề mục là?", answers = "340,341,342"})
mapArray:push({ id = 115, context = "không thuộc về Nguyên Khúc tứ đại gia chính là?", answers = "343,344,345"})
mapArray:push({ id = 116, context = "Được xưng là thơ quỷ chính là?", answers = "346,347,348"})
mapArray:push({ id = 117, context = "Tiểu Lâu Nhất Dạ Thính Xuân Vũ, câu tiếp theo là?", answers = "349,350,351"})
mapArray:push({ id = 118, context = "Lý Thanh Chiếu tác phẩm?", answers = "352,353,354"})
mapArray:push({ id = 119, context = "Tần Khả Khanh là một bộ nào trong tác phẩm nhân vật?", answers = "355,356,357"})
mapArray:push({ id = 120, context = "Đường dài lắm gian truân,lên dưới mà tìm kiếm. Xuất xứ là?", answers = "358,359,360"})
mapArray:push({ id = 121, context = "Thiên hạ mới chung một thạch, Tử Kiến độc chiếm tám đấu. Tử Kiến chỉ là ai?", answers = "361,362,363"})
mapArray:push({ id = 122, context = "Kim qua thiết mã, khí thôn vạn dặm như hổ. Là ai từ ngữ?", answers = "364,365,366"})
mapArray:push({ id = 123, context = "Cổ khúc 《 Quảng Lăng Tán 》 giảng là chuyện gì kiện?", answers = "367,368,369"})
mapArray:push({ id = 124, context = "Ba nói hai vỗ trúng ba nói, tác giả là ai?", answers = "370,371,372"})
mapArray:push({ id = 125, context = "《 Đào Hoa Nguyên Ký 》 là ai tác phẩm?", answers = "373,374,375"})
mapArray:push({ id = 126, context = "không thuộc về thời cổ Ngũ Âm chính là?", answers = "376,377,378"})
mapArray:push({ id = 127, context = "Tuổi xây dựng sự nghiệp , bình thường là ?", answers = "379,380,381"})
mapArray:push({ id = 128, context = "Thời cổ khoa cử đem hạng ba xưng là?", answers = "382,383,384"})
mapArray:push({ id = 129, context = "không thuộc về 《 Ngũ Kinh » chính là?", answers = "385,386,387"})
mapArray:push({ id = 130, context = "không thuộc về tam cương là?", answers = "388,389,390"})
mapArray:push({ id = 131, context = "không thuộc về Ngũ Thường là?", answers = "391,392,393"})
mapArray:push({ id = 132, context = "Lo trước cái lo của thiên hạ, vui sau cái vui của thiên hạ chính là?", answers = "394,395,396"})
mapArray:push({ id = 133, context = "Xuất sư biểu tác giả là?", answers = "397,398,399"})
mapArray:push({ id = 134, context = "Được xưng tán vi Làm gì tướng quân là trượng phu nữ tướng là ai?", answers = "400,401,402"})
mapArray:push({ id = 135, context = "vị nào không phải cổ đại Tứ Đại Mỹ Nữ một trong?", answers = "403,404,405"})
mapArray:push({ id = 136, context = "Cùng Kinh Kha cùng nhau ám sát Tần Vương người là ai?", answers = "406,407,408"})
mapArray:push({ id = 137, context = "Ngũ Nhạc, Tây Nhạc là chỉ toà nào núi?", answers = "409,410,411"})
mapArray:push({ id = 138, context = "Thanh mai trúc mã điển cố xuất xứ cái nào một bài thơ?", answers = "412,413,414"})
mapArray:push({ id = 139, context = "Yến tước sao biết chí hồng hộc ra từ nơi đâu?", answers = "415,416,417"})
mapArray:push({ id = 140, context = "không thuộc về tứ đại dân gian truyền thuyết chính là?", answers = "418,419,420"})
mapArray:push({ id = 141, context = "Chim sa cá lặn Trầm Ngư là hình dung cái nào một vị mỹ nữ?", answers = "421,422,423"})
mapArray:push({ id = 142, context = "Tết Nguyên Tiêu tại thời cổ được xưng là cái gì?", answers = "424,425,426"})
mapArray:push({ id = 143, context = "quốc gia nào không thuộc về Chiến Quốc Thất Hùng?", answers = "427,428,429"})
mapArray:push({ id = 144, context = "Thời kỳ Xuân Thu vị thứ nhất xưng bá Quân chủ là?", answers = "430,431,432"})
mapArray:push({ id = 145, context = "Vòng mập yến gầy yến chỉ là?", answers = "433,434,435"})
mapArray:push({ id = 146, context = "Thời cổ xưng nhất giáp là bao nhiêu năm?", answers = "436,437,438"})
mapArray:push({ id = 147, context = "Nhượng bộ lui binh, một bỏ là bao nhiêu dặm?", answers = "439,440,441"})
mapArray:push({ id = 148, context = "Thời cổ xưng hai tám giai nhân, là chỉ bao lớn niên kỷ?", answers = "442,443,444"})
mapArray:push({ id = 149, context = "Tứ Minh cuồng khách là ai?", answers = "445,446,447"})
mapArray:push({ id = 150, context = "Xuân Giang Hoa Nguyệt Dạ tác giả là ai?", answers = "448,449,450"})
mapArray:push({ id = 151, context = "không phải trị liệu hiệp khách chính là?", answers = "451,452,453"})
mapArray:push({ id = 152, context = "vị nào là khống chế hiệp khách?", answers = "454,455,456"})
mapArray:push({ id = 153, context = "vị nào hiệp khách có thể cho đồng đội thực hiện hộ thuẫn?", answers = "457,458,459"})
mapArray:push({ id = 154, context = "Đầy Tinh Kiếm ma võ lực hệ số là phần trăm bao nhiêu?", answers = "460,461,462"})
mapArray:push({ id = 155, context = "kỹ năng chủ động võ lực hệ số cao nhất hiệp khách là?", answers = "463,464,465"})
mapArray:push({ id = 156, context = "Nga Mi thần kỹ sẽ thực hiện trạng thái gì?", answers = "466,467,468"})
mapArray:push({ id = 157, context = "vị nào hiệp khách không có điểm huyệt năng lực?", answers = "469,470,471"})
mapArray:push({ id = 158, context = "cùng Cửu Dương giáo chủ không tồn tại duyên phần?", answers = "472,473,474"})
mapArray:push({ id = 159, context = "Vương giả lôi đài một tuần có một ngày mở ra?", answers = "475,476,477"})
mapArray:push({ id = 160, context = "Võ Lâm Đại Hội trận chung kết là ngày nào tiến hành?", answers = "478,479,480"})
mapArray:push({ id = 161, context = "vật phẩm nào không thể đang bang phái Tế Thế?", answers = "481,482,483"})
mapArray:push({ id = 162, context = "Bang phái mỗi ngày có thể trợ lực bao nhiêu lần?", answers = "484,485,486"})
mapArray:push({ id = 163, context = "Trung nghĩa lũy bao nhiêu bang phái có thể mở ra diễn võ?", answers = "487,488,489"})
mapArray:push({ id = 164, context = "Thời gian Bang Chủ có thể cấp sinh động hồng bao?", answers = "490,491,492"})
mapArray:push({ id = 165, context = "Mỗi tên người chơi có thể thêm bao nhiêu hảo hữu?", answers = "493,494,495"})
mapArray:push({ id = 166, context = "Hiệp khách mấy sao có thể sử dụng làm ảnh chân dung?", answers = "496,497,498"})
mapArray:push({ id = 167, context = "Ngự Thiện Phòng nhận lấy bao nhiêu thể lực?", answers = "499,500,501"})
mapArray:push({ id = 168, context = "bộ vị nào trang bị có thể khảm nạm bạo kích bảo thạch?", answers = "502,503,504"})
mapArray:push({ id = 169, context = "Chỗ nào có thể khảm nạm tất cả chủng loại bảo thạch?", answers = "505,506,507"})
mapArray:push({ id = 170, context = "Vô lượng cơn ác mộng 80 tầng vị nào trấn thủ?", answers = "508,509,510"})
mapArray:push({ id = 171, context = "Vô Lượng Sơn Nam Phong cùng bắc quật bao nhiêu tầng?", answers = "511,512,513"})
mapArray:push({ id = 172, context = "loại ảnh chân dung khung là có thuộc tính tăng thêm?", answers = "514,515,516"})
mapArray:push({ id = 173, context = "Pet kỹ năng cần xuất thủ bao nhiêu lần mới có thể phát động?", answers = "517,518,519"})
mapArray:push({ id = 174, context = "Pet cao nhất có thể đột phá tới cái gì phẩm chất?", answers = "520,521,522"})
mapArray:push({ id = 175, context = "Không phải kỹ năng sách lược kỹ năng phóng ra điều kiện?", answers = "523,524,525"})
mapArray:push({ id = 176, context = "Mỗi loại trận pháp có thể có bao nhiêu cái trận vị?", answers = "526,527,528"})
mapArray:push({ id = 177, context = "Hợp thành bảo thạch,cần tiêu hao bao nhiêu bảo thạch?", answers = "529,530,531"})
mapArray:push({ id = 178, context = "Đồ màu cam cần bao nhiêu mảnh đến hợp thành?", answers = "532,533,534"})
mapArray:push({ id = 179, context = "loại nào trang bị không có vạn năng duyên phận?", answers = "535,536,537"})
mapArray:push({ id = 180, context = "Thuộc tính khí huyết cùng nội lực chính là Thiên Thư?", answers = "538,539,540"})
mapArray:push({ id = 181, context = "Chủ thuộc tính là võ lực chính là loại nào tâm pháp?", answers = "541,542,543"})
mapArray:push({ id = 182, context = "Hiệp khách có thể trở thành thần thoại phẩm chất?", answers = "544,545,546"})
mapArray:push({ id = 183, context = "Skill chủ động không cách nào giảm xuống thụ kích thuộc tính?", answers = "547,548,549"})
mapArray:push({ id = 184, context = "Mỗi ngày có thể tiến hành bao nhiêu lần cầu nguyện?", answers = "550,551,552"})
mapArray:push({ id = 185, context = "Tiến hành 10 lần rút cần tiêu hao cái gì đạo cụ?", answers = "553,554,555"})
mapArray:push({ id = 186, context = "Cửa hàng có thể mua được Thiên Cương phù?", answers = "556,557,558"})
mapArray:push({ id = 187, context = "Hoàn thành 22 nhiệm vụ hàng ngày có thể được ban thưởng gì?", answers = "559,560,561"})
mapArray:push({ id = 188, context = "Tế Tự công năng, người chơi mỗi ngày có thể miễn phí nhận lấy bao nhiêu linh khí?", answers = "562,563,564"})
mapArray:push({ id = 189, context = "Tế Tự công năng, sử dụng một lần Đàn Hương lô cần tiêu hao bao nhiêu Nguyên Bảo?", answers = "565,566,567"})
mapArray:push({ id = 190, context = "Thỏa mãn cái nào một hạng điều kiện có thể tham gia vượt phục Võ Lâm Đại Hội?", answers = "568,569,570"})
mapArray:push({ id = 191, context = "cái nào một hạng không phải anh hùng đại hội phân tổ tên?", answers = "571,572,573"})
mapArray:push({ id = 192, context = "Môn phái đại sư trước bao nhiêu tên,trở thành võ lâm vương giả?", answers = "574,575,576"})
mapArray:push({ id = 193, context = "có một ngày có thể khiêu chiến Ma Ha sườn núi tất cả cửa khẩu?", answers = "577,578,579"})
mapArray:push({ id = 194, context = "Anh Hùng Chí,khiêu chiến cần tiêu hao bao nhiêu thể lực?", answers = "580,581,582"})
mapArray:push({ id = 195, context = "Người chơi mỗi ngày có thể miễn phí được bánh bao?", answers = "583,584,585"})
mapArray:push({ id = 196, context = "Đào bảo,người chơi thu hoạch được bảo rương số lần là?", answers = "586,587,588"})
mapArray:push({ id = 197, context = "Lần đầu mua sắm thể lực cần phải hao phí bao nhiêu Nguyên Bảo?", answers = "589,590,591"})
mapArray:push({ id = 198, context = "Hiệp khách không thể vì đồng đội thực hiện giảm thương trạng thái?", answers = "592,593,594"})
mapArray:push({ id = 199, context = "Hiệp khách không thể vì địch quân thực hiện sa sút trạng thái?", answers = "595,596,597"})
mapArray:push({ id = 200, context = "Hiệp khách phóng ra kỹ năng công kích không nhìn địch quân phòng ngự thuộc tính?", answers = "598,599,600"})
return mapArray
