local mapArray = MEMapArray:new()
mapArray:push({ id = 1, type = 1, recharge_id = 1, desc = "Hôm nay có thể dùng 6 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 2, type = 1, recharge_id = 2, desc = "Hôm nay có thể dùng 30 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 3, type = 1, recharge_id = 3, desc = "Hôm nay có thể dùng 98 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 4, type = 1, recharge_id = 4, desc = "Hôm nay có thể dùng 198 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 5, type = 1, recharge_id = 5, desc = "Hôm nay có thể dùng 328 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 6, type = 1, recharge_id = 6, desc = "Hôm nay có thể dùng 648 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 7, type = 2, recharge_id = 1, desc = "Ngày mai có thể dùng 6 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 8, type = 2, recharge_id = 2, desc = "Ngày mai có thể dùng 30 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 9, type = 2, recharge_id = 3, desc = "Ngày mai có thể dùng 98 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 10, type = 2, recharge_id = 4, desc = "Ngày mai có thể dùng 198 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 11, type = 2, recharge_id = 5, desc = "Ngày mai có thể dùng 328 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
mapArray:push({ id = 12, type = 2, recharge_id = 6, desc = "Ngày mai có thể dùng 648 Nguyên tệ nạp sử dụng thu được nguyên bảo cùng VIP điểm"})
return mapArray
