local mapArray = MEMapArray:new()
mapArray:push({ id = 1, star = 0, quality = 4, gem_open = 1, gem_max_level = 0, desc = "Không thể khảm bảo thạch", next_desc = "Thiên Thư đột phá 1 tinh khảm nạm 9 Cấp bảo thạch"})
mapArray:push({ id = 2, star = 1, quality = 4, gem_open = 1, gem_max_level = 9, desc = "Cao nhất khảm 9  Cấp bảo thạch", next_desc = "Thiên Thư đột phá 2 Tinh khảm nạm 12 Cấp bảo thạch"})
mapArray:push({ id = 3, star = 2, quality = 4, gem_open = 1, gem_max_level = 12, desc = "Cao nhất khảm 12 Cấp bảo thạch", next_desc = "Thiên Thư đột phá 3 Tinh khảm nạm 14 Cấp bảo thạch"})
mapArray:push({ id = 4, star = 3, quality = 4, gem_open = 1, gem_max_level = 14, desc = "Cao nhất khảm 14 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 5, star = 4, quality = 4, gem_open = 1, gem_max_level = 16, desc = "Cao nhất khảm 16 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 6, star = 5, quality = 4, gem_open = 1, gem_max_level = 18, desc = "Cao nhất khảm 18 Cấp bảo thạch", next_desc = ""})
mapArray:push({ id = 7, star = 0, quality = 5, gem_open = 1, gem_max_level = 0, desc = "Không thể khảm bảo thạch", next_desc = "Thiên Thư đột phá 1 tinh khảm nạm 9 Cấp bảo thạch"})
mapArray:push({ id = 8, star = 1, quality = 5, gem_open = 1, gem_max_level = 9, desc = "Cao nhất khảm 9 Cấp bảo thạch", next_desc = "Thiên Thư đột phá 2 Tinh khảm nạm 12 Cấp bảo thạch"})
mapArray:push({ id = 9, star = 2, quality = 5, gem_open = 1, gem_max_level = 12, desc = "Cao nhất khảm 12 Cấp bảo thạch", next_desc = "Thiên Thư đột phá 3 Tinh khảm nạm 14 Cấp bảo thạch"})
mapArray:push({ id = 10, star = 3, quality = 5, gem_open = 1, gem_max_level = 14, desc = "Cao nhất khảm 14 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 11, star = 4, quality = 5, gem_open = 1, gem_max_level = 16, desc = "Cao nhất khảm 16 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 12, star = 5, quality = 5, gem_open = 1, gem_max_level = 18, desc = "Cao nhất khảm 18 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 13, star = 6, quality = 5, gem_open = 1, gem_max_level = 19, desc = "Cao nhất khảm 19 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 14, star = 7, quality = 5, gem_open = 1, gem_max_level = 21, desc = "Cao nhất khảm 21 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 15, star = 8, quality = 5, gem_open = 1, gem_max_level = 23, desc = "Cao nhất khảm 23 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 16, star = 9, quality = 5, gem_open = 1, gem_max_level = 24, desc = "Cao nhất khảm 24 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
mapArray:push({ id = 17, star = 10, quality = 5, gem_open = 1, gem_max_level = 25, desc = "Cao nhất khảm 25 Cấp bảo thạch", next_desc = "Thiên Thư sau khi đột phá khảm Đá Cao Hơn"})
return mapArray
