local mapArray = MEMapArray:new()
mapArray:push({ quality = 4, level = 20, count = 2, type = 1, value = 5})
mapArray:push({ quality = 4, level = 40, count = 2, type = 1, value = 10})
mapArray:push({ quality = 4, level = 60, count = 2, type = 1, value = 15})
mapArray:push({ quality = 4, level = 80, count = 2, type = 1, value = 20})
mapArray:push({ quality = 4, level = 100, count = 2, type = 1, value = 25})
mapArray:push({ quality = 4, level = 120, count = 2, type = 1, value = 30})
mapArray:push({ quality = 5, level = 20, count = 3, type = 1, value = 5})
mapArray:push({ quality = 5, level = 40, count = 3, type = 1, value = 10})
mapArray:push({ quality = 5, level = 60, count = 3, type = 1, value = 15})
mapArray:push({ quality = 5, level = 80, count = 3, type = 1, value = 20})
mapArray:push({ quality = 5, level = 100, count = 3, type = 1, value = 25})
mapArray:push({ quality = 5, level = 120, count = 3, type = 1, value = 30})
return mapArray
