local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-Card_group_pay_Game",
			UUID = "54b22291_3238_4d57_a019_43b53c24e769",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "bg_Panel-Card_group_pay_Game",
					UUID = "35db0ef8_20e8_41a2_910b_c1696dd7db86",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "527",
					ignoreSize = "False",
					name = "bg",
					opacity = "100",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/common/bg_w2.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 310,
					},
					width = "906",
					ZOrder = "1",
				},
				{
					controlID = "biaoti_Panel-Card_group_pay_Game",
					UUID = "c7806c4c_2e45_4865_9b31_165e4fbd87e0",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "86",
					ignoreSize = "True",
					name = "biaoti",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/common/bg_gongxi.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 576,
					},
					width = "417",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "yjkz_biaoti_Panel-Card_group_pay_Game",
							UUID = "a58ef110_d451_437b_ace3_c7163d8649b8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "69",
							ignoreSize = "True",
							name = "yjkz",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/img_yjkz.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -8,
							},
							width = "225",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Card1_Panel-Card_group_pay_Game",
					UUID = "96e1c2d7_04bf_49b9_b8a5_7965fab88904",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "431",
					ignoreSize = "True",
					name = "Card1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/bg_yueka1.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 300,
						PositionY = 309,
					},
					width = "339",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Btn_get_Card1_Panel-Card_group_pay_Game",
							UUID = "20b04b98_4b53_4cde_be81_51191e34adda",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							disabled = "ui_new/pay/btn_lingqu2.png",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Btn_get",
							normal = "ui_new/pay/btn_lingqu.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -65,
								PositionY = -149,
							},
							UItype = "Button",
							visible = "False",
							width = "156",
							ZOrder = "1",
						},
						{
							controlID = "Btn_buy_Card1_Panel-Card_group_pay_Game",
							UUID = "5e7d52b9_f1e0_4f1b_b25b_341368aa416c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Btn_buy",
							normal = "ui_new/pay/btn_buy.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -135,
							},
							UItype = "Button",
							visible = "False",
							width = "156",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_newprice_bg_Btn_buy_Card1_Panel-Card_group_pay_Game",
									UUID = "400dff26_c27f_405b_ac22_6eccccab0eea",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "24",
									ignoreSize = "True",
									name = "img_newprice_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/shop/bg_shopping_price.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 3,
										PositionY = -46,
									},
									width = "142",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "img_res_icon_img_newprice_bg_Btn_buy_Card1_Panel-Card_group_pay_Game",
											UUID = "2aba8518_7b1d_4c4d_9ae1_445548617163",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "33",
											ignoreSize = "True",
											name = "img_res_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/pay/VIP_rmb.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -51,
											},
											width = "26",
											ZOrder = "1",
										},
										{
											controlID = "txt_price_img_newprice_bg_Btn_buy_Card1_Panel-Card_group_pay_Game",
											UUID = "94e1b118_b529_4894_bc4c_537a74e2168a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "txt_price",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "30",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 10,
											},
											width = "30",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Btn_chongzhi_Card1_Panel-Card_group_pay_Game",
							UUID = "12f1d381_f3b8_47d9_9bb9_f83765269888",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Btn_chongzhi",
							normal = "ui_new/pay/VIP_chongzhi.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -149,
							},
							UItype = "Button",
							visible = "False",
							width = "156",
							ZOrder = "1",
						},
						{
							controlID = "txt_day_Card1_Panel-Card_group_pay_Game",
							UUID = "b2975b2a_5a43_465a_bc40_cc80cea0ffd7",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "24",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "32",
							ignoreSize = "True",
							name = "txt_day",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "持续 30 天",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -82,
							},
							width = "117",
							ZOrder = "1",
						},
						{
							controlID = "Img_morepay_Card1_Panel-Card_group_pay_Game",
							UUID = "a529b1ce_3069_4caf_8edc_202abd507f05",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "28",
							ignoreSize = "True",
							name = "Img_morepay",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/img_zcz.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 40,
							},
							width = "234",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_Card_1_Img_morepay_Card1_Panel-Card_group_pay_Game",
									UUID = "4a02ce17_ae28_4235_98ab_3176647bff03",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FFFF4044",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "Label_Card_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "300",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 23,
										PositionY = 1,
									},
									width = "46",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Img_jihuo_Card1_Panel-Card_group_pay_Game",
							UUID = "8a027dcb_42b9_44d4_ae32_d4f31354c4c1",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "67",
							ignoreSize = "True",
							name = "Img_jihuo",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/icon_jihuo.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 110,
								PositionY = 165,
							},
							width = "74",
							ZOrder = "1",
						},
						{
							controlID = "Btn_got_Card1_Panel-Card_group_pay_Game",
							UUID = "5442d2a2_e6f2_4cf2_897a_2e2a22fd7dfd",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							disabled = "ui_new/pay/btn_lingqu2.png",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "72",
							ignoreSize = "True",
							name = "Btn_got",
							normal = "ui_new/pay/btn_lingqu2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -65,
								PositionY = -149,
							},
							UItype = "Button",
							width = "158",
							ZOrder = "1",
						},
						{
							controlID = "btn_xufei_Card1_Panel-Card_group_pay_Game",
							UUID = "c290fdab_afa1_40b3_90ae_e2df4936db02",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "btn_xufei",
							normal = "ui_new/pay/btn_xufei.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 81,
								PositionY = -150,
							},
							UItype = "Button",
							width = "127",
							ZOrder = "1",
						},
						{
							controlID = "img_sanbei_Card1_Panel-Card_group_pay_Game",
							UUID = "6141e57a_e87a_49ea_8bdb_c0c898a0fe85",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "57",
							ignoreSize = "True",
							name = "img_sanbei",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/img_sanbei.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 122,
								PositionY = 42,
							},
							width = "57",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Card2_Panel-Card_group_pay_Game",
					UUID = "2b6adac5_3804_4e63_b635_b291fd4859f1",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "431",
					ignoreSize = "True",
					name = "Card2",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/bg_yueka2.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 660,
						PositionY = 309,
					},
					width = "339",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Btn_get_Card2_Panel-Card_group_pay_Game",
							UUID = "7da3ec99_0292_4e65_8e08_0cb0f9b145ab",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							disabled = "ui_new/pay/btn_lingqu2.png",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Btn_get",
							normal = "ui_new/pay/btn_lingqu.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -65,
								PositionY = -149,
							},
							UItype = "Button",
							width = "156",
							ZOrder = "1",
						},
						{
							controlID = "Btn_buy_Card2_Panel-Card_group_pay_Game",
							UUID = "7305efee_ab19_4aad_8812_a3c2eecf1452",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Btn_buy",
							normal = "ui_new/pay/btn_buy.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -135,
							},
							UItype = "Button",
							width = "156",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_newprice_bg_Btn_buy_Card2_Panel-Card_group_pay_Game",
									UUID = "a243f584_b4ea_406f_81ab_302e5083531f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "24",
									ignoreSize = "True",
									name = "img_newprice_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/shop/bg_shopping_price.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 3,
										PositionY = -46,
									},
									width = "142",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "img_res_icon_img_newprice_bg_Btn_buy_Card2_Panel-Card_group_pay_Game",
											UUID = "c1b941e4_e8af_46b0_83c7_4c99f5979c28",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "33",
											ignoreSize = "True",
											name = "img_res_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/pay/VIP_rmb.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -51,
											},
											width = "26",
											ZOrder = "1",
										},
										{
											controlID = "txt_price_img_newprice_bg_Btn_buy_Card2_Panel-Card_group_pay_Game",
											UUID = "0295a70c_968b_428b_a018_6be99aa52cd2",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "txt_price",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "30",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 10,
											},
											width = "30",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Btn_chongzhi_Card2_Panel-Card_group_pay_Game",
							UUID = "d0be80bf_ea62_4c7b_850e_d1679d5bf0e2",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Btn_chongzhi",
							normal = "ui_new/pay/VIP_chongzhi.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -149,
							},
							UItype = "Button",
							width = "156",
							ZOrder = "1",
						},
						{
							controlID = "txt_day_Card2_Panel-Card_group_pay_Game",
							UUID = "34336d68_2d7d_4143_9839_b10a6468759d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "24",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "32",
							ignoreSize = "True",
							name = "txt_day",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "持续 30 天",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -82,
							},
							width = "117",
							ZOrder = "1",
						},
						{
							controlID = "Img_morepay_Card2_Panel-Card_group_pay_Game",
							UUID = "0bc8856c_87c9_4530_b594_7e16d03c1eb6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "28",
							ignoreSize = "True",
							name = "Img_morepay",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/img_zcz.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 46,
							},
							width = "234",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_Card_1_Img_morepay_Card2_Panel-Card_group_pay_Game",
									UUID = "8176bbd9_6e8f_4d89_a6fb_d8d7faff9e4c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FFFF4044",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "Label_Card_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "1200",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 23,
										PositionY = 1,
									},
									width = "61",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Img_jihuo_Card2_Panel-Card_group_pay_Game",
							UUID = "caf1452a_8018_42d1_8b01_e23b9bbf932e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "67",
							ignoreSize = "True",
							name = "Img_jihuo",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/icon_jihuo.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 110,
								PositionY = 165,
							},
							width = "74",
							ZOrder = "1",
						},
						{
							controlID = "Btn_got_Card2_Panel-Card_group_pay_Game",
							UUID = "a2d6d737_1472_4e9f_9013_b9bacdbab329",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							disabled = "ui_new/pay/btn_lingqu2.png",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "72",
							ignoreSize = "True",
							name = "Btn_got",
							normal = "ui_new/pay/btn_lingqu2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -65,
								PositionY = -149,
							},
							UItype = "Button",
							width = "158",
							ZOrder = "1",
						},
						{
							controlID = "btn_xufei_Card2_Panel-Card_group_pay_Game",
							UUID = "3b4b328c_8660_4855_aee2_95bcaf7a89fa",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "btn_xufei",
							normal = "ui_new/pay/btn_xufei.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 81,
								PositionY = -150,
							},
							UItype = "Button",
							width = "127",
							ZOrder = "1",
						},
						{
							controlID = "img_sanbei_Card2_Panel-Card_group_pay_Game",
							UUID = "385854ea_b0b5_4a09_b23a_950030c9ad5c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "57",
							ignoreSize = "True",
							name = "img_sanbei",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/img_sanbei.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 122,
								PositionY = 47,
							},
							width = "57",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Btn_Close_Panel-Card_group_pay_Game",
					UUID = "8785c476_1bcf_4ca0_bf1a_efeb8f483dd7",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "54",
					HitType = 
					{
						nHitType = 1,
						nXpos = -40,
						nYpos = -43,
						nHitWidth = 150,
						nHitHeight = 150
					},
					ignoreSize = "True",
					name = "Btn_Close",
					normal = "ui_new/common/common_close2_icon.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 910,
						PositionY = 547,
					},
					UItype = "Button",
					width = "54",
					ZOrder = "1",
				},
				{
					controlID = "bg_shuoming_Panel-Card_group_pay_Game",
					UUID = "47a20b76_9a32_40c8_b7cd_331baea58e1e",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "24",
					ignoreSize = "False",
					name = "bg_shuoming",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/bg_hong.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 56,
					},
					visible = "False",
					width = "360",
					ZOrder = "1",
				},
				{
					controlID = "img_yijihuo_Panel-Card_group_pay_Game",
					UUID = "5787bb3c_877f_43af_a677_be240a82b35d",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "336",
					ignoreSize = "True",
					name = "img_yijihuo",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/shuangbuff_yijh.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 865,
						PositionY = 313,
					},
					width = "89",
					ZOrder = "1",
				},
				{
					controlID = "img_weijihuo_Panel-Card_group_pay_Game",
					UUID = "8568d7b1_daa0_487d_b884_588d1fb7f74a",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "336",
					ignoreSize = "True",
					name = "img_weijihuo",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/shuangbuff_weijh.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 865,
						PositionY = 313,
					},
					width = "89",
					ZOrder = "1",
				},
				{
					controlID = "img_yueka_Panel-Card_group_pay_Game",
					UUID = "6fb3856b_deba_4dde_ba96_50df507161cb",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "245",
					ignoreSize = "True",
					name = "img_yueka",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/img_yueka.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 80,
						PositionY = 446,
					},
					width = "60",
					ZOrder = "1",
				},
				{
					controlID = "panel_sykd_Panel-Card_group_pay_Game",
					UUID = "1df5182e_be47_44bd_9c2b_9fe8ba5b48d2",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "77",
					ignoreSize = "False",
					name = "panel_sykd",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 180,
						PositionY = 22,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "600",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "img_txtbg_panel_sykd_Panel-Card_group_pay_Game",
							UUID = "00935b7f_f08d_4207_b21b_79217c54eb6b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "58",
							ignoreSize = "False",
							name = "img_txtbg",
							opacity = "200",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/lunjian/bg_name2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 296,
								PositionY = 38,
							},
							width = "610",
							ZOrder = "1",
						},
						{
							controlID = "txt_shuoming_panel_sykd_Panel-Card_group_pay_Game",
							UUID = "9ea9c9e8_f55e_433a_b5f2_a53efea60a60",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "20",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "26",
							ignoreSize = "True",
							name = "txt_shuoming",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "并且有概率获得限当日使用的30元充值赠劵",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 416,
								PositionY = 24,
							},
							width = "387",
							ZOrder = "1",
						},
						{
							controlID = "txt_ewaibuff_panel_sykd_Panel-Card_group_pay_Game",
							UUID = "c8f528dc_814b_4100_a666_13894d5c09a8",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFEFF8C",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "29",
							ignoreSize = "True",
							name = "txt_ewaibuff",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "激活双月卡每天可额外领取30元银票x1",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 416,
								PositionY = 41,
							},
							width = "382",
							ZOrder = "1",
						},
						{
							controlID = "panel_reward_panel_sykd_Panel-Card_group_pay_Game",
							UUID = "2e8f39b6_1613_40a9_9f56_5f99760edd3f",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "False",
							name = "panel_reward",
							scaleX = "0.5",
							scaleY = "0.5",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 422,
								PositionY = 4,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "140",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "bg_icon_panel_reward_panel_sykd_Panel-Card_group_pay_Game",
									UUID = "671d345c_7728_4644_a6ee_0dbfe7b70b0b",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "130",
									ignoreSize = "True",
									name = "bg_icon",
									normal = "ui_new/common/icon_bg/cheng_124.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										
									},
									UItype = "Button",
									width = "130",
									ZOrder = "1",
								},
								{
									controlID = "img_icon_panel_reward_panel_sykd_Panel-Card_group_pay_Game",
									UUID = "25db6df4_f59e_4f14_941b_b646d9fffc5f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "110",
									ignoreSize = "True",
									name = "img_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/item/30228.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 62,
										PositionY = 63,
									},
									width = "110",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_get_panel_sykd_Panel-Card_group_pay_Game",
							UUID = "9039fb64_8284_4ff0_b954_0eefa92f26da",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							disabled = "ui_new/pay/btn_lingqu4.png",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "67",
							ignoreSize = "True",
							name = "btn_get",
							normal = "ui_new/pay/btn_lingqu3.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 552,
								PositionY = 38,
							},
							UItype = "Button",
							width = "121",
							ZOrder = "1",
						},
						{
							controlID = "img_tips_panel_sykd_Panel-Card_group_pay_Game",
							UUID = "eae8da03_bdc2_40eb_a6d5_442a4133db5e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "True",
							name = "img_tips",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/img_syka.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 476,
								PositionY = 59,
							},
							width = "40",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/common/bg_w2.png",
			"ui_new/common/bg_gongxi.png",
			"ui_new/pay/img_yjkz.png",
			"ui_new/pay/bg_yueka1.png",
			"ui_new/pay/btn_lingqu.png",
			"ui_new/pay/btn_lingqu2.png",
			"ui_new/pay/btn_buy.png",
			"ui_new/shop/bg_shopping_price.png",
			"ui_new/pay/VIP_rmb.png",
			"ui_new/pay/VIP_chongzhi.png",
			"ui_new/pay/img_zcz.png",
			"ui_new/pay/icon_jihuo.png",
			"ui_new/pay/btn_xufei.png",
			"ui_new/pay/img_sanbei.png",
			"ui_new/pay/bg_yueka2.png",
			"ui_new/common/common_close2_icon.png",
			"ui_new/pay/bg_hong.png",
			"ui_new/pay/shuangbuff_yijh.png",
			"ui_new/pay/shuangbuff_weijh.png",
			"ui_new/pay/img_yueka.png",
			"ui_new/lunjian/bg_name2.png",
			"ui_new/common/icon_bg/cheng_124.png",
			"icon/item/30228.png",
			"ui_new/pay/btn_lingqu3.png",
			"ui_new/pay/btn_lingqu4.png",
			"ui_new/pay/img_syka.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

