local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-GuiBing_group_pay_Game",
			UUID = "b642d128_26cf_49f1_9ed1_9c4815fd9722",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "bg_Panel-GuiBing_group_pay_Game",
					UUID = "f1cb326b_bfd3_483c_8a67_927eaa59fe09",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "483",
					ignoreSize = "False",
					name = "bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/common/bg_h.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					width = "850",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "title_bg_Panel-GuiBing_group_pay_Game",
							UUID = "20c966f6_5256_450f_8144_a44dd5d1cf0b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "87",
							ignoreSize = "False",
							name = "title",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/common/bg_biaoti3.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -1,
								PositionY = 232,
							},
							width = "854",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_GuiBing_1_title_bg_Panel-GuiBing_group_pay_Game",
									UUID = "33072715_ad33_4fa7_9616_7fb5916ffaac",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "63",
									ignoreSize = "True",
									name = "Image_GuiBing_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_guibing.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 19,
									},
									width = "256",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_close_bg_Panel-GuiBing_group_pay_Game",
							UUID = "6cc82c4b_3674_4dca_84a2_9d51c865aad6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "54",
							ignoreSize = "True",
							name = "btn_close",
							normal = "ui_new/common/common_close3_icon.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 388,
								PositionY = 249,
							},
							UItype = "Button",
							width = "54",
							ZOrder = "1",
						},
						{
							controlID = "bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
							UUID = "ae6aebe6_cb13_4605_b196_e4e0c2835828",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "323",
							ignoreSize = "False",
							name = "bg_xiangxi",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/common/bg_h2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 156,
								PositionY = 24,
							},
							width = "470",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "title_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "f9f73d56_17f6_4fc3_bb1f_75e0ee4c499a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "50",
									ignoreSize = "True",
									name = "title",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_title.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 160,
									},
									width = "414",
									ZOrder = "1",
								},
								{
									controlID = "01_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "c3e0af93_0a8a_405b_940e_a50bd8a69d2e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "46",
									ignoreSize = "True",
									name = "01",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_g01.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -194,
										PositionY = 97,
									},
									visible = "False",
									width = "46",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "biaoti_01_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
											UUID = "aace0bcc_1d9a_48bc_872c_409007c11f29",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFC20B5D",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "biaoti",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "专属通道",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = 12,
											},
											width = "99",
											ZOrder = "1",
										},
										{
											controlID = "shuoming_01_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
											UUID = "271cc040_2012_4964_984b_5eca4c1a1650",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF3D3D3D",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "26",
											ignoreSize = "True",
											name = "shuoming",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "这里有专属的美女客服服务哦~",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = -16,
											},
											width = "275",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "02_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "5048725e_d5b6_4fa2_aad5_33dea6656fe7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "46",
									ignoreSize = "True",
									name = "02",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_g02.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -194,
										PositionY = 27,
									},
									visible = "False",
									width = "46",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "biaoti_02_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
											UUID = "09c173dc_59e1_44c0_b182_6a6c22d55e30",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFC20B5D",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "biaoti",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "专属通道",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = 12,
											},
											width = "99",
											ZOrder = "1",
										},
										{
											controlID = "shuoming_02_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
											UUID = "16852aa9_fdfa_46f9_ade0_36230a90c2f2",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF3D3D3D",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "26",
											ignoreSize = "True",
											name = "shuoming",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "这里有专属的美女客服服务哦~",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = -16,
											},
											width = "275",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "03_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "fb0f6d7c_eea4_47d5_b623_37621f66c26b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "46",
									ignoreSize = "True",
									name = "03",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_g03.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -194,
										PositionY = -43,
									},
									visible = "False",
									width = "46",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "biaoti_03_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
											UUID = "72c62a7d_a155_4521_a622_b9f575f862fc",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFC20B5D",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "biaoti",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "专属通道",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = 12,
											},
											width = "99",
											ZOrder = "1",
										},
										{
											controlID = "shuoming_03_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
											UUID = "11ad7bd6_3f5b_42c7_bcac_25b38280ab71",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF3D3D3D",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "26",
											ignoreSize = "True",
											name = "shuoming",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "这里有专属的美女客服服务哦~",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = -16,
											},
											width = "275",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "04_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "48086491_6b43_47be_b5a1_749e77ef62bb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "46",
									ignoreSize = "True",
									name = "04",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_g04.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -194,
										PositionY = -113,
									},
									visible = "False",
									width = "46",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "biaoti_04_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
											UUID = "be9f7148_befd_49e8_ba4b_cafbef4c789e",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFC20B5D",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "biaoti",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "专属通道",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = 12,
											},
											width = "99",
											ZOrder = "1",
										},
										{
											controlID = "shuoming_04_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
											UUID = "6a10bb4a_0890_4a4f_bd2a_75cb67d13c15",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF3D3D3D",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "26",
											ignoreSize = "True",
											name = "shuoming",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "这里有专属的美女客服服务哦~",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = -16,
											},
											width = "275",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "img_erweima_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "cc615cbf_0be8_440b_9f62_1fd25e3cd5bc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "257",
									ignoreSize = "True",
									name = "img_erweima",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_erweima.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -14,
									},
									width = "409",
									ZOrder = "1",
								},
								{
									controlID = "effect_1_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "1ba69783_12ed_4b49_a91b_b14a648e8e86",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "400",
									ignoreSize = "False",
									name = "effect_1",
									scaleX = "0.2",
									scaleY = "0.2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -154,
										PositionY = 67,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "400",
									ZOrder = "1",
								},
								{
									controlID = "effect_2_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "ec7d7e21_f2f8_4f47_ba70_01ffbb5294d7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "400",
									ignoreSize = "False",
									name = "effect_2",
									scaleX = "0.2",
									scaleY = "0.2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 157,
										PositionY = 67,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "400",
									ZOrder = "1",
								},
								{
									controlID = "effect_3_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "89316929_2c93_4341_9e07_4c08863c19f7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "400",
									ignoreSize = "False",
									name = "effect_3",
									scaleX = "0.2",
									scaleY = "0.2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -156,
										PositionY = -69,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "400",
									ZOrder = "1",
								},
								{
									controlID = "effect_4_bg_xiangxi_bg_Panel-GuiBing_group_pay_Game",
									UUID = "85b89b8e_e3d3_44ad_b282_176f5deeaa0b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "400",
									ignoreSize = "False",
									name = "effect_4",
									scaleX = "0.2",
									scaleY = "0.2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 158,
										PositionY = -69,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "400",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "txt_tishi_bg_Panel-GuiBing_group_pay_Game",
							UUID = "28833cbc_9609_4110_b10c_f835448cecf3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "METextArea",
							ColorMixing = "#FF3D3D3D",
							dstBlendFunc = "771",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "18",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							hAlignment = "0",
							height = "66",
							ignoreSize = "False",
							name = "txt_tishi",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "主人，您已经升级成为我们的贵宾用户,加专属美女客服QQ，享终身VIP服务。",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -240,
								PositionY = 168,
							},
							vAlignment = "0",
							width = "312",
							ZOrder = "1",
						},
						{
							controlID = "img_meinv_bg_Panel-GuiBing_group_pay_Game",
							UUID = "5b29ccea_66b6_4752_8884_65b7993cc710",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "233",
							ignoreSize = "True",
							name = "img_meinv",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui_new/pay/img_meinv.jpg",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -243,
								PositionY = 24,
							},
							width = "233",
							ZOrder = "1",
						},
						{
							controlID = "Label_GuiBing_1_bg_Panel-GuiBing_group_pay_Game",
							UUID = "7f435d00_12d2_4d7a_a149_cccfba1061f5",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF3D3D3D",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "29",
							ignoreSize = "True",
							name = "Label_GuiBing_1",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "美女客服QQ：",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -380,
								PositionY = -114,
							},
							width = "140",
							ZOrder = "1",
						},
						{
							controlID = "txt_qq_bg_Panel-GuiBing_group_pay_Game",
							UUID = "f8e15f33_4c24_45db_8e7c_13fe7e02eaa8",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFC20B5D",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "28",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "37",
							ignoreSize = "True",
							name = "txt_qq",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "800062051",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -238,
								PositionY = -115,
							},
							width = "146",
							ZOrder = "1",
						},
						{
							controlID = "btn_djfz_bg_Panel-GuiBing_group_pay_Game",
							UUID = "f9d3443a_6689_4f44_8c93_40c96ea45d10",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "btn_djfz",
							normal = "ui_new/pay/btn_djfz.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -243,
								PositionY = -175,
							},
							UItype = "Button",
							width = "156",
							ZOrder = "1",
						},
						{
							controlID = "img_input_bg_bg_Panel-GuiBing_group_pay_Game",
							UUID = "912bce12_9eba_4bfe_a4ea_dcabefc2e97e",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "42",
							ignoreSize = "True",
							name = "img_input_bg",
							sizepercentx = "23",
							sizepercenty = "8",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/bg_input.png",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 113,
								PositionY = -179,
							},
							width = "197",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "input_qq_img_input_bg_bg_Panel-GuiBing_group_pay_Game",
									UUID = "8b4ebd92_12d0_4442_b1ef_3b0df9273793",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									classname = "METextField",
									ColorMixing = "#FF3D3D3D",
									CursorEnabled = "True",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontSize = "22",
									hAlignment = "0",
									height = "23",
									HitType = 
									{
										nHitType = 1,
										nXpos = -30,
										nYpos = -15,
										nHitWidth = 220,
										nHitHeight = 50
									},
									ignoreSize = "False",
									KeyBoradType = "1",
									maxLengthEnable = "True;maxLength:20",
									name = "input_qq",
									passwordEnable = "False",
									placeHolder = "点击输入需要查找的帮派ID",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 11,
										PositionY = -11,
									},
									vAlignment = "0",
									width = "180",
									ZOrder = "9",
								},
							},
						},
						{
							controlID = "btn_tj_bg_Panel-GuiBing_group_pay_Game",
							UUID = "7c260602_5112_4d9f_bdc3_cb7d3c8df68f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "49",
							ignoreSize = "True",
							name = "btn_tj",
							normal = "ui_new/pay/btn_tj.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 355,
								PositionY = -180,
							},
							UItype = "Button",
							width = "89",
							ZOrder = "1",
						},
						{
							controlID = "btn_gg_bg_Panel-GuiBing_group_pay_Game",
							UUID = "90f00005_b00b_4714_acee_ea798e32e73f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "49",
							ignoreSize = "True",
							name = "btn_gg",
							normal = "ui_new/pay/btn_gg.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 356,
								PositionY = -180,
							},
							UItype = "Button",
							visible = "False",
							width = "89",
							ZOrder = "1",
						},
						{
							controlID = "TextArea_GuiBing_1_bg_Panel-GuiBing_group_pay_Game",
							UUID = "72e4ba6d_ffa5_4e59_9ec2_d86020686537",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "METextArea",
							ColorMixing = "#FF3D3D3D",
							dstBlendFunc = "771",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "17",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							hAlignment = "0",
							height = "60",
							ignoreSize = "False",
							name = "TextArea_GuiBing_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "如您不便，请留下QQ：我们将第一时间联系到您",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 15,
								PositionY = -184,
							},
							vAlignment = "0",
							width = "190",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/common/bg_h.png",
			"ui_new/common/bg_biaoti3.png",
			"ui_new/pay/img_guibing.png",
			"ui_new/common/common_close3_icon.png",
			"ui_new/common/bg_h2.png",
			"ui_new/pay/img_title.png",
			"ui_new/pay/img_g01.png",
			"ui_new/pay/img_g02.png",
			"ui_new/pay/img_g03.png",
			"ui_new/pay/img_g04.png",
			"ui_new/pay/img_erweima.png",
			"ui_new/pay/img_meinv.jpg",
			"ui_new/pay/btn_djfz.png",
			"ui_new/pay/bg_input.png",
			"ui_new/pay/btn_tj.png",
			"ui_new/pay/btn_gg.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

