local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-PayLayer_group_pay_Game",
			UUID = "20c877e5_79c1_4c83_b6e9_bdb009dec05b",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "100",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "True",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "panel_content_Panel-PayLayer_group_pay_Game",
					UUID = "e2422cff_c9b7_447b_a7bf_76eb53add6f4",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_content",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "735d4b70_ba77_4d96_8d9f_008a31a2007c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "635",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/VIP_bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
							},
							width = "989",
							ZOrder = "1",
						},
						{
							controlID = "btn_close_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "120b9b6b_1c59_4e3c_b148_2d600b99ca33",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "65",
							ignoreSize = "True",
							name = "btn_close",
							normal = "ui_new/common/common_close_icon.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 923,
								PositionY = 493,
							},
							UItype = "Button",
							width = "65",
							ZOrder = "1",
						},
						{
							controlID = "bg2_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "ed89115e_7e52_4067_b137_79b1a050124a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "112",
							ignoreSize = "True",
							name = "bg2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/VIP_g1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 507,
							},
							width = "805",
							ZOrder = "1",
						},
						{
							controlID = "btn_vip_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "c30521fb_1a2e_4e34_8d81_9b48d78508b8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "METextButton",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "btn_vip",
							normal = "ui_new/pay/VIP_tequan.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							titlefontName = "宋体",
							titlefontSize = "24",
							titletext = " ",
							titletextColor = "#FFFFFFFF",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 199,
								PositionY = 503,
							},
							visible = "False",
							width = "156",
							ZOrder = "1",
						},
						{
							controlID = "node_vip_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "0e63f9b7_cc5a_49f2_a58d_0479221fcc92",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_vip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 220,
								PositionY = 405,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_curVip_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "4945d2b1_2165_465a_913e_bcad0b8c35d1",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o15",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 68,
										PositionY = 132,
									},
									width = "114",
									ZOrder = "1",
								},
								{
									controlID = "txt_needMoney_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "fb0072e1_b390_4c55_bf9b_ecf3e95da844",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_217.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_needMoney",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "500000",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 108,
										PositionY = 68,
									},
									width = "92",
									ZOrder = "1",
								},
								{
									controlID = "lb3_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "df9e9057_e511_4139_83c6_cbd5d124382c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb3",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "再充值",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 21,
										PositionY = 71,
									},
									width = "80",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "9e869cbe_7a0e_466a_bb5d_176ba8471b2e",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "即可成为",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 205,
										PositionY = 71,
									},
									width = "104",
									ZOrder = "1",
								},
								{
									controlID = "bg_bar_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "26ac914a_d4ec_474e_8d50_28b5116fbed1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "22",
									ignoreSize = "False",
									name = "bg_bar",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_jidudi.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 349,
										PositionY = 126,
									},
									width = "300",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "bar_value_bg_bar_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
											UUID = "a2c1d943_f67c_4e42_aa19_510fae611808",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MELoadingBar",
											direction = "0",
											dstBlendFunc = "771",
											height = "22",
											ignoreSize = "False",
											name = "bar_value",
											percent = "100",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texture = "ui_new/pay/VIP_jidu.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "300",
											ZOrder = "1",
										},
										{
											controlID = "txt_value_bg_bar_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
											UUID = "ec2744d9_9324_4021_8f68_5a772ecc641a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabelBMFont",
											dstBlendFunc = "771",
											fileNameData = "font/num_217.fnt",
											height = "27",
											ignoreSize = "True",
											name = "txt_value",
											scaleX = "0.7",
											scaleY = "0.7",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "10000",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 1,
											},
											width = "77",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "img_yuanbao_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "2f82f31f_ffef_4cd0_8dfe_ba15cfaecffb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "48",
									ignoreSize = "True",
									name = "img_yuanbao",
									scaleX = "0.8",
									scaleY = "0.8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/common/yuanbao2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 84,
										PositionY = 72,
									},
									width = "51",
									ZOrder = "1",
								},
								{
									controlID = "txt_nextVip_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "b72c718a_a6d4_4edd_80ca_7d2d3537b81d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 322,
										PositionY = 76,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "img_zunjingde_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "9ddf8b22_ec60_4cbb_ad53_42e1e26adf3a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "25",
									ignoreSize = "True",
									name = "img_zunjingde",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_w2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 20,
										PositionY = 126,
									},
									width = "71",
									ZOrder = "1",
								},
								{
									controlID = "img_curVip_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "01cf7d63_8b54_4d18_9df6_c8b3d88be333",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "img_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 117,
										PositionY = 132,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "img_nextVip_node_vip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "fa3bc2fa_c7a2_4278_b1ca_3539e902a47e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "img_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 346,
										PositionY = 76,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "node_notVip_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "207060cd_4272_40e3_86f3_3245648fe6ce",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_notVip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 75,
								PositionY = -703,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_needMoney_node_notVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "b7305313_447e_4692_b71b_83c2bb5eff01",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_14.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_needMoney",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "0",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 112,
									},
									width = "20",
									ZOrder = "1",
								},
								{
									controlID = "lb1_node_notVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "cb36bb6e_db1a_4796_a3db_ab923d21c05a",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "您不是VIP，充值",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 73,
									},
									width = "200",
									ZOrder = "1",
								},
								{
									controlID = "img_rmb_node_notVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "91c064ca_e631_403d_a48d_016654e3060f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "33",
									ignoreSize = "True",
									name = "img_rmb",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_rmb.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 97,
									},
									width = "26",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_notVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "bf7b7548_01b3_4807_b407_acfd914725bb",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "享受",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 137,
									},
									width = "55",
									ZOrder = "1",
								},
								{
									controlID = "txt_nextVip_node_notVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "aa5abafc_774b_4e24_82c9_5f9086671f1d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 191,
										PositionY = 4,
									},
									width = "69",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "c0faf3b4_0a23_434f_821c_5d403b2ddfe7",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_topVip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 355,
								PositionY = 476,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_vip_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "4e0e95d7_1a8c_48bb_ad3a_e205e0360d05",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "60",
									ignoreSize = "False",
									name = "Panel_vip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -116,
										PositionY = 22,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "450",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "img_zunjing_Panel_vip_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
											UUID = "f910938d_60e1_4851_8fba_d982e71ad55d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "25",
											ignoreSize = "True",
											name = "img_zunjing",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/pay/VIP_w2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												PositionY = 33,
											},
											width = "71",
											ZOrder = "1",
										},
										{
											controlID = "img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
											UUID = "6c9220e2_afe2_4bbd_9492_215de6c415c9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "22",
											ignoreSize = "False",
											name = "img_jindutiao",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/pay/VIP_jidudi.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 330,
												PositionY = 33,
											},
											width = "300",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "LoadingBar_vip_img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
													UUID = "506f0f0f_c30c_4a1d_9f8a_b684e82f85e3",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
													classname = "MELoadingBar",
													direction = "0",
													dstBlendFunc = "771",
													height = "22",
													ignoreSize = "False",
													name = "LoadingBar_vip",
													percent = "100",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texture = "ui_new/pay/VIP_jidu.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "300",
													ZOrder = "1",
												},
												{
													controlID = "txt_jindu_img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
													UUID = "44efc657_8b1a_4181_9c89_208b827de46c",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabelBMFont",
													dstBlendFunc = "771",
													fileNameData = "font/num_217.fnt",
													height = "27",
													ignoreSize = "True",
													name = "txt_jindu",
													scaleX = "0.7",
													scaleY = "0.7",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													text = "10000",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionY = 1,
													},
													width = "77",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "txt_curVip_Panel_vip_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
											UUID = "44aaeea1_9e61_4d60_8174_5f7a026dbf4c",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabelBMFont",
											dstBlendFunc = "771",
											fileNameData = "font/num_37.fnt",
											height = "27",
											ignoreSize = "True",
											name = "txt_curVip",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "o15",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 49,
												PositionY = 39,
											},
											width = "114",
											ZOrder = "1",
										},
										{
											controlID = "img_vip_Panel_vip_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
											UUID = "ed21a460_7ada_4400_bc7f_e4d2ef82b1af",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "64",
											ignoreSize = "True",
											name = "img_vip",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 98,
												PositionY = 39,
											},
											visible = "False",
											width = "64",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "img1_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "b65e02a7_9ab7_4356_96a9_115f52959fd4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "43",
									ignoreSize = "True",
									name = "img1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/cz_zz_word.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 86,
										PositionY = 2,
									},
									width = "65",
									ZOrder = "1",
								},
								{
									controlID = "txt_curVip_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "3ca97a5a_1a33_4ab2_a2e5_01edc14774fd",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 153,
										PositionY = 7,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "e081b1f1_b049_4820_8d68_06394e00e961",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "啦！",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 217,
										PositionY = 2,
									},
									width = "43",
									ZOrder = "1",
								},
								{
									controlID = "lb1_node_topVip_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "9afe26bb_242f_4961_a99c_a96b7906d72c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "您已经是",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -11,
										PositionY = 2,
									},
									width = "107",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "img_fisrtPay_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "8737dbc8_4dd6_48fc_9e81_873ea32f2b69",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "52",
							ignoreSize = "True",
							name = "img_fisrtPay",
							scaleX = "0.6",
							scaleY = "0.6",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/VIP_shouchongfanbei.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 199,
								PositionY = 556,
							},
							visible = "False",
							width = "168",
							ZOrder = "1",
						},
						{
							controlID = "panel_scrollview_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "3dc4d355_2a8d_4fcb_90ec_c3cee58d7362",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "1",
							dstBlendFunc = "771",
							height = "390",
							ignoreSize = "False",
							innerHeight = "390",
							innerWidth = "834",
							name = "panel_scrollview",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 62,
								PositionY = 60,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "834",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "panel_recharge_panel_scrollview_panel_content_Panel-PayLayer_group_pay_Game",
									UUID = "38e17cce_767c_49f8_b041_2296131f270c",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "390",
									ignoreSize = "False",
									name = "panel_recharge",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "810",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "img_role_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "67e2669a_78b5_4a23_8593_be3210f85898",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "408",
							ignoreSize = "True",
							name = "img_role",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/zhongling.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 70,
								PositionY = 236,
							},
							visible = "False",
							width = "285",
							ZOrder = "1",
						},
						{
							controlID = "txt_wenzi_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "26b063ca_0edc_44e0_b0fe_0b2fc4653655",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							ColorMixing = "#00FFFFFF",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFC75E34",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "20",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "26",
							ignoreSize = "True",
							name = "txt_wenzi",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "每种金额的元宝在初次购买时都将获得三倍返利！",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 44,
							},
							width = "434",
							ZOrder = "1",
						},
						{
							controlID = "img_mengceng_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "f93a1761_01d2_4e65_b00a_29ee4eae2edc",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "29",
							ignoreSize = "True",
							name = "img_mengceng",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/img_mengceng.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 478,
								PositionY = 74,
							},
							width = "830",
							ZOrder = "1",
						},
						{
							controlID = "btn_zengquanbag_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "f5c907d8_5916_4e4b_8e72_ade4068a6c77",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "53",
							HitType = 
							{
								nHitType = 1,
								nXpos = -9,
								nYpos = -9,
								nHitWidth = 125,
								nHitHeight = 72
							},
							ignoreSize = "True",
							name = "btn_zengquanbag",
							normal = "ui_new/pay/btn_zengquanbao.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 780,
								PositionY = 477,
							},
							UItype = "Button",
							width = "99",
							ZOrder = "1",
						},
						{
							controlID = "btn_qiandao_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "77e23793_6335_434a_bb14_7af78c0cc4da",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "METextButton",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "53",
							ignoreSize = "True",
							name = "btn_qiandao",
							normal = "ui_new/pay/btn_qiandao.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							titlefontName = "宋体",
							titlefontSize = "24",
							titletext = " ",
							titletextColor = "#FFFFFFFF",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 780,
								PositionY = 534,
							},
							width = "99",
							ZOrder = "1",
						},
						{
							controlID = "btn_cz_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "d033a5a9_fb49_4b5b_8b48_5589591b6a68",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_cz",
							normal = "ui_new/pay/btn_cz2.png",
							pressed = "ui_new/pay/btn_cz2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 480,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
						{
							controlID = "btn_tq_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "d1a8c8d5_c03a_4eab_9dd0_a5b0fc7f9f1c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_tq",
							normal = "ui_new/pay/btn_tq1.png",
							pressed = "ui_new/pay/btn_tq2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 375,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
						{
							controlID = "btn_sc_panel_content_Panel-PayLayer_group_pay_Game",
							UUID = "77dcaa39_a10b_4532_b9d6_3144fd3bb3db",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_sc",
							normal = "ui_new/pay/btn_sc1.png",
							pressed = "ui_new/pay/btn_sc2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 270,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/pay/VIP_bg.png",
			"ui_new/common/common_close_icon.png",
			"ui_new/pay/VIP_g1.png",
			"ui_new/pay/VIP_tequan.png",
			"ui_new/pay/VIP_jidudi.png",
			"ui_new/pay/VIP_jidu.png",
			"ui_new/common/yuanbao2.png",
			"ui_new/pay/VIP_w2.png",
			"ui_new/pay/VIP_rmb.png",
			"ui_new/pay/cz_zz_word.png",
			"ui_new/pay/VIP_shouchongfanbei.png",
			"ui_new/pay/zhongling.png",
			"ui_new/pay/img_mengceng.png",
			"ui_new/pay/btn_zengquanbao.png",
			"ui_new/pay/btn_qiandao.png",
			"ui_new/pay/btn_cz2.png",
			"ui_new/pay/btn_tq2.png",
			"ui_new/pay/btn_tq1.png",
			"ui_new/pay/btn_sc2.png",
			"ui_new/pay/btn_sc1.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

