local t = 
{
	version = 1,
	components = 
	{
		
		{
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "340",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "210",
			ZOrder = "1",
			components = 
			{
				
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "154",
					ignoreSize = "True",
					name = "bg",
					normal = "ui_new/pay/VIP_chongzhidi.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 126,
						PositionY = 74,
					},
					UItype = "Button",
					width = "271",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "100",
					ignoreSize = "True",
					name = "img_icon",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/VIP_yb.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 55,
						PositionY = 73,
					},
					width = "111",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					classname = "MELabel",
					compPath = "luacomponents.common.MEIconLabel",
					dstBlendFunc = "771",
					FontColor = "#FFFFFFFF",
					fontName = "simhei",
					fontShadow = 
					{
						IsShadow = false,
						ShadowColor = "#FFFFFFFF",
						ShadowAlpha = 255,
						OffsetX = 0,
						OffsetY = 0,
					},
					fontSize = "24",
					fontStroke = 
					{
						IsStroke = false,
						StrokeColor = "#FFE6E6E6",
						StrokeSize = 1,
					},
					height = "24",
					IconLayout = "1",
					ignoreSize = "True",
					name = "txt_sycee",
					nGap = "0",
					nIconAlign = "1",
					nTextAlign = "1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					text = "20",
					touchAble = "False",
					touchScaleEnable = "False",
					UILayoutViewModel = 
					{
						PositionX = 186,
						PositionY = 103,
					},
					width = "24",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					classname = "MELabel",
					ColorMixing = "#FFFFFDBA",
					compPath = "luacomponents.common.MEIconLabel",
					dstBlendFunc = "771",
					FontColor = "#FFFFFFFF",
					fontName = "simhei",
					fontShadow = 
					{
						IsShadow = false,
						ShadowColor = "#FFFFFFFF",
						ShadowAlpha = 255,
						OffsetX = 0,
						OffsetY = 0,
					},
					fontSize = "30",
					fontStroke = 
					{
						IsStroke = false,
						StrokeColor = "#FFE6E6E6",
						StrokeSize = 1,
					},
					height = "30",
					IconLayout = "1",
					ignoreSize = "True",
					name = "txt_price",
					nGap = "0",
					nIconAlign = "1",
					nTextAlign = "1",
					scaleX = "0.8",
					scaleY = "0.8",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					text = "9000",
					touchAble = "False",
					touchScaleEnable = "False",
					UILayoutViewModel = 
					{
						PositionX = 186,
						PositionY = 55,
					},
					width = "60",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "33",
					ignoreSize = "True",
					name = "img_rmb",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/VIP_rmb.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 128,
						PositionY = 55,
					},
					width = "26",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "50",
					ignoreSize = "True",
					name = "Img_yuanbao",
					scaleX = "0.8",
					scaleY = "0.8",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/common/icon_sycee.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 128,
						PositionY = 104,
					},
					width = "55",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "53",
					ignoreSize = "True",
					name = "img_fisrtPay",
					scaleX = "0.8",
					scaleY = "0.8",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/vip60.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 35,
						PositionY = 132,
					},
					width = "111",
					ZOrder = "1",
					components = 
					{
						
						{
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabelBMFont",
							dstBlendFunc = "771",
							fileNameData = "font/num_217.fnt",
							height = "27",
							ignoreSize = "True",
							name = "txt_num",
							rotation = "-12.5",
							scaleX = "0.9",
							scaleY = "0.9",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							text = "50000",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 12,
								PositionY = 4,
							},
							width = "77",
							ZOrder = "1",
						},
					},
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "31",
					ignoreSize = "True",
					name = "Img_shouci",
					scaleX = "0.8",
					scaleY = "0.8",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/vip300.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 16,
						PositionY = 151,
					},
					width = "49",
					ZOrder = "1",
				},
				{
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "45",
					ignoreSize = "True",
					name = "img_keyongzengquan",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/pay/icon_zengquan1.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 17,
						PositionY = 28,
					},
					width = "45",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/pay/VIP_chongzhidi.png",
			"ui_new/pay/VIP_yb.png",
			"ui_new/pay/VIP_rmb.png",
			"ui_new/common/icon_sycee.png",
			"ui_new/pay/vip60.png",
			"ui_new/pay/vip300.png",
			"ui_new/pay/icon_zengquan1.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

