local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-VipItemCell_group_pay_Game",
			UUID = "7f395160_6975_4627_8fcc_e61a2887e211",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "191",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "btn_node_Panel-VipItemCell_group_pay_Game",
					UUID = "439a57c0_ff44_4a9c_ae0e_61f4415ffd2c",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					disabled = "ui_new/common/icon_bg/icon_bg_normal.png",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "162",
					ignoreSize = "True",
					name = "btn_node",
					normal = "ui_new/shop/bg_item_cell.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 68,
						PositionY = 114,
					},
					UItype = "Button",
					width = "130",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "btn_icon_btn_node_Panel-VipItemCell_group_pay_Game",
							UUID = "82d2ec71_e713_4255_af06_984e01311091",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "130",
							ignoreSize = "True",
							name = "btn_icon",
							normal = "ui_new/common/icon_bg/pz_bg_jia_124.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 16,
							},
							UItype = "Button",
							width = "130",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_icon_btn_icon_btn_node_Panel-VipItemCell_group_pay_Game",
									UUID = "f7b5b6f0_9aad_42cf_b3ac_6c4e5c927159",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "img_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									texturePath = "icon/item/2290.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "txt_number_btn_node_Panel-VipItemCell_group_pay_Game",
							UUID = "7404d8a1_7852_4e12_ab76_ad4f79384b93",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0.5",
							classname = "MELabelBMFont",
							dstBlendFunc = "771",
							fileNameData = "font/num_212.fnt",
							height = "31",
							ignoreSize = "True",
							name = "txt_number",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							text = "50",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 58,
								PositionY = -27,
							},
							width = "32",
							ZOrder = "1",
						},
						{
							controlID = "txt_name_btn_node_Panel-VipItemCell_group_pay_Game",
							UUID = "b5d0da09_82fd_453d_818c_fb95b0ce51a0",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							ColorMixing = "#00FFFFFF",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF3D3D3D",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "20",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "26",
							ignoreSize = "True",
							name = "txt_name",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "达摩闭息功残章",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -64,
							},
							width = "142",
							ZOrder = "1",
						},
						{
							controlID = "img_res_bg_btn_node_Panel-VipItemCell_group_pay_Game",
							UUID = "bcd4d39a_94e2_4514_8a22_5eefda8e288f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "24",
							ignoreSize = "True",
							name = "img_res_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/shop/bg_shop_item.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1,
								PositionY = -99,
							},
							width = "122",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_res_icon_img_res_bg_btn_node_Panel-VipItemCell_group_pay_Game",
									UUID = "67f8c671_0854_439d_92d1_ae6081e8655b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "46",
									ignoreSize = "True",
									name = "img_res_icon",
									scaleX = "0.8",
									scaleY = "0.8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_gbjf.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -49,
									},
									width = "47",
									ZOrder = "1",
								},
								{
									controlID = "txt_price_img_res_bg_btn_node_Panel-VipItemCell_group_pay_Game",
									UUID = "0473a9e5_445e_4cea_b584_8b19879ac8c7",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FFF0F8FF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "txt_price",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "8800",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 51,
									},
									width = "61",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "img_sold_out_btn_node_Panel-VipItemCell_group_pay_Game",
							UUID = "697cd21b_10f7_4af1_99e6_0e2a2f82d873",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "87",
							ignoreSize = "True",
							name = "img_sold_out",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/shop/sold_out.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 14,
							},
							width = "34",
							ZOrder = "1",
						},
						{
							controlID = "img_zhekou_btn_node_Panel-VipItemCell_group_pay_Game",
							UUID = "ced06ed9_6eb9_4167_84db_64fc8bfa6e27",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "62",
							ignoreSize = "True",
							name = "img_zhekou",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/shop/icon_zhekou.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -34,
								PositionY = 50,
							},
							width = "62",
							ZOrder = "1",
						},
						{
							controlID = "bg_time_btn_node_Panel-VipItemCell_group_pay_Game",
							UUID = "13517173_8dde_44a2_86bc_7fe481c4dfd8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "43",
							ignoreSize = "True",
							name = "bg_time",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/shop/bg_time.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 27,
								PositionY = 65,
							},
							visible = "False",
							width = "81",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "LabelBMFont_ShopItemCell_1_bg_time_btn_node_Panel-VipItemCell_group_pay_Game",
									UUID = "5506a8ba_0453_458b_8872_3d6072acc5b4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_212.fnt",
									height = "31",
									ignoreSize = "True",
									name = "LabelBMFont_ShopItemCell_1",
									scaleX = "0.75",
									scaleY = "0.75",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "00:00",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 6,
										PositionY = -8,
									},
									width = "69",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/shop/bg_item_cell.png",
			"ui_new/common/icon_bg/icon_bg_normal.png",
			"ui_new/common/icon_bg/pz_bg_jia_124.png",
			"icon/item/2290.png",
			"ui_new/shop/bg_shop_item.png",
			"ui_new/pay/img_gbjf.png",
			"ui_new/shop/sold_out.png",
			"ui_new/shop/icon_zhekou.png",
			"ui_new/shop/bg_time.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

