local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-VipLayer_group_pay_Game",
			UUID = "9c99051c_ac4a_4ec9_a06c_69809f644d7b",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "True",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "panel_content_Panel-VipLayer_group_pay_Game",
					UUID = "388b9e11_18bf_4c16_88f8_a9e6233c1ee9",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_content",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "bda2e20a_8f85_405b_9d8f_055ba4799c3e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "635",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/VIP_bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
							},
							width = "989",
							ZOrder = "1",
						},
						{
							controlID = "img_VIP_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "d3c261ab_fe2d_425f_b183_b57823e6f33a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "363",
							ignoreSize = "True",
							name = "img_VIP",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui_new/pay/VIP8.jpg",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 693,
								PositionY = 283,
							},
							width = "407",
							ZOrder = "1",
						},
						{
							controlID = "panel_img_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "57878b95_64d7_4899_8726_b723e7a5cb17",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "453",
							ignoreSize = "False",
							name = "panel_img",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 400,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "500",
							ZOrder = "1",
						},
						{
							controlID = "bg2_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "a4dae064_8259_40ac_b7f3_4a617188adcc",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "112",
							ignoreSize = "True",
							name = "bg2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/VIP_g1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 507,
							},
							width = "805",
							ZOrder = "1",
						},
						{
							controlID = "bg_vipList_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "9e1b96e4_732c_454d_afc4_918ac51d3171",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "340",
							ignoreSize = "False",
							name = "bg_vipList",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/bg_tequan.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 280,
								PositionY = 210,
							},
							width = "370",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "sv_vipinfo_bg_vipList_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "a86b80b4_be09_4de9_8d13_4e91989714e1",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "335",
									ignoreSize = "False",
									innerHeight = "340",
									innerWidth = "370",
									name = "sv_vipinfo",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -184,
										PositionY = -167,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "370",
									ZOrder = "1",
								},
								{
									controlID = "img_di1_bg_vipList_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "6f0e3e28_9366_4dd3_abad_de59ccbf359e",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "11",
									ignoreSize = "False",
									name = "img_di1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/array/js_xiantiao_icon.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -184,
										PositionY = -168,
									},
									width = "367",
									ZOrder = "11",
								},
								{
									controlID = "img_di2_bg_vipList_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "a62f156f_e400_4aa6_b360_e2d3ffbf908d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									flipY = "True",
									height = "11",
									ignoreSize = "False",
									name = "img_di2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/array/js_xiantiao_icon.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -184,
										PositionY = 158,
									},
									width = "367",
									ZOrder = "11",
								},
							},
						},
						{
							controlID = "img_fisrtPay_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "747398e4_4baf_4a4e_92d0_8211aaade042",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "52",
							ignoreSize = "True",
							name = "img_fisrtPay",
							scaleX = "0.6",
							scaleY = "0.6",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/VIP_shouchongfanbei.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 199,
								PositionY = 556,
							},
							visible = "False",
							width = "168",
							ZOrder = "1",
						},
						{
							controlID = "btn_pay_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "7b8fd5db_59f1_4455_a0dd_d01007df0d01",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "METextButton",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "btn_pay",
							normal = "ui_new/pay/VIP_chongzhi.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							titlefontName = "宋体",
							titlefontSize = "24",
							titletext = " ",
							titletextColor = "#FFFFFFFF",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 199,
								PositionY = 503,
							},
							visible = "False",
							width = "156",
							ZOrder = "1",
						},
						{
							controlID = "node_vip_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "010830e2_2f9f_4f66_a6fe_6a6f39cf26b7",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_vip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 220,
								PositionY = 405,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_curVip_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "21cd0bc5_d3bc_4936_8d48_fe7c3a4f6bd5",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o15",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 68,
										PositionY = 132,
									},
									width = "114",
									ZOrder = "1",
								},
								{
									controlID = "txt_needMoney_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "0665de0e_94fd_4f8f_9e54_d85f0c7f6f2d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_217.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_needMoney",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "500000",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 108,
										PositionY = 68,
									},
									width = "92",
									ZOrder = "1",
								},
								{
									controlID = "lb3_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "41613dd7_dc16_48d1_9add_d822fc5c038c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb3",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "再充值",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 21,
										PositionY = 71,
									},
									width = "80",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "99259d7f_42c8_4ba3_8749_4b2f53b9b8d0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "即可成为",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 205,
										PositionY = 71,
									},
									width = "104",
									ZOrder = "1",
								},
								{
									controlID = "bg_bar_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "2a85d2db_f413_434e_99a3_c2e31ed92300",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "22",
									ignoreSize = "False",
									name = "bg_bar",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_jidudi.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 349,
										PositionY = 126,
									},
									width = "300",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "bar_value_bg_bar_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
											UUID = "25314ce1_e273_4b00_8b97_49ea149a9b2e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MELoadingBar",
											direction = "0",
											dstBlendFunc = "771",
											height = "22",
											ignoreSize = "False",
											name = "bar_value",
											percent = "100",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texture = "ui_new/pay/VIP_jidu.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "300",
											ZOrder = "1",
										},
										{
											controlID = "txt_value_bg_bar_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
											UUID = "9dbe6d0b_47f4_4c17_b09b_cabfbfaf9e69",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabelBMFont",
											dstBlendFunc = "771",
											fileNameData = "font/num_217.fnt",
											height = "27",
											ignoreSize = "True",
											name = "txt_value",
											scaleX = "0.7",
											scaleY = "0.7",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "10000",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 1,
											},
											width = "77",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "img_yuanbao_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "f01bd58b_b805_4837_abd3_70645022bd94",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "48",
									ignoreSize = "True",
									name = "img_yuanbao",
									scaleX = "0.8",
									scaleY = "0.8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/common/yuanbao2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 84,
										PositionY = 72,
									},
									width = "51",
									ZOrder = "1",
								},
								{
									controlID = "txt_nextVip_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "3e5f4f37_c3eb_4690_bf26_8c560445a0b7",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 322,
										PositionY = 76,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "img_zunjingde_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "6b979630_f2fd_43bd_b9cf_74618dfa5eac",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "25",
									ignoreSize = "True",
									name = "img_zunjingde",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_w2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 20,
										PositionY = 126,
									},
									width = "71",
									ZOrder = "1",
								},
								{
									controlID = "img_curVip_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "147ed758_df0b_479e_af41_edb5af63d4b1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "img_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 117,
										PositionY = 132,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "img_nextVip_node_vip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "d9434fed_6aaf_4b98_8847_0560c9385272",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "img_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 346,
										PositionY = 76,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "node_notVip_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "09cf31d1_b627_4b9e_8144_d86cec23178a",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_notVip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 75,
								PositionY = -703,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_needMoney_node_notVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "a374e82a_643b_454f_a0c4_0b87452e384e",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_14.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_needMoney",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "0",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 112,
									},
									width = "20",
									ZOrder = "1",
								},
								{
									controlID = "lb1_node_notVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "e8615e0a_d523_4619_9328_31ca6a11f547",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "您不是VIP，充值",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 73,
									},
									width = "200",
									ZOrder = "1",
								},
								{
									controlID = "img_rmb_node_notVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "82165858_b98a_45f9_845d_0e8e896336db",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "33",
									ignoreSize = "True",
									name = "img_rmb",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_rmb.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 97,
									},
									width = "26",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_notVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "8546c788_1271_4b75_b2d7_f1ea1bb6ec6b",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "享受",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 137,
									},
									width = "55",
									ZOrder = "1",
								},
								{
									controlID = "txt_nextVip_node_notVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "cb8ef0f3_1fdd_459c_9b62_7de8616dafc2",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 191,
										PositionY = 4,
									},
									width = "69",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "85dde8b9_109b_4742_a6a1_a3218f280cca",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_topVip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 355,
								PositionY = 476,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_vip_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "c88ae174_526a_41b3_a4c2_703412792f3c",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "60",
									ignoreSize = "False",
									name = "Panel_vip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -116,
										PositionY = 22,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "450",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "img_zunjing_Panel_vip_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
											UUID = "7379c9c9_b7b4_4e96_bf73_63da61bc249c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "25",
											ignoreSize = "True",
											name = "img_zunjing",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/pay/VIP_w2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												PositionY = 33,
											},
											width = "71",
											ZOrder = "1",
										},
										{
											controlID = "img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
											UUID = "c3519a35_c0f1_4320_ae3a_0cc21f97570f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "22",
											ignoreSize = "False",
											name = "img_jindutiao",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/pay/VIP_jidudi.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 330,
												PositionY = 33,
											},
											width = "300",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "LoadingBar_vip_img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
													UUID = "836abb89_cfb9_4707_a115_3bba3f1e7e97",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
													classname = "MELoadingBar",
													direction = "0",
													dstBlendFunc = "771",
													height = "22",
													ignoreSize = "False",
													name = "LoadingBar_vip",
													percent = "100",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texture = "ui_new/pay/VIP_jidu.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "300",
													ZOrder = "1",
												},
												{
													controlID = "txt_jindu_img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
													UUID = "68a3391b_682c_4cc3_b9ed_0b7ac2cf46c1",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabelBMFont",
													dstBlendFunc = "771",
													fileNameData = "font/num_217.fnt",
													height = "27",
													ignoreSize = "True",
													name = "txt_jindu",
													scaleX = "0.7",
													scaleY = "0.7",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													text = "10000",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionY = 1,
													},
													width = "77",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "txt_curVip_Panel_vip_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
											UUID = "d986d9ca_019e_4d9d_8ee2_034961d902f2",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabelBMFont",
											dstBlendFunc = "771",
											fileNameData = "font/num_37.fnt",
											height = "27",
											ignoreSize = "True",
											name = "txt_curVip",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "o15",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 49,
												PositionY = 39,
											},
											width = "114",
											ZOrder = "1",
										},
										{
											controlID = "img_vip_Panel_vip_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
											UUID = "3a6f0556_b395_46b9_b06c_39e6922a6059",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "64",
											ignoreSize = "True",
											name = "img_vip",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 98,
												PositionY = 39,
											},
											visible = "False",
											width = "64",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "img1_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "b83dd232_bdbf_4761_b05d_de2d050eefd2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "43",
									ignoreSize = "True",
									name = "img1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/cz_zz_word.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 86,
										PositionY = 2,
									},
									width = "65",
									ZOrder = "1",
								},
								{
									controlID = "txt_curVip_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "3a78f09b_b235_4a92_8842_e269e90ca230",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 153,
										PositionY = 7,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "233f306d_5d4d_4217_a0d6_68271326e8f9",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "啦！",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 217,
										PositionY = 2,
									},
									width = "43",
									ZOrder = "1",
								},
								{
									controlID = "lb1_node_topVip_panel_content_Panel-VipLayer_group_pay_Game",
									UUID = "81c1c0de_f221_428a_af4e_4d2111016072",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "您已经是",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -11,
										PositionY = 2,
									},
									width = "107",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "panel_vip_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "70ecb0f6_2e36_4ddf_a9f1_f8515554e91c",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "420",
							ignoreSize = "False",
							name = "panel_vip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 66,
								PositionY = 30,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "825",
							ZOrder = "1",
						},
						{
							controlID = "img_role_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "49225434_91ca_4f12_8f99_5f1b1352fa00",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "408",
							ignoreSize = "True",
							name = "img_role",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/zhongling.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 70,
								PositionY = 236,
							},
							visible = "False",
							width = "285",
							ZOrder = "1",
						},
						{
							controlID = "btn_pageleft_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "83b10a95_7b1c_4032_9e67_b27fe878b34a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "83",
							HitType = 
							{
								nHitType = 1,
								nXpos = -32,
								nYpos = -40,
								nHitWidth = 62,
								nHitHeight = 166
							},
							ignoreSize = "True",
							name = "btn_pageleft",
							normal = "ui_new/common/right.png",
							scaleX = "-1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 81,
								PositionY = 240,
							},
							UItype = "Button",
							width = "33",
							ZOrder = "1",
						},
						{
							controlID = "btn_pageright_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "ebc77ec0_43f5_4b2c_af93_a93eb9a69ad0",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "83",
							HitType = 
							{
								nHitType = 1,
								nXpos = -11,
								nYpos = -33,
								nHitWidth = 64,
								nHitHeight = 151
							},
							ignoreSize = "True",
							name = "btn_pageright",
							normal = "ui_new/common/right.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 903,
								PositionY = 240,
							},
							UItype = "Button",
							width = "33",
							ZOrder = "1",
						},
						{
							controlID = "Img_biaoti_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "10570439_4a78_4970_b4b2_1f4a894f9622",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Img_biaoti",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 218,
								PositionY = -322,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "btn_cz_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "09e2073d_55b2_4ec2_b90c_460b146ff7c9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_cz",
							normal = "ui_new/pay/btn_cz1.png",
							pressed = "ui_new/pay/btn_cz2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 480,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
						{
							controlID = "btn_tq_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "0e20dad7_2bfa_4279_ab3c_283640e0ce43",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_tq",
							normal = "ui_new/pay/btn_tq2.png",
							pressed = "ui_new/pay/btn_tq2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 375,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
						{
							controlID = "btn_sc_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "4bdecaf5_7db9_4c05_82c4_5a9d4d9f6a34",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_sc",
							normal = "ui_new/pay/btn_sc1.png",
							pressed = "ui_new/pay/btn_sc2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 270,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
						{
							controlID = "btn_close_panel_content_Panel-VipLayer_group_pay_Game",
							UUID = "be106b81_a1e7_4e8c_86ae_a6daf39077be",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "65",
							HitType = 
							{
								nHitType = 2,
								nRadius = 60,
							},
							ignoreSize = "True",
							name = "btn_close",
							normal = "ui_new/common/common_close_icon.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 923,
								PositionY = 493,
							},
							UItype = "Button",
							width = "65",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/pay/VIP_bg.png",
			"ui_new/pay/VIP8.jpg",
			"ui_new/pay/VIP_g1.png",
			"ui_new/pay/bg_tequan.png",
			"ui_new/array/js_xiantiao_icon.png",
			"ui_new/pay/VIP_shouchongfanbei.png",
			"ui_new/pay/VIP_chongzhi.png",
			"ui_new/pay/VIP_jidudi.png",
			"ui_new/pay/VIP_jidu.png",
			"ui_new/common/yuanbao2.png",
			"ui_new/pay/VIP_w2.png",
			"ui_new/pay/VIP_rmb.png",
			"ui_new/pay/cz_zz_word.png",
			"ui_new/pay/zhongling.png",
			"ui_new/common/right.png",
			"ui_new/pay/btn_cz2.png",
			"ui_new/pay/btn_cz1.png",
			"ui_new/pay/btn_tq2.png",
			"ui_new/pay/btn_sc2.png",
			"ui_new/pay/btn_sc1.png",
			"ui_new/common/common_close_icon.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

