local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-VipShopLayer_group_pay_Game",
			UUID = "4c73b6ef_d33c_4576_b8fc_7693c3a84838",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "True",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "panel_content_Panel-VipShopLayer_group_pay_Game",
					UUID = "ee189ac8_26ce_4ace_b3c1_28329ab98810",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_content",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "e10295c5_bc3e_4a0f_be1e_e06035d88bfb",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "635",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/VIP_bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
							},
							width = "989",
							ZOrder = "1",
						},
						{
							controlID = "img_VIP_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "91af0d26_5823_4a64_9c96_2e33f732237d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "363",
							ignoreSize = "True",
							name = "img_VIP",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui_new/pay/VIP8.jpg",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 693,
								PositionY = 283,
							},
							visible = "False",
							width = "407",
							ZOrder = "1",
						},
						{
							controlID = "panel_img_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "16c25c0b_72e5_4a7e_bef7_12bc2f5fe9d1",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "453",
							ignoreSize = "False",
							name = "panel_img",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 400,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "500",
							ZOrder = "1",
						},
						{
							controlID = "bg2_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "9572f320_d996_43e5_a952_d139a54982b5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "47",
							ignoreSize = "True",
							name = "bg2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/img_bg_di.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 529,
							},
							width = "551",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_tips_bg2_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "7d48afb0_2508_490f_bb18_cc5d4fe0639c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "27",
									ignoreSize = "True",
									name = "img_tips",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_tips.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "424",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "bg_vipList_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "e23e66bc_fb23_4e81_9c55_15d28add4958",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "340",
							ignoreSize = "False",
							name = "bg_vipList",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/bg_tequan.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 280,
								PositionY = 210,
							},
							visible = "False",
							width = "370",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "sv_vipinfo_bg_vipList_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "7686384a_9468_4049_a7ac_41841713f184",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "335",
									ignoreSize = "False",
									innerHeight = "340",
									innerWidth = "370",
									name = "sv_vipinfo",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -184,
										PositionY = -167,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "370",
									ZOrder = "1",
								},
								{
									controlID = "img_di1_bg_vipList_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "6a27e2d2_56d3_40f5_b11b_8747e493e69e",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "11",
									ignoreSize = "False",
									name = "img_di1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/array/js_xiantiao_icon.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -184,
										PositionY = -168,
									},
									width = "367",
									ZOrder = "11",
								},
								{
									controlID = "img_di2_bg_vipList_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "dffed77f_27f4_486f_b313_ae8e0d36ea1f",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									flipY = "True",
									height = "11",
									ignoreSize = "False",
									name = "img_di2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/array/js_xiantiao_icon.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -184,
										PositionY = 158,
									},
									width = "367",
									ZOrder = "11",
								},
							},
						},
						{
							controlID = "img_fisrtPay_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "e9e279f0_42d4_48b0_842e_28065c58625a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "52",
							ignoreSize = "True",
							name = "img_fisrtPay",
							scaleX = "0.6",
							scaleY = "0.6",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/pay/VIP_shouchongfanbei.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 199,
								PositionY = 556,
							},
							visible = "False",
							width = "168",
							ZOrder = "1",
						},
						{
							controlID = "btn_pay_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "4178e02e_c73d_4d8b_9493_15ea9aa6cca8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "METextButton",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "btn_pay",
							normal = "ui_new/pay/VIP_chongzhi.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							titlefontName = "宋体",
							titlefontSize = "24",
							titletext = " ",
							titletextColor = "#FFFFFFFF",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 199,
								PositionY = 503,
							},
							visible = "False",
							width = "156",
							ZOrder = "1",
						},
						{
							controlID = "Image_VipShopLayer_1_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "dd099adc_aab4_46d0_b4c5_03f621b4988c",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							flipX = "True",
							height = "30",
							ignoreSize = "False",
							name = "Image_VipShopLayer_1",
							opacity = "100",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/common/gk_detail1_bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 781,
								PositionY = 41,
							},
							width = "650",
							ZOrder = "1",
						},
						{
							controlID = "txt_wenzi_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "c87d54a5_32f3_48a3_8ac2_b205650fe6ab",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							ColorMixing = "#00FFFFFF",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF3D3D3D",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "18",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "24",
							ignoreSize = "True",
							name = "txt_wenzi",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "每日0点自动刷新，刷新时会重置且重新随机所有栏位的物品和折扣",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 484,
								PositionY = 41,
							},
							width = "534",
							ZOrder = "1",
						},
						{
							controlID = "node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "9b6846ec_6eaa_48a1_812a_abd99af5d225",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_vip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 220,
								PositionY = 405,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_curVip_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "44f1a528_2515_449f_99cd_33fb89a355c8",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o15",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 68,
										PositionY = 132,
									},
									width = "114",
									ZOrder = "1",
								},
								{
									controlID = "txt_needMoney_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "e920316e_f27b_4666_ad4e_8514ba8e745d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_217.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_needMoney",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "500000",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 108,
										PositionY = 68,
									},
									width = "92",
									ZOrder = "1",
								},
								{
									controlID = "lb3_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "50a78652_e660_4891_b6fa_437053121291",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb3",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "再充值",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 21,
										PositionY = 71,
									},
									width = "80",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "3687303b_2b90_4409_b9a2_f8b798349831",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "即可成为",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 205,
										PositionY = 71,
									},
									width = "104",
									ZOrder = "1",
								},
								{
									controlID = "bg_bar_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "ba4445fd_0687_4613_a27a_15aba1371f27",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "22",
									ignoreSize = "False",
									name = "bg_bar",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_jidudi.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 349,
										PositionY = 126,
									},
									width = "300",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "bar_value_bg_bar_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
											UUID = "4de2fe6f_be99_44c3_b26e_2374910d0b31",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MELoadingBar",
											direction = "0",
											dstBlendFunc = "771",
											height = "22",
											ignoreSize = "False",
											name = "bar_value",
											percent = "100",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texture = "ui_new/pay/VIP_jidu.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "300",
											ZOrder = "1",
										},
										{
											controlID = "txt_value_bg_bar_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
											UUID = "3274fc9e_7d9f_400b_a42b_ce821bb8ccab",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabelBMFont",
											dstBlendFunc = "771",
											fileNameData = "font/num_217.fnt",
											height = "27",
											ignoreSize = "True",
											name = "txt_value",
											scaleX = "0.7",
											scaleY = "0.7",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "10000",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 1,
											},
											width = "77",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "img_yuanbao_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "f4ce3897_2fc2_42bc_928d_5356ef70f6bd",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "48",
									ignoreSize = "True",
									name = "img_yuanbao",
									scaleX = "0.8",
									scaleY = "0.8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/common/yuanbao2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 84,
										PositionY = 72,
									},
									width = "51",
									ZOrder = "1",
								},
								{
									controlID = "txt_nextVip_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "a1b62fa3_90a3_46ce_add9_e324ddca8183",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 322,
										PositionY = 76,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "img_zunjingde_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "d86e3b68_afbf_40d7_b9de_803e8a3634af",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "25",
									ignoreSize = "True",
									name = "img_zunjingde",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_w2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 20,
										PositionY = 126,
									},
									width = "71",
									ZOrder = "1",
								},
								{
									controlID = "img_curVip_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "e6cc0340_dfba_457c_a9ad_9f0bc3daa230",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "img_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 117,
										PositionY = 132,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "img_nextVip_node_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "b9f48560_c55b_49ef_82c1_742f3f8c4118",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "img_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 346,
										PositionY = 76,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "node_notVip_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "91ca3cc4_cd10_4549_8907_2f303acc2a79",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_notVip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 75,
								PositionY = -703,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_needMoney_node_notVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "fa6cc072_98a9_45be_8902_4bfb48d1c475",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_14.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_needMoney",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "0",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 112,
									},
									width = "20",
									ZOrder = "1",
								},
								{
									controlID = "lb1_node_notVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "4e114691_eaa0_4c1d_b499_d7d3490c55e9",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "您不是VIP，充值",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 73,
									},
									width = "200",
									ZOrder = "1",
								},
								{
									controlID = "img_rmb_node_notVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "ef5a218b_035d_48cc_b3f6_c76d7342bb96",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "33",
									ignoreSize = "True",
									name = "img_rmb",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/VIP_rmb.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 97,
									},
									width = "26",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_notVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "4ecfa3b5_b518_4430_8f38_ca11f16df38c",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "享受",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 137,
									},
									width = "55",
									ZOrder = "1",
								},
								{
									controlID = "txt_nextVip_node_notVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "175eca78_430e_4853_9a1a_31c13d78900e",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_nextVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 191,
										PositionY = 4,
									},
									width = "69",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "84797850_1b70_468f_aa86_fe57f6a77673",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "node_topVip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 355,
								PositionY = 476,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "100",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_vip_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "eab4f6e1_c65a_4943_8d81_9b1a72565854",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "60",
									ignoreSize = "False",
									name = "Panel_vip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -116,
										PositionY = 22,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "450",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "img_zunjing_Panel_vip_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
											UUID = "1d754ec2_d741_4176_a8a3_c76ee767e479",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "25",
											ignoreSize = "True",
											name = "img_zunjing",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/pay/VIP_w2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												PositionY = 33,
											},
											width = "71",
											ZOrder = "1",
										},
										{
											controlID = "img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
											UUID = "e3d941db_0276_43f5_8244_0c1ea547bffa",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "22",
											ignoreSize = "False",
											name = "img_jindutiao",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui_new/pay/VIP_jidudi.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 330,
												PositionY = 33,
											},
											width = "300",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "LoadingBar_vip_img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
													UUID = "8d951acc_b493_4e97_98a4_2e10c9f54f8f",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
													classname = "MELoadingBar",
													direction = "0",
													dstBlendFunc = "771",
													height = "22",
													ignoreSize = "False",
													name = "LoadingBar_vip",
													percent = "100",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texture = "ui_new/pay/VIP_jidu.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "300",
													ZOrder = "1",
												},
												{
													controlID = "txt_jindu_img_jindutiao_Panel_vip_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
													UUID = "4e5b7d4c_a472_4ed2_94ae_5477450101af",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabelBMFont",
													dstBlendFunc = "771",
													fileNameData = "font/num_217.fnt",
													height = "27",
													ignoreSize = "True",
													name = "txt_jindu",
													scaleX = "0.7",
													scaleY = "0.7",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													text = "10000",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionY = 1,
													},
													width = "77",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "txt_curVip_Panel_vip_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
											UUID = "1a10c615_0a62_4342_b804_9a2848dbb5f7",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabelBMFont",
											dstBlendFunc = "771",
											fileNameData = "font/num_37.fnt",
											height = "27",
											ignoreSize = "True",
											name = "txt_curVip",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "o15",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 49,
												PositionY = 39,
											},
											width = "114",
											ZOrder = "1",
										},
										{
											controlID = "img_vip_Panel_vip_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
											UUID = "8e69e20a_0e13_4040_8449_2391b1e67677",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "64",
											ignoreSize = "True",
											name = "img_vip",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 98,
												PositionY = 39,
											},
											visible = "False",
											width = "64",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "img1_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "6a13b05b_1f84_45c0_b832_d687fa680a0c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "43",
									ignoreSize = "True",
									name = "img1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/cz_zz_word.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 86,
										PositionY = 2,
									},
									width = "65",
									ZOrder = "1",
								},
								{
									controlID = "txt_curVip_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "c7715b07_af75_4aac_ba77_5457d9cd8439",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_37.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_curVip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "o",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 153,
										PositionY = 7,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "lb2_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "0f4454e5_ddda_44a5_b89d_bf128bf0bab2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "啦！",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 217,
										PositionY = 2,
									},
									width = "43",
									ZOrder = "1",
								},
								{
									controlID = "lb1_node_topVip_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "115d7ba9_f527_4663_966a_fee5f58f48ca",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3D3D3D",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "lb1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "您已经是",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -11,
										PositionY = 2,
									},
									width = "107",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "panel_vip_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "8729dd20_69b2_4f1a_923e_be92e573895c",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "433",
							ignoreSize = "False",
							name = "panel_vip",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 66,
								PositionY = 67,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "825",
							ZOrder = "1",
						},
						{
							controlID = "btn_pageleft_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "c14855a4_b178_454b_b631_8f48aa90406e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "83",
							ignoreSize = "True",
							name = "btn_pageleft",
							normal = "ui_new/common/right.png",
							scaleX = "-1.2",
							scaleY = "1.2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 56,
								PositionY = 230,
							},
							UItype = "Button",
							visible = "False",
							width = "33",
							ZOrder = "1",
						},
						{
							controlID = "btn_pageright_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "8b1a17e6_4d11_44c8_a494_db52b80585bf",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "83",
							ignoreSize = "True",
							name = "btn_pageright",
							normal = "ui_new/common/right.png",
							scaleX = "1.2",
							scaleY = "1.2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 900,
								PositionY = 230,
							},
							UItype = "Button",
							visible = "False",
							width = "33",
							ZOrder = "1",
						},
						{
							controlID = "Img_biaoti_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "a19529a5_d1fb_4e79_a43b_4e9d18657706",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Img_biaoti",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 218,
								PositionY = -322,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "btn_cz_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "2eb1addd_37c4_45be_b443_dd7bd6371290",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_cz",
							normal = "ui_new/pay/btn_cz1.png",
							pressed = "ui_new/pay/btn_cz2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 480,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
						{
							controlID = "btn_tq_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "88d9b536_346c_4161_a82b_afd54e3c3ad3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_tq",
							normal = "ui_new/pay/btn_tq1.png",
							pressed = "ui_new/pay/btn_tq2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 375,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
						{
							controlID = "btn_sc_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "a13d42cf_d5d6_437e_835a_9e881161aefc",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "121",
							HitType = 
							{
								nHitType = 1,
								nXpos = 28,
								nYpos = 0,
								nHitWidth = 72,
								nHitHeight = 104
							},
							ignoreSize = "True",
							name = "btn_sc",
							normal = "ui_new/pay/btn_sc2.png",
							pressed = "ui_new/pay/btn_sc2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 39,
								PositionY = 270,
							},
							UItype = "Button",
							width = "141",
							ZOrder = "1",
						},
						{
							controlID = "btn_close_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "2abe1872_af05_49c8_9cbf_a1eafe4e6559",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "65",
							ignoreSize = "True",
							name = "btn_close",
							normal = "ui_new/common/common_close_icon.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 923,
								PositionY = 493,
							},
							UItype = "Button",
							width = "65",
							ZOrder = "1",
						},
						{
							controlID = "btn_refresh_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "f8c85d8b_6e48_4654_8c27_a1f77bc473e3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "56",
							ignoreSize = "True",
							name = "btn_refresh",
							normal = "ui_new/shop/shop_shuaxin_btn.png",
							pressed = "ui_new/shop/shop_shuaxin_btn.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 811,
								PositionY = 46,
							},
							UItype = "Button",
							width = "103",
							ZOrder = "1",
						},
						{
							controlID = "img_res_bg_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "4cc845e9_d071_46aa_b546_8aa650db8657",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "24",
							ignoreSize = "True",
							name = "img_res_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/shop/bg_shop_item.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 785,
								PositionY = 528,
							},
							width = "122",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_res_icon_img_res_bg_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "cbd09968_385e_4645_8173_59b2f6b416b6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "41",
									ignoreSize = "True",
									name = "img_res_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/pay/img_gbjf.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -49,
									},
									width = "35",
									ZOrder = "1",
								},
								{
									controlID = "txt_price_img_res_bg_panel_content_Panel-VipShopLayer_group_pay_Game",
									UUID = "96433c73_aee5_46bd_a0c2_fe8d75ccc1b1",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FFF0F8FF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "txt_price",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "8800",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 51,
									},
									width = "61",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "txt_VIP_panel_content_Panel-VipShopLayer_group_pay_Game",
							UUID = "56a100eb_e719_4f47_83a2_2254c4af1d01",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0.5",
							classname = "MELabel",
							ColorMixing = "#00FFFFFF",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFBD4A30",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "16",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "21",
							ignoreSize = "True",
							name = "txt_VIP",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "VIP等级越高，低折扣概率越高",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 752,
								PositionY = 66,
							},
							width = "221",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/pay/VIP_bg.png",
			"ui_new/pay/VIP8.jpg",
			"ui_new/pay/img_bg_di.png",
			"ui_new/pay/img_tips.png",
			"ui_new/pay/bg_tequan.png",
			"ui_new/array/js_xiantiao_icon.png",
			"ui_new/pay/VIP_shouchongfanbei.png",
			"ui_new/pay/VIP_chongzhi.png",
			"ui_new/common/gk_detail1_bg.png",
			"ui_new/pay/VIP_jidudi.png",
			"ui_new/pay/VIP_jidu.png",
			"ui_new/common/yuanbao2.png",
			"ui_new/pay/VIP_w2.png",
			"ui_new/pay/VIP_rmb.png",
			"ui_new/pay/cz_zz_word.png",
			"ui_new/common/right.png",
			"ui_new/pay/btn_cz2.png",
			"ui_new/pay/btn_cz1.png",
			"ui_new/pay/btn_tq2.png",
			"ui_new/pay/btn_tq1.png",
			"ui_new/pay/btn_sc2.png",
			"ui_new/common/common_close_icon.png",
			"ui_new/shop/shop_shuaxin_btn.png",
			"ui_new/shop/bg_shop_item.png",
			"ui_new/pay/img_gbjf.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

